# golangci-lint configuration
# See: https://golangci-lint.run/usage/configuration/
version: "2"

linters:
  enable:
    - godox  # Detects TODO, FIXME, BUG comments
  disable:
    - staticcheck  # We run staticcheck separately (built from source to match Go version)

linters-settings:
  godox:
    # Keywords to check for - these should become GitHub issues instead
    keywords:
      - TODO
      - FIXME
      - BUG
      - HACK
      - XXX

issues:
  # Exclude generated files
  exclude-dirs:
    - gen
