# golangci-lint configuration
# See: https://golangci-lint.run/usage/configuration/
version: "2"

linters:
  enable:
    - godox       # Detects TODO, FIXME, BUG comments
    - errorlint   # Ensures proper error wrapping with %w
  disable:
    - staticcheck  # We run staticcheck separately (built from source to match Go version)

linters-settings:
  godox:
    # Keywords to check for - these should become GitHub issues instead
    keywords:
      - TODO
      - FIXME
      - BUG
      - HACK
      - XXX
  
  errorlint:
    # Check that fmt.Errorf uses %w instead of %v for error wrapping
    errorf: true
    # Allow multiple %w verbs in fmt.Errorf (Go 1.20+)
    errorf-multi: true
    # Check that errors.Is() is used instead of == for sentinel error comparisons
    asserts: true
    # Check that errors.As() is used instead of type assertions for error types
    comparison: true

issues:
  # Exclude generated files
  exclude-dirs:
    - gen
