// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/inventory.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package api.v1;

@kotlin.jvm.JvmName("-initializecontainerPath")
public inline fun containerPath(block: api.v1.ContainerPathKt.Dsl.() -> kotlin.Unit): api.v1.Inventory.ContainerPath =
  api.v1.ContainerPathKt.Dsl._create(api.v1.Inventory.ContainerPath.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `api.v1.ContainerPath`
 */
public object ContainerPathKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: api.v1.Inventory.ContainerPath.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: api.v1.Inventory.ContainerPath.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): api.v1.Inventory.ContainerPath = _builder.build()

    /**
     * ```
     * The immediate container.
     * ```
     *
     * `string container = 1 [json_name = "container"];`
     */
    public var container: kotlin.String
      @JvmName("getContainer")
      get() = _builder.container
      @JvmName("setContainer")
      set(value) {
        _builder.container = value
      }
    /**
     * ```
     * The immediate container.
     * ```
     *
     * `string container = 1 [json_name = "container"];`
     */
    public fun clearContainer() {
      _builder.clearContainer()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class PathProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * Full path from root to this item (if include_hierarchy was true).
     * Each entry is a container identifier, from outermost to innermost.
     * ```
     *
     * `repeated string path = 2 [json_name = "path"];`
     * @return A list containing the path.
     */
    public val path: com.google.protobuf.kotlin.DslList<kotlin.String, PathProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.pathList
      )
    /**
     * ```
     * Full path from root to this item (if include_hierarchy was true).
     * Each entry is a container identifier, from outermost to innermost.
     * ```
     *
     * `repeated string path = 2 [json_name = "path"];`
     * @param value The path to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addPath")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, PathProxy>.add(value: kotlin.String) {
      _builder.addPath(value)
    }
    /**
     * ```
     * Full path from root to this item (if include_hierarchy was true).
     * Each entry is a container identifier, from outermost to innermost.
     * ```
     *
     * `repeated string path = 2 [json_name = "path"];`
     * @param value The path to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignPath")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, PathProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * ```
     * Full path from root to this item (if include_hierarchy was true).
     * Each entry is a container identifier, from outermost to innermost.
     * ```
     *
     * `repeated string path = 2 [json_name = "path"];`
     * @param values The path to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllPath")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, PathProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllPath(values)
    }
    /**
     * ```
     * Full path from root to this item (if include_hierarchy was true).
     * Each entry is a container identifier, from outermost to innermost.
     * ```
     *
     * `repeated string path = 2 [json_name = "path"];`
     * @param values The path to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllPath")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, PathProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * ```
     * Full path from root to this item (if include_hierarchy was true).
     * Each entry is a container identifier, from outermost to innermost.
     * ```
     *
     * `repeated string path = 2 [json_name = "path"];`
     * @param index The index to set the value at.
     * @param value The path to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setPath")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, PathProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setPath(index, value)
    }
    /**
     * ```
     * Full path from root to this item (if include_hierarchy was true).
     * Each entry is a container identifier, from outermost to innermost.
     * ```
     *
     * `repeated string path = 2 [json_name = "path"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearPath")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, PathProxy>.clear() {
      _builder.clearPath()
    }}
}
@kotlin.jvm.JvmSynthetic
public inline fun api.v1.Inventory.ContainerPath.copy(block: `api.v1`.ContainerPathKt.Dsl.() -> kotlin.Unit): api.v1.Inventory.ContainerPath =
  `api.v1`.ContainerPathKt.Dsl._create(this.toBuilder()).apply { block() }._build()

