// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/search.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package api.v1;

@kotlin.jvm.JvmName("-initializecontainerPathElement")
public inline fun containerPathElement(block: api.v1.ContainerPathElementKt.Dsl.() -> kotlin.Unit): api.v1.Search.ContainerPathElement =
  api.v1.ContainerPathElementKt.Dsl._create(api.v1.Search.ContainerPathElement.newBuilder()).apply { block() }._build()
/**
 * ```
 * A single element in a container path.
 * ```
 *
 * Protobuf type `api.v1.ContainerPathElement`
 */
public object ContainerPathElementKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: api.v1.Search.ContainerPathElement.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: api.v1.Search.ContainerPathElement.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): api.v1.Search.ContainerPathElement = _builder.build()

    /**
     * ```
     * Container identifier
     * ```
     *
     * `string identifier = 1 [json_name = "identifier"];`
     */
    public var identifier: kotlin.String
      @JvmName("getIdentifier")
      get() = _builder.identifier
      @JvmName("setIdentifier")
      set(value) {
        _builder.identifier = value
      }
    /**
     * ```
     * Container identifier
     * ```
     *
     * `string identifier = 1 [json_name = "identifier"];`
     */
    public fun clearIdentifier() {
      _builder.clearIdentifier()
    }

    /**
     * ```
     * Container title (if available, otherwise will be empty)
     * ```
     *
     * `string title = 2 [json_name = "title"];`
     */
    public var title: kotlin.String
      @JvmName("getTitle")
      get() = _builder.title
      @JvmName("setTitle")
      set(value) {
        _builder.title = value
      }
    /**
     * ```
     * Container title (if available, otherwise will be empty)
     * ```
     *
     * `string title = 2 [json_name = "title"];`
     */
    public fun clearTitle() {
      _builder.clearTitle()
    }

    /**
     * ```
     * Depth level in hierarchy (0 = root, higher = deeper)
     * ```
     *
     * `int32 depth = 3 [json_name = "depth"];`
     */
    public var depth: kotlin.Int
      @JvmName("getDepth")
      get() = _builder.depth
      @JvmName("setDepth")
      set(value) {
        _builder.depth = value
      }
    /**
     * ```
     * Depth level in hierarchy (0 = root, higher = deeper)
     * ```
     *
     * `int32 depth = 3 [json_name = "depth"];`
     */
    public fun clearDepth() {
      _builder.clearDepth()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun api.v1.Search.ContainerPathElement.copy(block: `api.v1`.ContainerPathElementKt.Dsl.() -> kotlin.Unit): api.v1.Search.ContainerPathElement =
  `api.v1`.ContainerPathElementKt.Dsl._create(this.toBuilder()).apply { block() }._build()

