// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/inventory.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package api.v1;

@kotlin.jvm.JvmName("-initializecreateInventoryItemRequest")
public inline fun createInventoryItemRequest(block: api.v1.CreateInventoryItemRequestKt.Dsl.() -> kotlin.Unit): api.v1.Inventory.CreateInventoryItemRequest =
  api.v1.CreateInventoryItemRequestKt.Dsl._create(api.v1.Inventory.CreateInventoryItemRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `api.v1.CreateInventoryItemRequest`
 */
public object CreateInventoryItemRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: api.v1.Inventory.CreateInventoryItemRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: api.v1.Inventory.CreateInventoryItemRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): api.v1.Inventory.CreateInventoryItemRequest = _builder.build()

    /**
     * ```
     * The identifier for the new item (will be munged to wiki identifier format).
     * ```
     *
     * `string item_identifier = 1 [json_name = "itemIdentifier"];`
     */
    public var itemIdentifier: kotlin.String
      @JvmName("getItemIdentifier")
      get() = _builder.itemIdentifier
      @JvmName("setItemIdentifier")
      set(value) {
        _builder.itemIdentifier = value
      }
    /**
     * ```
     * The identifier for the new item (will be munged to wiki identifier format).
     * ```
     *
     * `string item_identifier = 1 [json_name = "itemIdentifier"];`
     */
    public fun clearItemIdentifier() {
      _builder.clearItemIdentifier()
    }

    /**
     * ```
     * Optional: The container this item belongs to.
     * ```
     *
     * `string container = 2 [json_name = "container"];`
     */
    public var container: kotlin.String
      @JvmName("getContainer")
      get() = _builder.container
      @JvmName("setContainer")
      set(value) {
        _builder.container = value
      }
    /**
     * ```
     * Optional: The container this item belongs to.
     * ```
     *
     * `string container = 2 [json_name = "container"];`
     */
    public fun clearContainer() {
      _builder.clearContainer()
    }

    /**
     * ```
     * Optional: Human-readable title for the item.
     * If not provided, will be auto-generated from the identifier.
     * ```
     *
     * `string title = 3 [json_name = "title"];`
     */
    public var title: kotlin.String
      @JvmName("getTitle")
      get() = _builder.title
      @JvmName("setTitle")
      set(value) {
        _builder.title = value
      }
    /**
     * ```
     * Optional: Human-readable title for the item.
     * If not provided, will be auto-generated from the identifier.
     * ```
     *
     * `string title = 3 [json_name = "title"];`
     */
    public fun clearTitle() {
      _builder.clearTitle()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun api.v1.Inventory.CreateInventoryItemRequest.copy(block: `api.v1`.CreateInventoryItemRequestKt.Dsl.() -> kotlin.Unit): api.v1.Inventory.CreateInventoryItemRequest =
  `api.v1`.CreateInventoryItemRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

