// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/inventory.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package api.v1;

@kotlin.jvm.JvmName("-initializecreateInventoryItemResponse")
public inline fun createInventoryItemResponse(block: api.v1.CreateInventoryItemResponseKt.Dsl.() -> kotlin.Unit): api.v1.Inventory.CreateInventoryItemResponse =
  api.v1.CreateInventoryItemResponseKt.Dsl._create(api.v1.Inventory.CreateInventoryItemResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `api.v1.CreateInventoryItemResponse`
 */
public object CreateInventoryItemResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: api.v1.Inventory.CreateInventoryItemResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: api.v1.Inventory.CreateInventoryItemResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): api.v1.Inventory.CreateInventoryItemResponse = _builder.build()

    /**
     * ```
     * Whether the operation was successful.
     * ```
     *
     * `bool success = 1 [json_name = "success"];`
     */
    public var success: kotlin.Boolean
      @JvmName("getSuccess")
      get() = _builder.success
      @JvmName("setSuccess")
      set(value) {
        _builder.success = value
      }
    /**
     * ```
     * Whether the operation was successful.
     * ```
     *
     * `bool success = 1 [json_name = "success"];`
     */
    public fun clearSuccess() {
      _builder.clearSuccess()
    }

    /**
     * ```
     * The final identifier of the created item (after munging).
     * ```
     *
     * `string item_identifier = 2 [json_name = "itemIdentifier"];`
     */
    public var itemIdentifier: kotlin.String
      @JvmName("getItemIdentifier")
      get() = _builder.itemIdentifier
      @JvmName("setItemIdentifier")
      set(value) {
        _builder.itemIdentifier = value
      }
    /**
     * ```
     * The final identifier of the created item (after munging).
     * ```
     *
     * `string item_identifier = 2 [json_name = "itemIdentifier"];`
     */
    public fun clearItemIdentifier() {
      _builder.clearItemIdentifier()
    }

    /**
     * ```
     * Human-readable summary of the action taken, suitable for LLM consumption.
     * ```
     *
     * `string summary = 3 [json_name = "summary"];`
     */
    public var summary: kotlin.String
      @JvmName("getSummary")
      get() = _builder.summary
      @JvmName("setSummary")
      set(value) {
        _builder.summary = value
      }
    /**
     * ```
     * Human-readable summary of the action taken, suitable for LLM consumption.
     * ```
     *
     * `string summary = 3 [json_name = "summary"];`
     */
    public fun clearSummary() {
      _builder.clearSummary()
    }

    /**
     * ```
     * Error message if the operation failed.
     * ```
     *
     * `string error = 4 [json_name = "error"];`
     */
    public var error: kotlin.String
      @JvmName("getError")
      get() = _builder.error
      @JvmName("setError")
      set(value) {
        _builder.error = value
      }
    /**
     * ```
     * Error message if the operation failed.
     * ```
     *
     * `string error = 4 [json_name = "error"];`
     */
    public fun clearError() {
      _builder.clearError()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun api.v1.Inventory.CreateInventoryItemResponse.copy(block: `api.v1`.CreateInventoryItemResponseKt.Dsl.() -> kotlin.Unit): api.v1.Inventory.CreateInventoryItemResponse =
  `api.v1`.CreateInventoryItemResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

