// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/page_management.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package api.v1;

@kotlin.jvm.JvmName("-initializeexistingPageInfo")
public inline fun existingPageInfo(block: api.v1.ExistingPageInfoKt.Dsl.() -> kotlin.Unit): api.v1.PageManagement.ExistingPageInfo =
  api.v1.ExistingPageInfoKt.Dsl._create(api.v1.PageManagement.ExistingPageInfo.newBuilder()).apply { block() }._build()
/**
 * ```
 * Info about an existing page (used when identifier already exists).
 * ```
 *
 * Protobuf type `api.v1.ExistingPageInfo`
 */
public object ExistingPageInfoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: api.v1.PageManagement.ExistingPageInfo.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: api.v1.PageManagement.ExistingPageInfo.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): api.v1.PageManagement.ExistingPageInfo = _builder.build()

    /**
     * ```
     * The page identifier.
     * ```
     *
     * `string identifier = 1 [json_name = "identifier"];`
     */
    public var identifier: kotlin.String
      @JvmName("getIdentifier")
      get() = _builder.identifier
      @JvmName("setIdentifier")
      set(value) {
        _builder.identifier = value
      }
    /**
     * ```
     * The page identifier.
     * ```
     *
     * `string identifier = 1 [json_name = "identifier"];`
     */
    public fun clearIdentifier() {
      _builder.clearIdentifier()
    }

    /**
     * ```
     * The page title from frontmatter.
     * ```
     *
     * `string title = 2 [json_name = "title"];`
     */
    public var title: kotlin.String
      @JvmName("getTitle")
      get() = _builder.title
      @JvmName("setTitle")
      set(value) {
        _builder.title = value
      }
    /**
     * ```
     * The page title from frontmatter.
     * ```
     *
     * `string title = 2 [json_name = "title"];`
     */
    public fun clearTitle() {
      _builder.clearTitle()
    }

    /**
     * ```
     * The inventory.container value if this is an inventory item.
     * ```
     *
     * `string container = 3 [json_name = "container"];`
     */
    public var container: kotlin.String
      @JvmName("getContainer")
      get() = _builder.container
      @JvmName("setContainer")
      set(value) {
        _builder.container = value
      }
    /**
     * ```
     * The inventory.container value if this is an inventory item.
     * ```
     *
     * `string container = 3 [json_name = "container"];`
     */
    public fun clearContainer() {
      _builder.clearContainer()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun api.v1.PageManagement.ExistingPageInfo.copy(block: `api.v1`.ExistingPageInfoKt.Dsl.() -> kotlin.Unit): api.v1.PageManagement.ExistingPageInfo =
  `api.v1`.ExistingPageInfoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

