// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/inventory.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package api.v1;

@kotlin.jvm.JvmName("-initializefindItemLocationResponse")
public inline fun findItemLocationResponse(block: api.v1.FindItemLocationResponseKt.Dsl.() -> kotlin.Unit): api.v1.Inventory.FindItemLocationResponse =
  api.v1.FindItemLocationResponseKt.Dsl._create(api.v1.Inventory.FindItemLocationResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `api.v1.FindItemLocationResponse`
 */
public object FindItemLocationResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: api.v1.Inventory.FindItemLocationResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: api.v1.Inventory.FindItemLocationResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): api.v1.Inventory.FindItemLocationResponse = _builder.build()

    /**
     * ```
     * The item being queried.
     * ```
     *
     * `string item_identifier = 1 [json_name = "itemIdentifier"];`
     */
    public var itemIdentifier: kotlin.String
      @JvmName("getItemIdentifier")
      get() = _builder.itemIdentifier
      @JvmName("setItemIdentifier")
      set(value) {
        _builder.itemIdentifier = value
      }
    /**
     * ```
     * The item being queried.
     * ```
     *
     * `string item_identifier = 1 [json_name = "itemIdentifier"];`
     */
    public fun clearItemIdentifier() {
      _builder.clearItemIdentifier()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class LocationsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * The container(s) this item is in.
     * Usually just one, but could be multiple if there are anomalies.
     * ```
     *
     * `repeated .api.v1.ContainerPath locations = 2 [json_name = "locations"];`
     */
     public val locations: com.google.protobuf.kotlin.DslList<api.v1.Inventory.ContainerPath, LocationsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.locationsList
      )
    /**
     * ```
     * The container(s) this item is in.
     * Usually just one, but could be multiple if there are anomalies.
     * ```
     *
     * `repeated .api.v1.ContainerPath locations = 2 [json_name = "locations"];`
     * @param value The locations to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addLocations")
    public fun com.google.protobuf.kotlin.DslList<api.v1.Inventory.ContainerPath, LocationsProxy>.add(value: api.v1.Inventory.ContainerPath) {
      _builder.addLocations(value)
    }
    /**
     * ```
     * The container(s) this item is in.
     * Usually just one, but could be multiple if there are anomalies.
     * ```
     *
     * `repeated .api.v1.ContainerPath locations = 2 [json_name = "locations"];`
     * @param value The locations to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignLocations")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<api.v1.Inventory.ContainerPath, LocationsProxy>.plusAssign(value: api.v1.Inventory.ContainerPath) {
      add(value)
    }
    /**
     * ```
     * The container(s) this item is in.
     * Usually just one, but could be multiple if there are anomalies.
     * ```
     *
     * `repeated .api.v1.ContainerPath locations = 2 [json_name = "locations"];`
     * @param values The locations to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllLocations")
    public fun com.google.protobuf.kotlin.DslList<api.v1.Inventory.ContainerPath, LocationsProxy>.addAll(values: kotlin.collections.Iterable<api.v1.Inventory.ContainerPath>) {
      _builder.addAllLocations(values)
    }
    /**
     * ```
     * The container(s) this item is in.
     * Usually just one, but could be multiple if there are anomalies.
     * ```
     *
     * `repeated .api.v1.ContainerPath locations = 2 [json_name = "locations"];`
     * @param values The locations to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllLocations")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<api.v1.Inventory.ContainerPath, LocationsProxy>.plusAssign(values: kotlin.collections.Iterable<api.v1.Inventory.ContainerPath>) {
      addAll(values)
    }
    /**
     * ```
     * The container(s) this item is in.
     * Usually just one, but could be multiple if there are anomalies.
     * ```
     *
     * `repeated .api.v1.ContainerPath locations = 2 [json_name = "locations"];`
     * @param index The index to set the value at.
     * @param value The locations to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setLocations")
    public operator fun com.google.protobuf.kotlin.DslList<api.v1.Inventory.ContainerPath, LocationsProxy>.set(index: kotlin.Int, value: api.v1.Inventory.ContainerPath) {
      _builder.setLocations(index, value)
    }
    /**
     * ```
     * The container(s) this item is in.
     * Usually just one, but could be multiple if there are anomalies.
     * ```
     *
     * `repeated .api.v1.ContainerPath locations = 2 [json_name = "locations"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearLocations")
    public fun com.google.protobuf.kotlin.DslList<api.v1.Inventory.ContainerPath, LocationsProxy>.clear() {
      _builder.clearLocations()
    }


    /**
     * ```
     * Whether the item was found.
     * ```
     *
     * `bool found = 3 [json_name = "found"];`
     */
    public var found: kotlin.Boolean
      @JvmName("getFound")
      get() = _builder.found
      @JvmName("setFound")
      set(value) {
        _builder.found = value
      }
    /**
     * ```
     * Whether the item was found.
     * ```
     *
     * `bool found = 3 [json_name = "found"];`
     */
    public fun clearFound() {
      _builder.clearFound()
    }

    /**
     * ```
     * Human-readable summary suitable for LLM consumption.
     * ```
     *
     * `string summary = 4 [json_name = "summary"];`
     */
    public var summary: kotlin.String
      @JvmName("getSummary")
      get() = _builder.summary
      @JvmName("setSummary")
      set(value) {
        _builder.summary = value
      }
    /**
     * ```
     * Human-readable summary suitable for LLM consumption.
     * ```
     *
     * `string summary = 4 [json_name = "summary"];`
     */
    public fun clearSummary() {
      _builder.clearSummary()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun api.v1.Inventory.FindItemLocationResponse.copy(block: `api.v1`.FindItemLocationResponseKt.Dsl.() -> kotlin.Unit): api.v1.Inventory.FindItemLocationResponse =
  `api.v1`.FindItemLocationResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

