// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/inventory.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package api.v1;

@kotlin.jvm.JvmName("-initializefindItemLocationRequest")
public inline fun findItemLocationRequest(block: api.v1.FindItemLocationRequestKt.Dsl.() -> kotlin.Unit): api.v1.Inventory.FindItemLocationRequest =
  api.v1.FindItemLocationRequestKt.Dsl._create(api.v1.Inventory.FindItemLocationRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `api.v1.FindItemLocationRequest`
 */
public object FindItemLocationRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: api.v1.Inventory.FindItemLocationRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: api.v1.Inventory.FindItemLocationRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): api.v1.Inventory.FindItemLocationRequest = _builder.build()

    /**
     * ```
     * The identifier of the item to find.
     * ```
     *
     * `string item_identifier = 1 [json_name = "itemIdentifier"];`
     */
    public var itemIdentifier: kotlin.String
      @JvmName("getItemIdentifier")
      get() = _builder.itemIdentifier
      @JvmName("setItemIdentifier")
      set(value) {
        _builder.itemIdentifier = value
      }
    /**
     * ```
     * The identifier of the item to find.
     * ```
     *
     * `string item_identifier = 1 [json_name = "itemIdentifier"];`
     */
    public fun clearItemIdentifier() {
      _builder.clearItemIdentifier()
    }

    /**
     * ```
     * Whether to include the full container hierarchy path.
     * ```
     *
     * `bool include_hierarchy = 2 [json_name = "includeHierarchy"];`
     */
    public var includeHierarchy: kotlin.Boolean
      @JvmName("getIncludeHierarchy")
      get() = _builder.includeHierarchy
      @JvmName("setIncludeHierarchy")
      set(value) {
        _builder.includeHierarchy = value
      }
    /**
     * ```
     * Whether to include the full container hierarchy path.
     * ```
     *
     * `bool include_hierarchy = 2 [json_name = "includeHierarchy"];`
     */
    public fun clearIncludeHierarchy() {
      _builder.clearIncludeHierarchy()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun api.v1.Inventory.FindItemLocationRequest.copy(block: `api.v1`.FindItemLocationRequestKt.Dsl.() -> kotlin.Unit): api.v1.Inventory.FindItemLocationRequest =
  `api.v1`.FindItemLocationRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

