// Code generated by connect-kotlin. DO NOT EDIT.
//
// Source: api/v1/frontmatter.proto
//
package api.v1

import com.connectrpc.Headers
import com.connectrpc.ResponseMessage

/**
 *  The Frontmatter service definition.
 */
public interface FrontmatterClientInterface {
  /**
   *  Gets the frontmatter for a given page.
   */
  public suspend fun getFrontmatter(request: FrontmatterOuterClass.GetFrontmatterRequest, headers: Headers = emptyMap()): ResponseMessage<FrontmatterOuterClass.GetFrontmatterResponse>

  /**
   *  Merges the given frontmatter with the existing frontmatter for a page.
   */
  public suspend fun mergeFrontmatter(request: FrontmatterOuterClass.MergeFrontmatterRequest, headers: Headers = emptyMap()): ResponseMessage<FrontmatterOuterClass.MergeFrontmatterResponse>

  /**
   *  Replaces the entire frontmatter for a given page.
   */
  public suspend fun replaceFrontmatter(request: FrontmatterOuterClass.ReplaceFrontmatterRequest, headers: Headers = emptyMap()): ResponseMessage<FrontmatterOuterClass.ReplaceFrontmatterResponse>

  /**
   *  Removes a key from the frontmatter at a given path.
   */
  public suspend fun removeKeyAtPath(request: FrontmatterOuterClass.RemoveKeyAtPathRequest, headers: Headers = emptyMap()): ResponseMessage<FrontmatterOuterClass.RemoveKeyAtPathResponse>
}
