// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/page_management.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package api.v1;

@kotlin.jvm.JvmName("-initializegenerateIdentifierResponse")
public inline fun generateIdentifierResponse(block: api.v1.GenerateIdentifierResponseKt.Dsl.() -> kotlin.Unit): api.v1.PageManagement.GenerateIdentifierResponse =
  api.v1.GenerateIdentifierResponseKt.Dsl._create(api.v1.PageManagement.GenerateIdentifierResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `api.v1.GenerateIdentifierResponse`
 */
public object GenerateIdentifierResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: api.v1.PageManagement.GenerateIdentifierResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: api.v1.PageManagement.GenerateIdentifierResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): api.v1.PageManagement.GenerateIdentifierResponse = _builder.build()

    /**
     * ```
     * The generated identifier (munged to wiki format, possibly with suffix if ensure_unique).
     * ```
     *
     * `string identifier = 1 [json_name = "identifier"];`
     */
    public var identifier: kotlin.String
      @JvmName("getIdentifier")
      get() = _builder.identifier
      @JvmName("setIdentifier")
      set(value) {
        _builder.identifier = value
      }
    /**
     * ```
     * The generated identifier (munged to wiki format, possibly with suffix if ensure_unique).
     * ```
     *
     * `string identifier = 1 [json_name = "identifier"];`
     */
    public fun clearIdentifier() {
      _builder.clearIdentifier()
    }

    /**
     * ```
     * Whether this identifier is available (no existing page with this identifier).
     * ```
     *
     * `bool is_unique = 2 [json_name = "isUnique"];`
     */
    public var isUnique: kotlin.Boolean
      @JvmName("getIsUnique")
      get() = _builder.isUnique
      @JvmName("setIsUnique")
      set(value) {
        _builder.isUnique = value
      }
    /**
     * ```
     * Whether this identifier is available (no existing page with this identifier).
     * ```
     *
     * `bool is_unique = 2 [json_name = "isUnique"];`
     */
    public fun clearIsUnique() {
      _builder.clearIsUnique()
    }

    /**
     * ```
     * Info about the existing page if is_unique is false.
     * ```
     *
     * `.api.v1.ExistingPageInfo existing_page = 3 [json_name = "existingPage"];`
     */
    public var existingPage: api.v1.PageManagement.ExistingPageInfo
      @JvmName("getExistingPage")
      get() = _builder.existingPage
      @JvmName("setExistingPage")
      set(value) {
        _builder.existingPage = value
      }
    /**
     * ```
     * Info about the existing page if is_unique is false.
     * ```
     *
     * `.api.v1.ExistingPageInfo existing_page = 3 [json_name = "existingPage"];`
     */
    public fun clearExistingPage() {
      _builder.clearExistingPage()
    }
    /**
     * ```
     * Info about the existing page if is_unique is false.
     * ```
     *
     * `.api.v1.ExistingPageInfo existing_page = 3 [json_name = "existingPage"];`
     * @return Whether the existingPage field is set.
     */
    public fun hasExistingPage(): kotlin.Boolean {
      return _builder.hasExistingPage()
    }
    public val GenerateIdentifierResponseKt.Dsl.existingPageOrNull: api.v1.PageManagement.ExistingPageInfo?
      get() = _builder.existingPageOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun api.v1.PageManagement.GenerateIdentifierResponse.copy(block: `api.v1`.GenerateIdentifierResponseKt.Dsl.() -> kotlin.Unit): api.v1.PageManagement.GenerateIdentifierResponse =
  `api.v1`.GenerateIdentifierResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val api.v1.PageManagement.GenerateIdentifierResponseOrBuilder.existingPageOrNull: api.v1.PageManagement.ExistingPageInfo?
  get() = if (hasExistingPage()) getExistingPage() else null

