// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/page_management.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package api.v1;

@kotlin.jvm.JvmName("-initializegenerateIdentifierRequest")
public inline fun generateIdentifierRequest(block: api.v1.GenerateIdentifierRequestKt.Dsl.() -> kotlin.Unit): api.v1.PageManagement.GenerateIdentifierRequest =
  api.v1.GenerateIdentifierRequestKt.Dsl._create(api.v1.PageManagement.GenerateIdentifierRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * Generate Identifier
 * ```
 *
 * Protobuf type `api.v1.GenerateIdentifierRequest`
 */
public object GenerateIdentifierRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: api.v1.PageManagement.GenerateIdentifierRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: api.v1.PageManagement.GenerateIdentifierRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): api.v1.PageManagement.GenerateIdentifierRequest = _builder.build()

    /**
     * ```
     * The text to convert to an identifier (typically a title).
     * ```
     *
     * `string text = 1 [json_name = "text"];`
     */
    public var text: kotlin.String
      @JvmName("getText")
      get() = _builder.text
      @JvmName("setText")
      set(value) {
        _builder.text = value
      }
    /**
     * ```
     * The text to convert to an identifier (typically a title).
     * ```
     *
     * `string text = 1 [json_name = "text"];`
     */
    public fun clearText() {
      _builder.clearText()
    }

    /**
     * ```
     * If true, add suffix (e.g., _1, _2) to ensure no existing page has this identifier.
     * ```
     *
     * `bool ensure_unique = 2 [json_name = "ensureUnique"];`
     */
    public var ensureUnique: kotlin.Boolean
      @JvmName("getEnsureUnique")
      get() = _builder.ensureUnique
      @JvmName("setEnsureUnique")
      set(value) {
        _builder.ensureUnique = value
      }
    /**
     * ```
     * If true, add suffix (e.g., _1, _2) to ensure no existing page has this identifier.
     * ```
     *
     * `bool ensure_unique = 2 [json_name = "ensureUnique"];`
     */
    public fun clearEnsureUnique() {
      _builder.clearEnsureUnique()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun api.v1.PageManagement.GenerateIdentifierRequest.copy(block: `api.v1`.GenerateIdentifierRequestKt.Dsl.() -> kotlin.Unit): api.v1.PageManagement.GenerateIdentifierRequest =
  `api.v1`.GenerateIdentifierRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

