// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/frontmatter.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package api.v1;

@kotlin.jvm.JvmName("-initializegetFrontmatterRequest")
public inline fun getFrontmatterRequest(block: api.v1.GetFrontmatterRequestKt.Dsl.() -> kotlin.Unit): api.v1.FrontmatterOuterClass.GetFrontmatterRequest =
  api.v1.GetFrontmatterRequestKt.Dsl._create(api.v1.FrontmatterOuterClass.GetFrontmatterRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * The request message containing the page name.
 * ```
 *
 * Protobuf type `api.v1.GetFrontmatterRequest`
 */
public object GetFrontmatterRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: api.v1.FrontmatterOuterClass.GetFrontmatterRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: api.v1.FrontmatterOuterClass.GetFrontmatterRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): api.v1.FrontmatterOuterClass.GetFrontmatterRequest = _builder.build()

    /**
     * `string page = 1 [json_name = "page"];`
     */
    public var page: kotlin.String
      @JvmName("getPage")
      get() = _builder.page
      @JvmName("setPage")
      set(value) {
        _builder.page = value
      }
    /**
     * `string page = 1 [json_name = "page"];`
     */
    public fun clearPage() {
      _builder.clearPage()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun api.v1.FrontmatterOuterClass.GetFrontmatterRequest.copy(block: `api.v1`.GetFrontmatterRequestKt.Dsl.() -> kotlin.Unit): api.v1.FrontmatterOuterClass.GetFrontmatterRequest =
  `api.v1`.GetFrontmatterRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

