// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/system_info.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package api.v1;

@kotlin.jvm.JvmName("-initializegetJobStatusRequest")
public inline fun getJobStatusRequest(block: api.v1.GetJobStatusRequestKt.Dsl.() -> kotlin.Unit): api.v1.SystemInfo.GetJobStatusRequest =
  api.v1.GetJobStatusRequestKt.Dsl._create(api.v1.SystemInfo.GetJobStatusRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * The request message for the GetJobStatus RPC.
 * ```
 *
 * Protobuf type `api.v1.GetJobStatusRequest`
 */
public object GetJobStatusRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: api.v1.SystemInfo.GetJobStatusRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: api.v1.SystemInfo.GetJobStatusRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): api.v1.SystemInfo.GetJobStatusRequest = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun api.v1.SystemInfo.GetJobStatusRequest.copy(block: `api.v1`.GetJobStatusRequestKt.Dsl.() -> kotlin.Unit): api.v1.SystemInfo.GetJobStatusRequest =
  `api.v1`.GetJobStatusRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

