// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/system_info.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package api.v1;

@kotlin.jvm.JvmName("-initializegetJobStatusResponse")
public inline fun getJobStatusResponse(block: api.v1.GetJobStatusResponseKt.Dsl.() -> kotlin.Unit): api.v1.SystemInfo.GetJobStatusResponse =
  api.v1.GetJobStatusResponseKt.Dsl._create(api.v1.SystemInfo.GetJobStatusResponse.newBuilder()).apply { block() }._build()
/**
 * ```
 * The response message for the GetJobStatus RPC.
 * ```
 *
 * Protobuf type `api.v1.GetJobStatusResponse`
 */
public object GetJobStatusResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: api.v1.SystemInfo.GetJobStatusResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: api.v1.SystemInfo.GetJobStatusResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): api.v1.SystemInfo.GetJobStatusResponse = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class JobQueuesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .api.v1.JobQueueStatus job_queues = 1 [json_name = "jobQueues"];`
     */
     public val jobQueues: com.google.protobuf.kotlin.DslList<api.v1.SystemInfo.JobQueueStatus, JobQueuesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.jobQueuesList
      )
    /**
     * `repeated .api.v1.JobQueueStatus job_queues = 1 [json_name = "jobQueues"];`
     * @param value The jobQueues to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addJobQueues")
    public fun com.google.protobuf.kotlin.DslList<api.v1.SystemInfo.JobQueueStatus, JobQueuesProxy>.add(value: api.v1.SystemInfo.JobQueueStatus) {
      _builder.addJobQueues(value)
    }
    /**
     * `repeated .api.v1.JobQueueStatus job_queues = 1 [json_name = "jobQueues"];`
     * @param value The jobQueues to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignJobQueues")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<api.v1.SystemInfo.JobQueueStatus, JobQueuesProxy>.plusAssign(value: api.v1.SystemInfo.JobQueueStatus) {
      add(value)
    }
    /**
     * `repeated .api.v1.JobQueueStatus job_queues = 1 [json_name = "jobQueues"];`
     * @param values The jobQueues to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllJobQueues")
    public fun com.google.protobuf.kotlin.DslList<api.v1.SystemInfo.JobQueueStatus, JobQueuesProxy>.addAll(values: kotlin.collections.Iterable<api.v1.SystemInfo.JobQueueStatus>) {
      _builder.addAllJobQueues(values)
    }
    /**
     * `repeated .api.v1.JobQueueStatus job_queues = 1 [json_name = "jobQueues"];`
     * @param values The jobQueues to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllJobQueues")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<api.v1.SystemInfo.JobQueueStatus, JobQueuesProxy>.plusAssign(values: kotlin.collections.Iterable<api.v1.SystemInfo.JobQueueStatus>) {
      addAll(values)
    }
    /**
     * `repeated .api.v1.JobQueueStatus job_queues = 1 [json_name = "jobQueues"];`
     * @param index The index to set the value at.
     * @param value The jobQueues to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setJobQueues")
    public operator fun com.google.protobuf.kotlin.DslList<api.v1.SystemInfo.JobQueueStatus, JobQueuesProxy>.set(index: kotlin.Int, value: api.v1.SystemInfo.JobQueueStatus) {
      _builder.setJobQueues(index, value)
    }
    /**
     * `repeated .api.v1.JobQueueStatus job_queues = 1 [json_name = "jobQueues"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearJobQueues")
    public fun com.google.protobuf.kotlin.DslList<api.v1.SystemInfo.JobQueueStatus, JobQueuesProxy>.clear() {
      _builder.clearJobQueues()
    }

  }
}
@kotlin.jvm.JvmSynthetic
public inline fun api.v1.SystemInfo.GetJobStatusResponse.copy(block: `api.v1`.GetJobStatusResponseKt.Dsl.() -> kotlin.Unit): api.v1.SystemInfo.GetJobStatusResponse =
  `api.v1`.GetJobStatusResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

