// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/system_info.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package api.v1;

@kotlin.jvm.JvmName("-initializegetVersionRequest")
public inline fun getVersionRequest(block: api.v1.GetVersionRequestKt.Dsl.() -> kotlin.Unit): api.v1.SystemInfo.GetVersionRequest =
  api.v1.GetVersionRequestKt.Dsl._create(api.v1.SystemInfo.GetVersionRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * The request message for the GetVersion RPC.
 * ```
 *
 * Protobuf type `api.v1.GetVersionRequest`
 */
public object GetVersionRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: api.v1.SystemInfo.GetVersionRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: api.v1.SystemInfo.GetVersionRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): api.v1.SystemInfo.GetVersionRequest = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun api.v1.SystemInfo.GetVersionRequest.copy(block: `api.v1`.GetVersionRequestKt.Dsl.() -> kotlin.Unit): api.v1.SystemInfo.GetVersionRequest =
  `api.v1`.GetVersionRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

