// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/system_info.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package api.v1;

@kotlin.jvm.JvmName("-initializegetVersionResponse")
public inline fun getVersionResponse(block: api.v1.GetVersionResponseKt.Dsl.() -> kotlin.Unit): api.v1.SystemInfo.GetVersionResponse =
  api.v1.GetVersionResponseKt.Dsl._create(api.v1.SystemInfo.GetVersionResponse.newBuilder()).apply { block() }._build()
/**
 * ```
 * The response message for the GetVersion RPC.
 * ```
 *
 * Protobuf type `api.v1.GetVersionResponse`
 */
public object GetVersionResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: api.v1.SystemInfo.GetVersionResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: api.v1.SystemInfo.GetVersionResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): api.v1.SystemInfo.GetVersionResponse = _builder.build()

    /**
     * `string commit = 1 [json_name = "commit"];`
     */
    public var commit: kotlin.String
      @JvmName("getCommit")
      get() = _builder.commit
      @JvmName("setCommit")
      set(value) {
        _builder.commit = value
      }
    /**
     * `string commit = 1 [json_name = "commit"];`
     */
    public fun clearCommit() {
      _builder.clearCommit()
    }

    /**
     * `.google.protobuf.Timestamp build_time = 2 [json_name = "buildTime"];`
     */
    public var buildTime: com.google.protobuf.Timestamp
      @JvmName("getBuildTime")
      get() = _builder.buildTime
      @JvmName("setBuildTime")
      set(value) {
        _builder.buildTime = value
      }
    /**
     * `.google.protobuf.Timestamp build_time = 2 [json_name = "buildTime"];`
     */
    public fun clearBuildTime() {
      _builder.clearBuildTime()
    }
    /**
     * `.google.protobuf.Timestamp build_time = 2 [json_name = "buildTime"];`
     * @return Whether the buildTime field is set.
     */
    public fun hasBuildTime(): kotlin.Boolean {
      return _builder.hasBuildTime()
    }
    public val GetVersionResponseKt.Dsl.buildTimeOrNull: com.google.protobuf.Timestamp?
      get() = _builder.buildTimeOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun api.v1.SystemInfo.GetVersionResponse.copy(block: `api.v1`.GetVersionResponseKt.Dsl.() -> kotlin.Unit): api.v1.SystemInfo.GetVersionResponse =
  `api.v1`.GetVersionResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val api.v1.SystemInfo.GetVersionResponseOrBuilder.buildTimeOrNull: com.google.protobuf.Timestamp?
  get() = if (hasBuildTime()) getBuildTime() else null

