// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/search.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package api.v1;

@kotlin.jvm.JvmName("-initializehighlightSpan")
public inline fun highlightSpan(block: api.v1.HighlightSpanKt.Dsl.() -> kotlin.Unit): api.v1.Search.HighlightSpan =
  api.v1.HighlightSpanKt.Dsl._create(api.v1.Search.HighlightSpan.newBuilder()).apply { block() }._build()
/**
 * ```
 * A span of text to be highlighted.
 * ```
 *
 * Protobuf type `api.v1.HighlightSpan`
 */
public object HighlightSpanKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: api.v1.Search.HighlightSpan.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: api.v1.Search.HighlightSpan.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): api.v1.Search.HighlightSpan = _builder.build()

    /**
     * ```
     * Start position in fragment
     * ```
     *
     * `int32 start = 1 [json_name = "start"];`
     */
    public var start: kotlin.Int
      @JvmName("getStart")
      get() = _builder.start
      @JvmName("setStart")
      set(value) {
        _builder.start = value
      }
    /**
     * ```
     * Start position in fragment
     * ```
     *
     * `int32 start = 1 [json_name = "start"];`
     */
    public fun clearStart() {
      _builder.clearStart()
    }

    /**
     * ```
     * End position in fragment
     * ```
     *
     * `int32 end = 2 [json_name = "end"];`
     */
    public var end: kotlin.Int
      @JvmName("getEnd")
      get() = _builder.end
      @JvmName("setEnd")
      set(value) {
        _builder.end = value
      }
    /**
     * ```
     * End position in fragment
     * ```
     *
     * `int32 end = 2 [json_name = "end"];`
     */
    public fun clearEnd() {
      _builder.clearEnd()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun api.v1.Search.HighlightSpan.copy(block: `api.v1`.HighlightSpanKt.Dsl.() -> kotlin.Unit): api.v1.Search.HighlightSpan =
  `api.v1`.HighlightSpanKt.Dsl._create(this.toBuilder()).apply { block() }._build()

