// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/search.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package api.v1;

@kotlin.jvm.JvmName("-initializeinventoryContext")
public inline fun inventoryContext(block: api.v1.InventoryContextKt.Dsl.() -> kotlin.Unit): api.v1.Search.InventoryContext =
  api.v1.InventoryContextKt.Dsl._create(api.v1.Search.InventoryContext.newBuilder()).apply { block() }._build()
/**
 * ```
 * Inventory context for search results.
 * ```
 *
 * Protobuf type `api.v1.InventoryContext`
 */
public object InventoryContextKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: api.v1.Search.InventoryContext.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: api.v1.Search.InventoryContext.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): api.v1.Search.InventoryContext = _builder.build()

    /**
     * ```
     * Whether this result is inventory-related
     * ```
     *
     * `bool is_inventory_related = 1 [json_name = "isInventoryRelated"];`
     */
    public var isInventoryRelated: kotlin.Boolean
      @JvmName("getIsInventoryRelated")
      get() = _builder.isInventoryRelated
      @JvmName("setIsInventoryRelated")
      set(value) {
        _builder.isInventoryRelated = value
      }
    /**
     * ```
     * Whether this result is inventory-related
     * ```
     *
     * `bool is_inventory_related = 1 [json_name = "isInventoryRelated"];`
     */
    public fun clearIsInventoryRelated() {
      _builder.clearIsInventoryRelated()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class PathProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * Full path from root to immediate container
     * ```
     *
     * `repeated .api.v1.ContainerPathElement path = 2 [json_name = "path"];`
     */
     public val path: com.google.protobuf.kotlin.DslList<api.v1.Search.ContainerPathElement, PathProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.pathList
      )
    /**
     * ```
     * Full path from root to immediate container
     * ```
     *
     * `repeated .api.v1.ContainerPathElement path = 2 [json_name = "path"];`
     * @param value The path to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addPath")
    public fun com.google.protobuf.kotlin.DslList<api.v1.Search.ContainerPathElement, PathProxy>.add(value: api.v1.Search.ContainerPathElement) {
      _builder.addPath(value)
    }
    /**
     * ```
     * Full path from root to immediate container
     * ```
     *
     * `repeated .api.v1.ContainerPathElement path = 2 [json_name = "path"];`
     * @param value The path to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignPath")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<api.v1.Search.ContainerPathElement, PathProxy>.plusAssign(value: api.v1.Search.ContainerPathElement) {
      add(value)
    }
    /**
     * ```
     * Full path from root to immediate container
     * ```
     *
     * `repeated .api.v1.ContainerPathElement path = 2 [json_name = "path"];`
     * @param values The path to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllPath")
    public fun com.google.protobuf.kotlin.DslList<api.v1.Search.ContainerPathElement, PathProxy>.addAll(values: kotlin.collections.Iterable<api.v1.Search.ContainerPathElement>) {
      _builder.addAllPath(values)
    }
    /**
     * ```
     * Full path from root to immediate container
     * ```
     *
     * `repeated .api.v1.ContainerPathElement path = 2 [json_name = "path"];`
     * @param values The path to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllPath")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<api.v1.Search.ContainerPathElement, PathProxy>.plusAssign(values: kotlin.collections.Iterable<api.v1.Search.ContainerPathElement>) {
      addAll(values)
    }
    /**
     * ```
     * Full path from root to immediate container
     * ```
     *
     * `repeated .api.v1.ContainerPathElement path = 2 [json_name = "path"];`
     * @param index The index to set the value at.
     * @param value The path to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setPath")
    public operator fun com.google.protobuf.kotlin.DslList<api.v1.Search.ContainerPathElement, PathProxy>.set(index: kotlin.Int, value: api.v1.Search.ContainerPathElement) {
      _builder.setPath(index, value)
    }
    /**
     * ```
     * Full path from root to immediate container
     * ```
     *
     * `repeated .api.v1.ContainerPathElement path = 2 [json_name = "path"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearPath")
    public fun com.google.protobuf.kotlin.DslList<api.v1.Search.ContainerPathElement, PathProxy>.clear() {
      _builder.clearPath()
    }

  }
}
@kotlin.jvm.JvmSynthetic
public inline fun api.v1.Search.InventoryContext.copy(block: `api.v1`.InventoryContextKt.Dsl.() -> kotlin.Unit): api.v1.Search.InventoryContext =
  `api.v1`.InventoryContextKt.Dsl._create(this.toBuilder()).apply { block() }._build()

