// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/search.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package api.v1;

@kotlin.jvm.JvmName("-initializeinventoryContext")
public inline fun inventoryContext(block: api.v1.InventoryContextKt.Dsl.() -> kotlin.Unit): api.v1.Search.InventoryContext =
  api.v1.InventoryContextKt.Dsl._create(api.v1.Search.InventoryContext.newBuilder()).apply { block() }._build()
/**
 * ```
 * Inventory context for search results.
 * ```
 *
 * Protobuf type `api.v1.InventoryContext`
 */
public object InventoryContextKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: api.v1.Search.InventoryContext.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: api.v1.Search.InventoryContext.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): api.v1.Search.InventoryContext = _builder.build()

    /**
     * ```
     * Container identifier
     * ```
     *
     * `string container_id = 1 [json_name = "containerId"];`
     */
    public var containerId: kotlin.String
      @JvmName("getContainerId")
      get() = _builder.containerId
      @JvmName("setContainerId")
      set(value) {
        _builder.containerId = value
      }
    /**
     * ```
     * Container identifier
     * ```
     *
     * `string container_id = 1 [json_name = "containerId"];`
     */
    public fun clearContainerId() {
      _builder.clearContainerId()
    }

    /**
     * ```
     * Container title (if available)
     * ```
     *
     * `string container_title = 2 [json_name = "containerTitle"];`
     */
    public var containerTitle: kotlin.String
      @JvmName("getContainerTitle")
      get() = _builder.containerTitle
      @JvmName("setContainerTitle")
      set(value) {
        _builder.containerTitle = value
      }
    /**
     * ```
     * Container title (if available)
     * ```
     *
     * `string container_title = 2 [json_name = "containerTitle"];`
     */
    public fun clearContainerTitle() {
      _builder.clearContainerTitle()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun api.v1.Search.InventoryContext.copy(block: `api.v1`.InventoryContextKt.Dsl.() -> kotlin.Unit): api.v1.Search.InventoryContext =
  `api.v1`.InventoryContextKt.Dsl._create(this.toBuilder()).apply { block() }._build()

