// Code generated by connect-kotlin. DO NOT EDIT.
//
// Source: api/v1/inventory.proto
//
package api.v1

import com.connectrpc.Headers
import com.connectrpc.ResponseMessage

/**
 *  InventoryManagementService provides operations for managing inventory items.
 *  This service enables AI agents and other clients to manage household inventory
 *  through natural language commands like "put the batteries in the drawer".
 */
public interface InventoryManagementServiceClientInterface {
  /**
   *  Creates a new inventory item page with the inv_item template structure.
   */
  public suspend fun createInventoryItem(request: Inventory.CreateInventoryItemRequest, headers: Headers = emptyMap()): ResponseMessage<Inventory.CreateInventoryItemResponse>

  /**
   *  Moves an item from one container to another by updating both
   *  the item's inventory.container and the containers' inventory.items lists.
   */
  public suspend fun moveInventoryItem(request: Inventory.MoveInventoryItemRequest, headers: Headers = emptyMap()): ResponseMessage<Inventory.MoveInventoryItemResponse>

  /**
   *  Lists all items in a container, including items in nested containers.
   */
  public suspend fun listContainerContents(request: Inventory.ListContainerContentsRequest, headers: Headers = emptyMap()): ResponseMessage<Inventory.ListContainerContentsResponse>

  /**
   *  Finds which container(s) an item is in.
   */
  public suspend fun findItemLocation(request: Inventory.FindItemLocationRequest, headers: Headers = emptyMap()): ResponseMessage<Inventory.FindItemLocationResponse>
}
