// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/inventory.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package api.v1;

@kotlin.jvm.JvmName("-initializeinventoryItem")
public inline fun inventoryItem(block: api.v1.InventoryItemKt.Dsl.() -> kotlin.Unit): api.v1.Inventory.InventoryItem =
  api.v1.InventoryItemKt.Dsl._create(api.v1.Inventory.InventoryItem.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `api.v1.InventoryItem`
 */
public object InventoryItemKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: api.v1.Inventory.InventoryItem.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: api.v1.Inventory.InventoryItem.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): api.v1.Inventory.InventoryItem = _builder.build()

    /**
     * ```
     * The identifier of the item.
     * ```
     *
     * `string identifier = 1 [json_name = "identifier"];`
     */
    public var identifier: kotlin.String
      @JvmName("getIdentifier")
      get() = _builder.identifier
      @JvmName("setIdentifier")
      set(value) {
        _builder.identifier = value
      }
    /**
     * ```
     * The identifier of the item.
     * ```
     *
     * `string identifier = 1 [json_name = "identifier"];`
     */
    public fun clearIdentifier() {
      _builder.clearIdentifier()
    }

    /**
     * ```
     * The title of the item (if set in frontmatter).
     * ```
     *
     * `string title = 2 [json_name = "title"];`
     */
    public var title: kotlin.String
      @JvmName("getTitle")
      get() = _builder.title
      @JvmName("setTitle")
      set(value) {
        _builder.title = value
      }
    /**
     * ```
     * The title of the item (if set in frontmatter).
     * ```
     *
     * `string title = 2 [json_name = "title"];`
     */
    public fun clearTitle() {
      _builder.clearTitle()
    }

    /**
     * ```
     * Whether this item is itself a container (has items inside it).
     * ```
     *
     * `bool is_container = 3 [json_name = "isContainer"];`
     */
    public var isContainer: kotlin.Boolean
      @JvmName("getIsContainer")
      get() = _builder.isContainer
      @JvmName("setIsContainer")
      set(value) {
        _builder.isContainer = value
      }
    /**
     * ```
     * Whether this item is itself a container (has items inside it).
     * ```
     *
     * `bool is_container = 3 [json_name = "isContainer"];`
     */
    public fun clearIsContainer() {
      _builder.clearIsContainer()
    }

    /**
     * ```
     * The direct container this item is in.
     * ```
     *
     * `string container = 4 [json_name = "container"];`
     */
    public var container: kotlin.String
      @JvmName("getContainer")
      get() = _builder.container
      @JvmName("setContainer")
      set(value) {
        _builder.container = value
      }
    /**
     * ```
     * The direct container this item is in.
     * ```
     *
     * `string container = 4 [json_name = "container"];`
     */
    public fun clearContainer() {
      _builder.clearContainer()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class NestedItemsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * Nested items if this is a container and recursive listing was requested.
     * ```
     *
     * `repeated .api.v1.InventoryItem nested_items = 5 [json_name = "nestedItems"];`
     */
     public val nestedItems: com.google.protobuf.kotlin.DslList<api.v1.Inventory.InventoryItem, NestedItemsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.nestedItemsList
      )
    /**
     * ```
     * Nested items if this is a container and recursive listing was requested.
     * ```
     *
     * `repeated .api.v1.InventoryItem nested_items = 5 [json_name = "nestedItems"];`
     * @param value The nestedItems to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addNestedItems")
    public fun com.google.protobuf.kotlin.DslList<api.v1.Inventory.InventoryItem, NestedItemsProxy>.add(value: api.v1.Inventory.InventoryItem) {
      _builder.addNestedItems(value)
    }
    /**
     * ```
     * Nested items if this is a container and recursive listing was requested.
     * ```
     *
     * `repeated .api.v1.InventoryItem nested_items = 5 [json_name = "nestedItems"];`
     * @param value The nestedItems to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignNestedItems")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<api.v1.Inventory.InventoryItem, NestedItemsProxy>.plusAssign(value: api.v1.Inventory.InventoryItem) {
      add(value)
    }
    /**
     * ```
     * Nested items if this is a container and recursive listing was requested.
     * ```
     *
     * `repeated .api.v1.InventoryItem nested_items = 5 [json_name = "nestedItems"];`
     * @param values The nestedItems to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllNestedItems")
    public fun com.google.protobuf.kotlin.DslList<api.v1.Inventory.InventoryItem, NestedItemsProxy>.addAll(values: kotlin.collections.Iterable<api.v1.Inventory.InventoryItem>) {
      _builder.addAllNestedItems(values)
    }
    /**
     * ```
     * Nested items if this is a container and recursive listing was requested.
     * ```
     *
     * `repeated .api.v1.InventoryItem nested_items = 5 [json_name = "nestedItems"];`
     * @param values The nestedItems to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllNestedItems")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<api.v1.Inventory.InventoryItem, NestedItemsProxy>.plusAssign(values: kotlin.collections.Iterable<api.v1.Inventory.InventoryItem>) {
      addAll(values)
    }
    /**
     * ```
     * Nested items if this is a container and recursive listing was requested.
     * ```
     *
     * `repeated .api.v1.InventoryItem nested_items = 5 [json_name = "nestedItems"];`
     * @param index The index to set the value at.
     * @param value The nestedItems to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setNestedItems")
    public operator fun com.google.protobuf.kotlin.DslList<api.v1.Inventory.InventoryItem, NestedItemsProxy>.set(index: kotlin.Int, value: api.v1.Inventory.InventoryItem) {
      _builder.setNestedItems(index, value)
    }
    /**
     * ```
     * Nested items if this is a container and recursive listing was requested.
     * ```
     *
     * `repeated .api.v1.InventoryItem nested_items = 5 [json_name = "nestedItems"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearNestedItems")
    public fun com.google.protobuf.kotlin.DslList<api.v1.Inventory.InventoryItem, NestedItemsProxy>.clear() {
      _builder.clearNestedItems()
    }

  }
}
@kotlin.jvm.JvmSynthetic
public inline fun api.v1.Inventory.InventoryItem.copy(block: `api.v1`.InventoryItemKt.Dsl.() -> kotlin.Unit): api.v1.Inventory.InventoryItem =
  `api.v1`.InventoryItemKt.Dsl._create(this.toBuilder()).apply { block() }._build()

