// Code generated by connect-kotlin. DO NOT EDIT.
//
// Source: api/v1/inventory.proto
//
package api.v1

import com.connectrpc.Headers
import com.connectrpc.MethodSpec
import com.connectrpc.ProtocolClientInterface
import com.connectrpc.ResponseMessage
import com.connectrpc.StreamType

/**
 *  InventoryManagementService provides operations for managing inventory items.
 *  This service enables AI agents and other clients to manage household inventory
 *  through natural language commands like "put the batteries in the drawer".
 */
public class InventoryManagementServiceClient(
  private val client: ProtocolClientInterface,
) : InventoryManagementServiceClientInterface {
  /**
   *  Creates a new inventory item page with the inv_item template structure.
   */
  override suspend fun createInventoryItem(request: Inventory.CreateInventoryItemRequest, headers: Headers): ResponseMessage<Inventory.CreateInventoryItemResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "api.v1.InventoryManagementService/CreateInventoryItem",
      api.v1.Inventory.CreateInventoryItemRequest::class,
      api.v1.Inventory.CreateInventoryItemResponse::class,
      StreamType.UNARY,
    ),
  )


  /**
   *  Moves an item from one container to another by updating both
   *  the item's inventory.container and the containers' inventory.items lists.
   */
  override suspend fun moveInventoryItem(request: Inventory.MoveInventoryItemRequest, headers: Headers): ResponseMessage<Inventory.MoveInventoryItemResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "api.v1.InventoryManagementService/MoveInventoryItem",
      api.v1.Inventory.MoveInventoryItemRequest::class,
      api.v1.Inventory.MoveInventoryItemResponse::class,
      StreamType.UNARY,
    ),
  )


  /**
   *  Lists all items in a container, including items in nested containers.
   */
  override suspend fun listContainerContents(request: Inventory.ListContainerContentsRequest, headers: Headers): ResponseMessage<Inventory.ListContainerContentsResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "api.v1.InventoryManagementService/ListContainerContents",
      api.v1.Inventory.ListContainerContentsRequest::class,
      api.v1.Inventory.ListContainerContentsResponse::class,
      StreamType.UNARY,
    ),
  )


  /**
   *  Finds which container(s) an item is in.
   */
  override suspend fun findItemLocation(request: Inventory.FindItemLocationRequest, headers: Headers): ResponseMessage<Inventory.FindItemLocationResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "api.v1.InventoryManagementService/FindItemLocation",
      api.v1.Inventory.FindItemLocationRequest::class,
      api.v1.Inventory.FindItemLocationResponse::class,
      StreamType.UNARY,
    ),
  )

}
