// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/system_info.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package api.v1;

@kotlin.jvm.JvmName("-initializejobQueueStatus")
public inline fun jobQueueStatus(block: api.v1.JobQueueStatusKt.Dsl.() -> kotlin.Unit): api.v1.SystemInfo.JobQueueStatus =
  api.v1.JobQueueStatusKt.Dsl._create(api.v1.SystemInfo.JobQueueStatus.newBuilder()).apply { block() }._build()
/**
 * ```
 * Status information for a single job queue.
 * ```
 *
 * Protobuf type `api.v1.JobQueueStatus`
 */
public object JobQueueStatusKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: api.v1.SystemInfo.JobQueueStatus.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: api.v1.SystemInfo.JobQueueStatus.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): api.v1.SystemInfo.JobQueueStatus = _builder.build()

    /**
     * ```
     * "Frontmatter", "Bleve", "File Scan"
     * ```
     *
     * `string name = 1 [json_name = "name"];`
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.name
      @JvmName("setName")
      set(value) {
        _builder.name = value
      }
    /**
     * ```
     * "Frontmatter", "Bleve", "File Scan"
     * ```
     *
     * `string name = 1 [json_name = "name"];`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * ```
     * Current queue depth
     * ```
     *
     * `int32 jobs_remaining = 2 [json_name = "jobsRemaining"];`
     */
    public var jobsRemaining: kotlin.Int
      @JvmName("getJobsRemaining")
      get() = _builder.jobsRemaining
      @JvmName("setJobsRemaining")
      set(value) {
        _builder.jobsRemaining = value
      }
    /**
     * ```
     * Current queue depth
     * ```
     *
     * `int32 jobs_remaining = 2 [json_name = "jobsRemaining"];`
     */
    public fun clearJobsRemaining() {
      _builder.clearJobsRemaining()
    }

    /**
     * ```
     * Peak, resets to 0 when empty
     * ```
     *
     * `int32 high_water_mark = 3 [json_name = "highWaterMark"];`
     */
    public var highWaterMark: kotlin.Int
      @JvmName("getHighWaterMark")
      get() = _builder.highWaterMark
      @JvmName("setHighWaterMark")
      set(value) {
        _builder.highWaterMark = value
      }
    /**
     * ```
     * Peak, resets to 0 when empty
     * ```
     *
     * `int32 high_water_mark = 3 [json_name = "highWaterMark"];`
     */
    public fun clearHighWaterMark() {
      _builder.clearHighWaterMark()
    }

    /**
     * ```
     * jobs_remaining > 0
     * ```
     *
     * `bool is_active = 4 [json_name = "isActive"];`
     */
    public var isActive: kotlin.Boolean
      @JvmName("getIsActive")
      get() = _builder.isActive
      @JvmName("setIsActive")
      set(value) {
        _builder.isActive = value
      }
    /**
     * ```
     * jobs_remaining > 0
     * ```
     *
     * `bool is_active = 4 [json_name = "isActive"];`
     */
    public fun clearIsActive() {
      _builder.clearIsActive()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun api.v1.SystemInfo.JobQueueStatus.copy(block: `api.v1`.JobQueueStatusKt.Dsl.() -> kotlin.Unit): api.v1.SystemInfo.JobQueueStatus =
  `api.v1`.JobQueueStatusKt.Dsl._create(this.toBuilder()).apply { block() }._build()

