// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/inventory.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package api.v1;

@kotlin.jvm.JvmName("-initializelistContainerContentsResponse")
public inline fun listContainerContentsResponse(block: api.v1.ListContainerContentsResponseKt.Dsl.() -> kotlin.Unit): api.v1.Inventory.ListContainerContentsResponse =
  api.v1.ListContainerContentsResponseKt.Dsl._create(api.v1.Inventory.ListContainerContentsResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `api.v1.ListContainerContentsResponse`
 */
public object ListContainerContentsResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: api.v1.Inventory.ListContainerContentsResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: api.v1.Inventory.ListContainerContentsResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): api.v1.Inventory.ListContainerContentsResponse = _builder.build()

    /**
     * ```
     * The container being queried.
     * ```
     *
     * `string container_identifier = 1 [json_name = "containerIdentifier"];`
     */
    public var containerIdentifier: kotlin.String
      @JvmName("getContainerIdentifier")
      get() = _builder.containerIdentifier
      @JvmName("setContainerIdentifier")
      set(value) {
        _builder.containerIdentifier = value
      }
    /**
     * ```
     * The container being queried.
     * ```
     *
     * `string container_identifier = 1 [json_name = "containerIdentifier"];`
     */
    public fun clearContainerIdentifier() {
      _builder.clearContainerIdentifier()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ItemsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * Items directly in this container.
     * ```
     *
     * `repeated .api.v1.InventoryItem items = 2 [json_name = "items"];`
     */
     public val items: com.google.protobuf.kotlin.DslList<api.v1.Inventory.InventoryItem, ItemsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.itemsList
      )
    /**
     * ```
     * Items directly in this container.
     * ```
     *
     * `repeated .api.v1.InventoryItem items = 2 [json_name = "items"];`
     * @param value The items to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addItems")
    public fun com.google.protobuf.kotlin.DslList<api.v1.Inventory.InventoryItem, ItemsProxy>.add(value: api.v1.Inventory.InventoryItem) {
      _builder.addItems(value)
    }
    /**
     * ```
     * Items directly in this container.
     * ```
     *
     * `repeated .api.v1.InventoryItem items = 2 [json_name = "items"];`
     * @param value The items to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignItems")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<api.v1.Inventory.InventoryItem, ItemsProxy>.plusAssign(value: api.v1.Inventory.InventoryItem) {
      add(value)
    }
    /**
     * ```
     * Items directly in this container.
     * ```
     *
     * `repeated .api.v1.InventoryItem items = 2 [json_name = "items"];`
     * @param values The items to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllItems")
    public fun com.google.protobuf.kotlin.DslList<api.v1.Inventory.InventoryItem, ItemsProxy>.addAll(values: kotlin.collections.Iterable<api.v1.Inventory.InventoryItem>) {
      _builder.addAllItems(values)
    }
    /**
     * ```
     * Items directly in this container.
     * ```
     *
     * `repeated .api.v1.InventoryItem items = 2 [json_name = "items"];`
     * @param values The items to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllItems")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<api.v1.Inventory.InventoryItem, ItemsProxy>.plusAssign(values: kotlin.collections.Iterable<api.v1.Inventory.InventoryItem>) {
      addAll(values)
    }
    /**
     * ```
     * Items directly in this container.
     * ```
     *
     * `repeated .api.v1.InventoryItem items = 2 [json_name = "items"];`
     * @param index The index to set the value at.
     * @param value The items to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setItems")
    public operator fun com.google.protobuf.kotlin.DslList<api.v1.Inventory.InventoryItem, ItemsProxy>.set(index: kotlin.Int, value: api.v1.Inventory.InventoryItem) {
      _builder.setItems(index, value)
    }
    /**
     * ```
     * Items directly in this container.
     * ```
     *
     * `repeated .api.v1.InventoryItem items = 2 [json_name = "items"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearItems")
    public fun com.google.protobuf.kotlin.DslList<api.v1.Inventory.InventoryItem, ItemsProxy>.clear() {
      _builder.clearItems()
    }


    /**
     * ```
     * Total count of items (including nested if recursive).
     * ```
     *
     * `int32 total_count = 3 [json_name = "totalCount"];`
     */
    public var totalCount: kotlin.Int
      @JvmName("getTotalCount")
      get() = _builder.totalCount
      @JvmName("setTotalCount")
      set(value) {
        _builder.totalCount = value
      }
    /**
     * ```
     * Total count of items (including nested if recursive).
     * ```
     *
     * `int32 total_count = 3 [json_name = "totalCount"];`
     */
    public fun clearTotalCount() {
      _builder.clearTotalCount()
    }

    /**
     * ```
     * Human-readable summary suitable for LLM consumption.
     * ```
     *
     * `string summary = 4 [json_name = "summary"];`
     */
    public var summary: kotlin.String
      @JvmName("getSummary")
      get() = _builder.summary
      @JvmName("setSummary")
      set(value) {
        _builder.summary = value
      }
    /**
     * ```
     * Human-readable summary suitable for LLM consumption.
     * ```
     *
     * `string summary = 4 [json_name = "summary"];`
     */
    public fun clearSummary() {
      _builder.clearSummary()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun api.v1.Inventory.ListContainerContentsResponse.copy(block: `api.v1`.ListContainerContentsResponseKt.Dsl.() -> kotlin.Unit): api.v1.Inventory.ListContainerContentsResponse =
  `api.v1`.ListContainerContentsResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

