// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/inventory.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package api.v1;

@kotlin.jvm.JvmName("-initializelistContainerContentsRequest")
public inline fun listContainerContentsRequest(block: api.v1.ListContainerContentsRequestKt.Dsl.() -> kotlin.Unit): api.v1.Inventory.ListContainerContentsRequest =
  api.v1.ListContainerContentsRequestKt.Dsl._create(api.v1.Inventory.ListContainerContentsRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `api.v1.ListContainerContentsRequest`
 */
public object ListContainerContentsRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: api.v1.Inventory.ListContainerContentsRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: api.v1.Inventory.ListContainerContentsRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): api.v1.Inventory.ListContainerContentsRequest = _builder.build()

    /**
     * ```
     * The identifier of the container to list contents of.
     * ```
     *
     * `string container_identifier = 1 [json_name = "containerIdentifier"];`
     */
    public var containerIdentifier: kotlin.String
      @JvmName("getContainerIdentifier")
      get() = _builder.containerIdentifier
      @JvmName("setContainerIdentifier")
      set(value) {
        _builder.containerIdentifier = value
      }
    /**
     * ```
     * The identifier of the container to list contents of.
     * ```
     *
     * `string container_identifier = 1 [json_name = "containerIdentifier"];`
     */
    public fun clearContainerIdentifier() {
      _builder.clearContainerIdentifier()
    }

    /**
     * ```
     * Whether to recursively include items in nested containers.
     * Default: false (only direct items)
     * ```
     *
     * `bool recursive = 2 [json_name = "recursive"];`
     */
    public var recursive: kotlin.Boolean
      @JvmName("getRecursive")
      get() = _builder.recursive
      @JvmName("setRecursive")
      set(value) {
        _builder.recursive = value
      }
    /**
     * ```
     * Whether to recursively include items in nested containers.
     * Default: false (only direct items)
     * ```
     *
     * `bool recursive = 2 [json_name = "recursive"];`
     */
    public fun clearRecursive() {
      _builder.clearRecursive()
    }

    /**
     * ```
     * Maximum depth for recursive listing. 0 means unlimited.
     * Only used when recursive is true.
     * ```
     *
     * `int32 max_depth = 3 [json_name = "maxDepth"];`
     */
    public var maxDepth: kotlin.Int
      @JvmName("getMaxDepth")
      get() = _builder.maxDepth
      @JvmName("setMaxDepth")
      set(value) {
        _builder.maxDepth = value
      }
    /**
     * ```
     * Maximum depth for recursive listing. 0 means unlimited.
     * Only used when recursive is true.
     * ```
     *
     * `int32 max_depth = 3 [json_name = "maxDepth"];`
     */
    public fun clearMaxDepth() {
      _builder.clearMaxDepth()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun api.v1.Inventory.ListContainerContentsRequest.copy(block: `api.v1`.ListContainerContentsRequestKt.Dsl.() -> kotlin.Unit): api.v1.Inventory.ListContainerContentsRequest =
  `api.v1`.ListContainerContentsRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

