// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/frontmatter.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package api.v1;

@kotlin.jvm.JvmName("-initializemergeFrontmatterRequest")
public inline fun mergeFrontmatterRequest(block: api.v1.MergeFrontmatterRequestKt.Dsl.() -> kotlin.Unit): api.v1.FrontmatterOuterClass.MergeFrontmatterRequest =
  api.v1.MergeFrontmatterRequestKt.Dsl._create(api.v1.FrontmatterOuterClass.MergeFrontmatterRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * The request message for merging frontmatter.
 * ```
 *
 * Protobuf type `api.v1.MergeFrontmatterRequest`
 */
public object MergeFrontmatterRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: api.v1.FrontmatterOuterClass.MergeFrontmatterRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: api.v1.FrontmatterOuterClass.MergeFrontmatterRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): api.v1.FrontmatterOuterClass.MergeFrontmatterRequest = _builder.build()

    /**
     * `string page = 1 [json_name = "page"];`
     */
    public var page: kotlin.String
      @JvmName("getPage")
      get() = _builder.page
      @JvmName("setPage")
      set(value) {
        _builder.page = value
      }
    /**
     * `string page = 1 [json_name = "page"];`
     */
    public fun clearPage() {
      _builder.clearPage()
    }

    /**
     * ```
     * The frontmatter fields to merge.
     * ```
     *
     * `.google.protobuf.Struct frontmatter = 2 [json_name = "frontmatter"];`
     */
    public var frontmatter: com.google.protobuf.Struct
      @JvmName("getFrontmatter")
      get() = _builder.frontmatter
      @JvmName("setFrontmatter")
      set(value) {
        _builder.frontmatter = value
      }
    /**
     * ```
     * The frontmatter fields to merge.
     * ```
     *
     * `.google.protobuf.Struct frontmatter = 2 [json_name = "frontmatter"];`
     */
    public fun clearFrontmatter() {
      _builder.clearFrontmatter()
    }
    /**
     * ```
     * The frontmatter fields to merge.
     * ```
     *
     * `.google.protobuf.Struct frontmatter = 2 [json_name = "frontmatter"];`
     * @return Whether the frontmatter field is set.
     */
    public fun hasFrontmatter(): kotlin.Boolean {
      return _builder.hasFrontmatter()
    }
    public val MergeFrontmatterRequestKt.Dsl.frontmatterOrNull: com.google.protobuf.Struct?
      get() = _builder.frontmatterOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun api.v1.FrontmatterOuterClass.MergeFrontmatterRequest.copy(block: `api.v1`.MergeFrontmatterRequestKt.Dsl.() -> kotlin.Unit): api.v1.FrontmatterOuterClass.MergeFrontmatterRequest =
  `api.v1`.MergeFrontmatterRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val api.v1.FrontmatterOuterClass.MergeFrontmatterRequestOrBuilder.frontmatterOrNull: com.google.protobuf.Struct?
  get() = if (hasFrontmatter()) getFrontmatter() else null

