// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/inventory.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package api.v1;

@kotlin.jvm.JvmName("-initializemoveInventoryItemResponse")
public inline fun moveInventoryItemResponse(block: api.v1.MoveInventoryItemResponseKt.Dsl.() -> kotlin.Unit): api.v1.Inventory.MoveInventoryItemResponse =
  api.v1.MoveInventoryItemResponseKt.Dsl._create(api.v1.Inventory.MoveInventoryItemResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `api.v1.MoveInventoryItemResponse`
 */
public object MoveInventoryItemResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: api.v1.Inventory.MoveInventoryItemResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: api.v1.Inventory.MoveInventoryItemResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): api.v1.Inventory.MoveInventoryItemResponse = _builder.build()

    /**
     * ```
     * Whether the operation was successful.
     * ```
     *
     * `bool success = 1 [json_name = "success"];`
     */
    public var success: kotlin.Boolean
      @JvmName("getSuccess")
      get() = _builder.success
      @JvmName("setSuccess")
      set(value) {
        _builder.success = value
      }
    /**
     * ```
     * Whether the operation was successful.
     * ```
     *
     * `bool success = 1 [json_name = "success"];`
     */
    public fun clearSuccess() {
      _builder.clearSuccess()
    }

    /**
     * ```
     * The previous container the item was in (empty if it was a root-level item).
     * ```
     *
     * `string previous_container = 2 [json_name = "previousContainer"];`
     */
    public var previousContainer: kotlin.String
      @JvmName("getPreviousContainer")
      get() = _builder.previousContainer
      @JvmName("setPreviousContainer")
      set(value) {
        _builder.previousContainer = value
      }
    /**
     * ```
     * The previous container the item was in (empty if it was a root-level item).
     * ```
     *
     * `string previous_container = 2 [json_name = "previousContainer"];`
     */
    public fun clearPreviousContainer() {
      _builder.clearPreviousContainer()
    }

    /**
     * ```
     * The new container the item is now in.
     * ```
     *
     * `string new_container = 3 [json_name = "newContainer"];`
     */
    public var newContainer: kotlin.String
      @JvmName("getNewContainer")
      get() = _builder.newContainer
      @JvmName("setNewContainer")
      set(value) {
        _builder.newContainer = value
      }
    /**
     * ```
     * The new container the item is now in.
     * ```
     *
     * `string new_container = 3 [json_name = "newContainer"];`
     */
    public fun clearNewContainer() {
      _builder.clearNewContainer()
    }

    /**
     * ```
     * Human-readable summary of the action taken, suitable for LLM consumption.
     * ```
     *
     * `string summary = 4 [json_name = "summary"];`
     */
    public var summary: kotlin.String
      @JvmName("getSummary")
      get() = _builder.summary
      @JvmName("setSummary")
      set(value) {
        _builder.summary = value
      }
    /**
     * ```
     * Human-readable summary of the action taken, suitable for LLM consumption.
     * ```
     *
     * `string summary = 4 [json_name = "summary"];`
     */
    public fun clearSummary() {
      _builder.clearSummary()
    }

    /**
     * ```
     * Error message if the operation failed.
     * ```
     *
     * `string error = 5 [json_name = "error"];`
     */
    public var error: kotlin.String
      @JvmName("getError")
      get() = _builder.error
      @JvmName("setError")
      set(value) {
        _builder.error = value
      }
    /**
     * ```
     * Error message if the operation failed.
     * ```
     *
     * `string error = 5 [json_name = "error"];`
     */
    public fun clearError() {
      _builder.clearError()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun api.v1.Inventory.MoveInventoryItemResponse.copy(block: `api.v1`.MoveInventoryItemResponseKt.Dsl.() -> kotlin.Unit): api.v1.Inventory.MoveInventoryItemResponse =
  `api.v1`.MoveInventoryItemResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

