// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/inventory.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package api.v1;

@kotlin.jvm.JvmName("-initializemoveInventoryItemRequest")
public inline fun moveInventoryItemRequest(block: api.v1.MoveInventoryItemRequestKt.Dsl.() -> kotlin.Unit): api.v1.Inventory.MoveInventoryItemRequest =
  api.v1.MoveInventoryItemRequestKt.Dsl._create(api.v1.Inventory.MoveInventoryItemRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `api.v1.MoveInventoryItemRequest`
 */
public object MoveInventoryItemRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: api.v1.Inventory.MoveInventoryItemRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: api.v1.Inventory.MoveInventoryItemRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): api.v1.Inventory.MoveInventoryItemRequest = _builder.build()

    /**
     * ```
     * The identifier of the item to move.
     * ```
     *
     * `string item_identifier = 1 [json_name = "itemIdentifier"];`
     */
    public var itemIdentifier: kotlin.String
      @JvmName("getItemIdentifier")
      get() = _builder.itemIdentifier
      @JvmName("setItemIdentifier")
      set(value) {
        _builder.itemIdentifier = value
      }
    /**
     * ```
     * The identifier of the item to move.
     * ```
     *
     * `string item_identifier = 1 [json_name = "itemIdentifier"];`
     */
    public fun clearItemIdentifier() {
      _builder.clearItemIdentifier()
    }

    /**
     * ```
     * The new container to move the item to.
     * If empty, removes the item from any container (makes it a root-level item).
     * ```
     *
     * `string new_container = 2 [json_name = "newContainer"];`
     */
    public var newContainer: kotlin.String
      @JvmName("getNewContainer")
      get() = _builder.newContainer
      @JvmName("setNewContainer")
      set(value) {
        _builder.newContainer = value
      }
    /**
     * ```
     * The new container to move the item to.
     * If empty, removes the item from any container (makes it a root-level item).
     * ```
     *
     * `string new_container = 2 [json_name = "newContainer"];`
     */
    public fun clearNewContainer() {
      _builder.clearNewContainer()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun api.v1.Inventory.MoveInventoryItemRequest.copy(block: `api.v1`.MoveInventoryItemRequestKt.Dsl.() -> kotlin.Unit): api.v1.Inventory.MoveInventoryItemRequest =
  `api.v1`.MoveInventoryItemRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

