// Code generated by connect-kotlin. DO NOT EDIT.
//
// Source: api/v1/page_management.proto
//
package api.v1

import com.connectrpc.Headers
import com.connectrpc.ResponseMessage

public interface PageManagementServiceClientInterface {
  public suspend fun createPage(request: PageManagement.CreatePageRequest, headers: Headers = emptyMap()): ResponseMessage<PageManagement.CreatePageResponse>

  public suspend fun readPage(request: PageManagement.ReadPageRequest, headers: Headers = emptyMap()): ResponseMessage<PageManagement.ReadPageResponse>

  public suspend fun renderPage(request: PageManagement.RenderPageRequest, headers: Headers = emptyMap()): ResponseMessage<PageManagement.RenderPageResponse>

  public suspend fun updatePage(request: PageManagement.UpdatePageRequest, headers: Headers = emptyMap()): ResponseMessage<PageManagement.UpdatePageResponse>

  public suspend fun updatePageContent(request: PageManagement.UpdatePageContentRequest, headers: Headers = emptyMap()): ResponseMessage<PageManagement.UpdatePageContentResponse>

  public suspend fun updateWholePage(request: PageManagement.UpdateWholePageRequest, headers: Headers = emptyMap()): ResponseMessage<PageManagement.UpdateWholePageResponse>

  public suspend fun deletePage(request: PageManagement.DeletePageRequest, headers: Headers = emptyMap()): ResponseMessage<PageManagement.DeletePageResponse>

  /**
   *  GenerateIdentifier converts text to a wiki page identifier format.
   *  Used by UI to auto-generate identifiers from titles and check availability.
   */
  public suspend fun generateIdentifier(request: PageManagement.GenerateIdentifierRequest, headers: Headers = emptyMap()): ResponseMessage<PageManagement.GenerateIdentifierResponse>
}
