// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/frontmatter.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package api.v1;

@kotlin.jvm.JvmName("-initializeremoveKeyAtPathRequest")
public inline fun removeKeyAtPathRequest(block: api.v1.RemoveKeyAtPathRequestKt.Dsl.() -> kotlin.Unit): api.v1.FrontmatterOuterClass.RemoveKeyAtPathRequest =
  api.v1.RemoveKeyAtPathRequestKt.Dsl._create(api.v1.FrontmatterOuterClass.RemoveKeyAtPathRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * The request for removing a key at a path.
 * ```
 *
 * Protobuf type `api.v1.RemoveKeyAtPathRequest`
 */
public object RemoveKeyAtPathRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: api.v1.FrontmatterOuterClass.RemoveKeyAtPathRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: api.v1.FrontmatterOuterClass.RemoveKeyAtPathRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): api.v1.FrontmatterOuterClass.RemoveKeyAtPathRequest = _builder.build()

    /**
     * `string page = 1 [json_name = "page"];`
     */
    public var page: kotlin.String
      @JvmName("getPage")
      get() = _builder.page
      @JvmName("setPage")
      set(value) {
        _builder.page = value
      }
    /**
     * `string page = 1 [json_name = "page"];`
     */
    public fun clearPage() {
      _builder.clearPage()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class KeyPathProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * The path to the key to remove.
     * ```
     *
     * `repeated .api.v1.PathComponent key_path = 2 [json_name = "keyPath"];`
     */
     public val keyPath: com.google.protobuf.kotlin.DslList<api.v1.FrontmatterOuterClass.PathComponent, KeyPathProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.keyPathList
      )
    /**
     * ```
     * The path to the key to remove.
     * ```
     *
     * `repeated .api.v1.PathComponent key_path = 2 [json_name = "keyPath"];`
     * @param value The keyPath to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addKeyPath")
    public fun com.google.protobuf.kotlin.DslList<api.v1.FrontmatterOuterClass.PathComponent, KeyPathProxy>.add(value: api.v1.FrontmatterOuterClass.PathComponent) {
      _builder.addKeyPath(value)
    }
    /**
     * ```
     * The path to the key to remove.
     * ```
     *
     * `repeated .api.v1.PathComponent key_path = 2 [json_name = "keyPath"];`
     * @param value The keyPath to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignKeyPath")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<api.v1.FrontmatterOuterClass.PathComponent, KeyPathProxy>.plusAssign(value: api.v1.FrontmatterOuterClass.PathComponent) {
      add(value)
    }
    /**
     * ```
     * The path to the key to remove.
     * ```
     *
     * `repeated .api.v1.PathComponent key_path = 2 [json_name = "keyPath"];`
     * @param values The keyPath to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllKeyPath")
    public fun com.google.protobuf.kotlin.DslList<api.v1.FrontmatterOuterClass.PathComponent, KeyPathProxy>.addAll(values: kotlin.collections.Iterable<api.v1.FrontmatterOuterClass.PathComponent>) {
      _builder.addAllKeyPath(values)
    }
    /**
     * ```
     * The path to the key to remove.
     * ```
     *
     * `repeated .api.v1.PathComponent key_path = 2 [json_name = "keyPath"];`
     * @param values The keyPath to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllKeyPath")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<api.v1.FrontmatterOuterClass.PathComponent, KeyPathProxy>.plusAssign(values: kotlin.collections.Iterable<api.v1.FrontmatterOuterClass.PathComponent>) {
      addAll(values)
    }
    /**
     * ```
     * The path to the key to remove.
     * ```
     *
     * `repeated .api.v1.PathComponent key_path = 2 [json_name = "keyPath"];`
     * @param index The index to set the value at.
     * @param value The keyPath to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setKeyPath")
    public operator fun com.google.protobuf.kotlin.DslList<api.v1.FrontmatterOuterClass.PathComponent, KeyPathProxy>.set(index: kotlin.Int, value: api.v1.FrontmatterOuterClass.PathComponent) {
      _builder.setKeyPath(index, value)
    }
    /**
     * ```
     * The path to the key to remove.
     * ```
     *
     * `repeated .api.v1.PathComponent key_path = 2 [json_name = "keyPath"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearKeyPath")
    public fun com.google.protobuf.kotlin.DslList<api.v1.FrontmatterOuterClass.PathComponent, KeyPathProxy>.clear() {
      _builder.clearKeyPath()
    }

  }
}
@kotlin.jvm.JvmSynthetic
public inline fun api.v1.FrontmatterOuterClass.RemoveKeyAtPathRequest.copy(block: `api.v1`.RemoveKeyAtPathRequestKt.Dsl.() -> kotlin.Unit): api.v1.FrontmatterOuterClass.RemoveKeyAtPathRequest =
  `api.v1`.RemoveKeyAtPathRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

