// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/frontmatter.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package api.v1;

@kotlin.jvm.JvmName("-initializeremoveKeyAtPathResponse")
public inline fun removeKeyAtPathResponse(block: api.v1.RemoveKeyAtPathResponseKt.Dsl.() -> kotlin.Unit): api.v1.FrontmatterOuterClass.RemoveKeyAtPathResponse =
  api.v1.RemoveKeyAtPathResponseKt.Dsl._create(api.v1.FrontmatterOuterClass.RemoveKeyAtPathResponse.newBuilder()).apply { block() }._build()
/**
 * ```
 * The response for removing a key at a path.
 * ```
 *
 * Protobuf type `api.v1.RemoveKeyAtPathResponse`
 */
public object RemoveKeyAtPathResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: api.v1.FrontmatterOuterClass.RemoveKeyAtPathResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: api.v1.FrontmatterOuterClass.RemoveKeyAtPathResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): api.v1.FrontmatterOuterClass.RemoveKeyAtPathResponse = _builder.build()

    /**
     * ```
     * The updated frontmatter after removal.
     * ```
     *
     * `.google.protobuf.Struct frontmatter = 1 [json_name = "frontmatter"];`
     */
    public var frontmatter: com.google.protobuf.Struct
      @JvmName("getFrontmatter")
      get() = _builder.frontmatter
      @JvmName("setFrontmatter")
      set(value) {
        _builder.frontmatter = value
      }
    /**
     * ```
     * The updated frontmatter after removal.
     * ```
     *
     * `.google.protobuf.Struct frontmatter = 1 [json_name = "frontmatter"];`
     */
    public fun clearFrontmatter() {
      _builder.clearFrontmatter()
    }
    /**
     * ```
     * The updated frontmatter after removal.
     * ```
     *
     * `.google.protobuf.Struct frontmatter = 1 [json_name = "frontmatter"];`
     * @return Whether the frontmatter field is set.
     */
    public fun hasFrontmatter(): kotlin.Boolean {
      return _builder.hasFrontmatter()
    }
    public val RemoveKeyAtPathResponseKt.Dsl.frontmatterOrNull: com.google.protobuf.Struct?
      get() = _builder.frontmatterOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun api.v1.FrontmatterOuterClass.RemoveKeyAtPathResponse.copy(block: `api.v1`.RemoveKeyAtPathResponseKt.Dsl.() -> kotlin.Unit): api.v1.FrontmatterOuterClass.RemoveKeyAtPathResponse =
  `api.v1`.RemoveKeyAtPathResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val api.v1.FrontmatterOuterClass.RemoveKeyAtPathResponseOrBuilder.frontmatterOrNull: com.google.protobuf.Struct?
  get() = if (hasFrontmatter()) getFrontmatter() else null

