// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/page_management.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package api.v1;

@kotlin.jvm.JvmName("-initializerenderPageRequest")
public inline fun renderPageRequest(block: api.v1.RenderPageRequestKt.Dsl.() -> kotlin.Unit): api.v1.PageManagement.RenderPageRequest =
  api.v1.RenderPageRequestKt.Dsl._create(api.v1.PageManagement.RenderPageRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * Render Page
 * ```
 *
 * Protobuf type `api.v1.RenderPageRequest`
 */
public object RenderPageRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: api.v1.PageManagement.RenderPageRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: api.v1.PageManagement.RenderPageRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): api.v1.PageManagement.RenderPageRequest = _builder.build()

    /**
     * `string page_name = 1 [json_name = "pageName"];`
     */
    public var pageName: kotlin.String
      @JvmName("getPageName")
      get() = _builder.pageName
      @JvmName("setPageName")
      set(value) {
        _builder.pageName = value
      }
    /**
     * `string page_name = 1 [json_name = "pageName"];`
     */
    public fun clearPageName() {
      _builder.clearPageName()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun api.v1.PageManagement.RenderPageRequest.copy(block: `api.v1`.RenderPageRequestKt.Dsl.() -> kotlin.Unit): api.v1.PageManagement.RenderPageRequest =
  `api.v1`.RenderPageRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

