// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/page_management.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package api.v1;

@kotlin.jvm.JvmName("-initializerenderPageResponse")
public inline fun renderPageResponse(block: api.v1.RenderPageResponseKt.Dsl.() -> kotlin.Unit): api.v1.PageManagement.RenderPageResponse =
  api.v1.RenderPageResponseKt.Dsl._create(api.v1.PageManagement.RenderPageResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `api.v1.RenderPageResponse`
 */
public object RenderPageResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: api.v1.PageManagement.RenderPageResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: api.v1.PageManagement.RenderPageResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): api.v1.PageManagement.RenderPageResponse = _builder.build()

    /**
     * `string rendered_content_html = 1 [json_name = "renderedContentHtml"];`
     */
    public var renderedContentHtml: kotlin.String
      @JvmName("getRenderedContentHtml")
      get() = _builder.renderedContentHtml
      @JvmName("setRenderedContentHtml")
      set(value) {
        _builder.renderedContentHtml = value
      }
    /**
     * `string rendered_content_html = 1 [json_name = "renderedContentHtml"];`
     */
    public fun clearRenderedContentHtml() {
      _builder.clearRenderedContentHtml()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun api.v1.PageManagement.RenderPageResponse.copy(block: `api.v1`.RenderPageResponseKt.Dsl.() -> kotlin.Unit): api.v1.PageManagement.RenderPageResponse =
  `api.v1`.RenderPageResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

