// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/search.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package api.v1;

@kotlin.jvm.JvmName("-initializesearchContentRequest")
public inline fun searchContentRequest(block: api.v1.SearchContentRequestKt.Dsl.() -> kotlin.Unit): api.v1.Search.SearchContentRequest =
  api.v1.SearchContentRequestKt.Dsl._create(api.v1.Search.SearchContentRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * The request message for searching content.
 * ```
 *
 * Protobuf type `api.v1.SearchContentRequest`
 */
public object SearchContentRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: api.v1.Search.SearchContentRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: api.v1.Search.SearchContentRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): api.v1.Search.SearchContentRequest = _builder.build()

    /**
     * `string query = 1 [json_name = "query"];`
     */
    public var query: kotlin.String
      @JvmName("getQuery")
      get() = _builder.query
      @JvmName("setQuery")
      set(value) {
        _builder.query = value
      }
    /**
     * `string query = 1 [json_name = "query"];`
     */
    public fun clearQuery() {
      _builder.clearQuery()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun api.v1.Search.SearchContentRequest.copy(block: `api.v1`.SearchContentRequestKt.Dsl.() -> kotlin.Unit): api.v1.Search.SearchContentRequest =
  `api.v1`.SearchContentRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

