// Code generated by connect-kotlin. DO NOT EDIT.
//
// Source: api/v1/search.proto
//
package api.v1

import com.connectrpc.Headers
import com.connectrpc.ResponseMessage

/**
 *  The Search service definition.
 */
public interface SearchServiceClientInterface {
  /**
   *  Searches the wiki content and returns matching results.
   */
  public suspend fun searchContent(request: Search.SearchContentRequest, headers: Headers = emptyMap()): ResponseMessage<Search.SearchContentResponse>
}
