// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/search.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package api.v1;

@kotlin.jvm.JvmName("-initializesearchResult")
public inline fun searchResult(block: api.v1.SearchResultKt.Dsl.() -> kotlin.Unit): api.v1.Search.SearchResult =
  api.v1.SearchResultKt.Dsl._create(api.v1.Search.SearchResult.newBuilder()).apply { block() }._build()
/**
 * ```
 * A search result item.
 * ```
 *
 * Protobuf type `api.v1.SearchResult`
 */
public object SearchResultKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: api.v1.Search.SearchResult.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: api.v1.Search.SearchResult.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): api.v1.Search.SearchResult = _builder.build()

    /**
     * ```
     * Page identifier
     * ```
     *
     * `string identifier = 1 [json_name = "identifier"];`
     */
    public var identifier: kotlin.String
      @JvmName("getIdentifier")
      get() = _builder.identifier
      @JvmName("setIdentifier")
      set(value) {
        _builder.identifier = value
      }
    /**
     * ```
     * Page identifier
     * ```
     *
     * `string identifier = 1 [json_name = "identifier"];`
     */
    public fun clearIdentifier() {
      _builder.clearIdentifier()
    }

    /**
     * ```
     * Page title
     * ```
     *
     * `string title = 2 [json_name = "title"];`
     */
    public var title: kotlin.String
      @JvmName("getTitle")
      get() = _builder.title
      @JvmName("setTitle")
      set(value) {
        _builder.title = value
      }
    /**
     * ```
     * Page title
     * ```
     *
     * `string title = 2 [json_name = "title"];`
     */
    public fun clearTitle() {
      _builder.clearTitle()
    }

    /**
     * ```
     * Plain text fragment (no HTML)
     * ```
     *
     * `string fragment = 3 [json_name = "fragment"];`
     */
    public var fragment: kotlin.String
      @JvmName("getFragment")
      get() = _builder.fragment
      @JvmName("setFragment")
      set(value) {
        _builder.fragment = value
      }
    /**
     * ```
     * Plain text fragment (no HTML)
     * ```
     *
     * `string fragment = 3 [json_name = "fragment"];`
     */
    public fun clearFragment() {
      _builder.clearFragment()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class HighlightsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * Highlight positions
     * ```
     *
     * `repeated .api.v1.HighlightSpan highlights = 4 [json_name = "highlights"];`
     */
     public val highlights: com.google.protobuf.kotlin.DslList<api.v1.Search.HighlightSpan, HighlightsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.highlightsList
      )
    /**
     * ```
     * Highlight positions
     * ```
     *
     * `repeated .api.v1.HighlightSpan highlights = 4 [json_name = "highlights"];`
     * @param value The highlights to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addHighlights")
    public fun com.google.protobuf.kotlin.DslList<api.v1.Search.HighlightSpan, HighlightsProxy>.add(value: api.v1.Search.HighlightSpan) {
      _builder.addHighlights(value)
    }
    /**
     * ```
     * Highlight positions
     * ```
     *
     * `repeated .api.v1.HighlightSpan highlights = 4 [json_name = "highlights"];`
     * @param value The highlights to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignHighlights")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<api.v1.Search.HighlightSpan, HighlightsProxy>.plusAssign(value: api.v1.Search.HighlightSpan) {
      add(value)
    }
    /**
     * ```
     * Highlight positions
     * ```
     *
     * `repeated .api.v1.HighlightSpan highlights = 4 [json_name = "highlights"];`
     * @param values The highlights to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllHighlights")
    public fun com.google.protobuf.kotlin.DslList<api.v1.Search.HighlightSpan, HighlightsProxy>.addAll(values: kotlin.collections.Iterable<api.v1.Search.HighlightSpan>) {
      _builder.addAllHighlights(values)
    }
    /**
     * ```
     * Highlight positions
     * ```
     *
     * `repeated .api.v1.HighlightSpan highlights = 4 [json_name = "highlights"];`
     * @param values The highlights to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllHighlights")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<api.v1.Search.HighlightSpan, HighlightsProxy>.plusAssign(values: kotlin.collections.Iterable<api.v1.Search.HighlightSpan>) {
      addAll(values)
    }
    /**
     * ```
     * Highlight positions
     * ```
     *
     * `repeated .api.v1.HighlightSpan highlights = 4 [json_name = "highlights"];`
     * @param index The index to set the value at.
     * @param value The highlights to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setHighlights")
    public operator fun com.google.protobuf.kotlin.DslList<api.v1.Search.HighlightSpan, HighlightsProxy>.set(index: kotlin.Int, value: api.v1.Search.HighlightSpan) {
      _builder.setHighlights(index, value)
    }
    /**
     * ```
     * Highlight positions
     * ```
     *
     * `repeated .api.v1.HighlightSpan highlights = 4 [json_name = "highlights"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearHighlights")
    public fun com.google.protobuf.kotlin.DslList<api.v1.Search.HighlightSpan, HighlightsProxy>.clear() {
      _builder.clearHighlights()
    }


    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class FrontmatterProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * Requested frontmatter values (dot-path -> value)
     * ```
     *
     * `map<string, string> frontmatter = 5 [json_name = "frontmatter"];`
     */
     public val frontmatter: com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, FrontmatterProxy>
      @kotlin.jvm.JvmSynthetic
      @JvmName("getFrontmatterMap")
      get() = com.google.protobuf.kotlin.DslMap(
        _builder.frontmatterMap
      )
    /**
     * ```
     * Requested frontmatter values (dot-path -> value)
     * ```
     *
     * `map<string, string> frontmatter = 5 [json_name = "frontmatter"];`
     */
    @JvmName("putFrontmatter")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, FrontmatterProxy>
      .put(key: kotlin.String, value: kotlin.String) {
         _builder.putFrontmatter(key, value)
       }
    /**
     * ```
     * Requested frontmatter values (dot-path -> value)
     * ```
     *
     * `map<string, string> frontmatter = 5 [json_name = "frontmatter"];`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("setFrontmatter")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, FrontmatterProxy>
      .set(key: kotlin.String, value: kotlin.String) {
         put(key, value)
       }
    /**
     * ```
     * Requested frontmatter values (dot-path -> value)
     * ```
     *
     * `map<string, string> frontmatter = 5 [json_name = "frontmatter"];`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("removeFrontmatter")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, FrontmatterProxy>
      .remove(key: kotlin.String) {
         _builder.removeFrontmatter(key)
       }
    /**
     * ```
     * Requested frontmatter values (dot-path -> value)
     * ```
     *
     * `map<string, string> frontmatter = 5 [json_name = "frontmatter"];`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("putAllFrontmatter")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, FrontmatterProxy>
      .putAll(map: kotlin.collections.Map<kotlin.String, kotlin.String>) {
         _builder.putAllFrontmatter(map)
       }
    /**
     * ```
     * Requested frontmatter values (dot-path -> value)
     * ```
     *
     * `map<string, string> frontmatter = 5 [json_name = "frontmatter"];`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("clearFrontmatter")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, FrontmatterProxy>
      .clear() {
         _builder.clearFrontmatter()
       }

    /**
     * ```
     * Inventory context (if result is an inventory item)
     * ```
     *
     * `.api.v1.InventoryContext inventory_context = 6 [json_name = "inventoryContext"];`
     */
    public var inventoryContext: api.v1.Search.InventoryContext
      @JvmName("getInventoryContext")
      get() = _builder.inventoryContext
      @JvmName("setInventoryContext")
      set(value) {
        _builder.inventoryContext = value
      }
    /**
     * ```
     * Inventory context (if result is an inventory item)
     * ```
     *
     * `.api.v1.InventoryContext inventory_context = 6 [json_name = "inventoryContext"];`
     */
    public fun clearInventoryContext() {
      _builder.clearInventoryContext()
    }
    /**
     * ```
     * Inventory context (if result is an inventory item)
     * ```
     *
     * `.api.v1.InventoryContext inventory_context = 6 [json_name = "inventoryContext"];`
     * @return Whether the inventoryContext field is set.
     */
    public fun hasInventoryContext(): kotlin.Boolean {
      return _builder.hasInventoryContext()
    }
    public val SearchResultKt.Dsl.inventoryContextOrNull: api.v1.Search.InventoryContext?
      get() = _builder.inventoryContextOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun api.v1.Search.SearchResult.copy(block: `api.v1`.SearchResultKt.Dsl.() -> kotlin.Unit): api.v1.Search.SearchResult =
  `api.v1`.SearchResultKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val api.v1.Search.SearchResultOrBuilder.inventoryContextOrNull: api.v1.Search.InventoryContext?
  get() = if (hasInventoryContext()) getInventoryContext() else null

