// Code generated by connect-kotlin. DO NOT EDIT.
//
// Source: api/v1/search.proto
//
package api.v1

import com.connectrpc.Headers
import com.connectrpc.MethodSpec
import com.connectrpc.ProtocolClientInterface
import com.connectrpc.ResponseMessage
import com.connectrpc.StreamType

/**
 *  The Search service definition.
 */
public class SearchServiceClient(
  private val client: ProtocolClientInterface,
) : SearchServiceClientInterface {
  /**
   *  Searches the wiki content and returns matching results.
   */
  override suspend fun searchContent(request: Search.SearchContentRequest, headers: Headers): ResponseMessage<Search.SearchContentResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "api.v1.SearchService/SearchContent",
      api.v1.Search.SearchContentRequest::class,
      api.v1.Search.SearchContentResponse::class,
      StreamType.UNARY,
    ),
  )

}
