// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/search.proto
// Protobuf Java Version: 4.28.3

package api.v1;

public final class Search {
  private Search() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface SearchContentRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.v1.SearchContentRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string query = 1 [json_name = "query"];</code>
     * @return The query.
     */
    java.lang.String getQuery();
    /**
     * <code>string query = 1 [json_name = "query"];</code>
     * @return The bytes for query.
     */
    com.google.protobuf.ByteString
        getQueryBytes();

    /**
     * <pre>
     * Optional: filter results to only pages that have ALL of these frontmatter keys
     * </pre>
     *
     * <code>repeated string frontmatter_key_include_filters = 2 [json_name = "frontmatterKeyIncludeFilters"];</code>
     * @return A list containing the frontmatterKeyIncludeFilters.
     */
    java.util.List<java.lang.String>
        getFrontmatterKeyIncludeFiltersList();
    /**
     * <pre>
     * Optional: filter results to only pages that have ALL of these frontmatter keys
     * </pre>
     *
     * <code>repeated string frontmatter_key_include_filters = 2 [json_name = "frontmatterKeyIncludeFilters"];</code>
     * @return The count of frontmatterKeyIncludeFilters.
     */
    int getFrontmatterKeyIncludeFiltersCount();
    /**
     * <pre>
     * Optional: filter results to only pages that have ALL of these frontmatter keys
     * </pre>
     *
     * <code>repeated string frontmatter_key_include_filters = 2 [json_name = "frontmatterKeyIncludeFilters"];</code>
     * @param index The index of the element to return.
     * @return The frontmatterKeyIncludeFilters at the given index.
     */
    java.lang.String getFrontmatterKeyIncludeFilters(int index);
    /**
     * <pre>
     * Optional: filter results to only pages that have ALL of these frontmatter keys
     * </pre>
     *
     * <code>repeated string frontmatter_key_include_filters = 2 [json_name = "frontmatterKeyIncludeFilters"];</code>
     * @param index The index of the element to return.
     * @return The frontmatterKeyIncludeFilters at the given index.
     */
    com.google.protobuf.ByteString
        getFrontmatterKeyIncludeFiltersBytes(int index);

    /**
     * <pre>
     * Optional: filter OUT results that have ANY of these frontmatter keys
     * </pre>
     *
     * <code>repeated string frontmatter_key_exclude_filters = 3 [json_name = "frontmatterKeyExcludeFilters"];</code>
     * @return A list containing the frontmatterKeyExcludeFilters.
     */
    java.util.List<java.lang.String>
        getFrontmatterKeyExcludeFiltersList();
    /**
     * <pre>
     * Optional: filter OUT results that have ANY of these frontmatter keys
     * </pre>
     *
     * <code>repeated string frontmatter_key_exclude_filters = 3 [json_name = "frontmatterKeyExcludeFilters"];</code>
     * @return The count of frontmatterKeyExcludeFilters.
     */
    int getFrontmatterKeyExcludeFiltersCount();
    /**
     * <pre>
     * Optional: filter OUT results that have ANY of these frontmatter keys
     * </pre>
     *
     * <code>repeated string frontmatter_key_exclude_filters = 3 [json_name = "frontmatterKeyExcludeFilters"];</code>
     * @param index The index of the element to return.
     * @return The frontmatterKeyExcludeFilters at the given index.
     */
    java.lang.String getFrontmatterKeyExcludeFilters(int index);
    /**
     * <pre>
     * Optional: filter OUT results that have ANY of these frontmatter keys
     * </pre>
     *
     * <code>repeated string frontmatter_key_exclude_filters = 3 [json_name = "frontmatterKeyExcludeFilters"];</code>
     * @param index The index of the element to return.
     * @return The frontmatterKeyExcludeFilters at the given index.
     */
    com.google.protobuf.ByteString
        getFrontmatterKeyExcludeFiltersBytes(int index);
  }
  /**
   * <pre>
   * The request message for searching content.
   * </pre>
   *
   * Protobuf type {@code api.v1.SearchContentRequest}
   */
  public  static final class SearchContentRequest extends
      com.google.protobuf.GeneratedMessageLite<
          SearchContentRequest, SearchContentRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:api.v1.SearchContentRequest)
      SearchContentRequestOrBuilder {
    private SearchContentRequest() {
      query_ = "";
      frontmatterKeyIncludeFilters_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
      frontmatterKeyExcludeFilters_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }
    public static final int QUERY_FIELD_NUMBER = 1;
    private java.lang.String query_;
    /**
     * <code>string query = 1 [json_name = "query"];</code>
     * @return The query.
     */
    @java.lang.Override
    public java.lang.String getQuery() {
      return query_;
    }
    /**
     * <code>string query = 1 [json_name = "query"];</code>
     * @return The bytes for query.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getQueryBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(query_);
    }
    /**
     * <code>string query = 1 [json_name = "query"];</code>
     * @param value The query to set.
     */
    private void setQuery(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      query_ = value;
    }
    /**
     * <code>string query = 1 [json_name = "query"];</code>
     */
    private void clearQuery() {

      query_ = getDefaultInstance().getQuery();
    }
    /**
     * <code>string query = 1 [json_name = "query"];</code>
     * @param value The bytes for query to set.
     */
    private void setQueryBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      query_ = value.toStringUtf8();

    }

    public static final int FRONTMATTER_KEY_INCLUDE_FILTERS_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.ProtobufList<java.lang.String> frontmatterKeyIncludeFilters_;
    /**
     * <pre>
     * Optional: filter results to only pages that have ALL of these frontmatter keys
     * </pre>
     *
     * <code>repeated string frontmatter_key_include_filters = 2 [json_name = "frontmatterKeyIncludeFilters"];</code>
     * @return A list containing the frontmatterKeyIncludeFilters.
     */
    @java.lang.Override
    public java.util.List<java.lang.String> getFrontmatterKeyIncludeFiltersList() {
      return frontmatterKeyIncludeFilters_;
    }
    /**
     * <pre>
     * Optional: filter results to only pages that have ALL of these frontmatter keys
     * </pre>
     *
     * <code>repeated string frontmatter_key_include_filters = 2 [json_name = "frontmatterKeyIncludeFilters"];</code>
     * @return The count of frontmatterKeyIncludeFilters.
     */
    @java.lang.Override
    public int getFrontmatterKeyIncludeFiltersCount() {
      return frontmatterKeyIncludeFilters_.size();
    }
    /**
     * <pre>
     * Optional: filter results to only pages that have ALL of these frontmatter keys
     * </pre>
     *
     * <code>repeated string frontmatter_key_include_filters = 2 [json_name = "frontmatterKeyIncludeFilters"];</code>
     * @param index The index of the element to return.
     * @return The frontmatterKeyIncludeFilters at the given index.
     */
    @java.lang.Override
    public java.lang.String getFrontmatterKeyIncludeFilters(int index) {
      return frontmatterKeyIncludeFilters_.get(index);
    }
    /**
     * <pre>
     * Optional: filter results to only pages that have ALL of these frontmatter keys
     * </pre>
     *
     * <code>repeated string frontmatter_key_include_filters = 2 [json_name = "frontmatterKeyIncludeFilters"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the frontmatterKeyIncludeFilters at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFrontmatterKeyIncludeFiltersBytes(int index) {
      return com.google.protobuf.ByteString.copyFromUtf8(
          frontmatterKeyIncludeFilters_.get(index));
    }
    private void ensureFrontmatterKeyIncludeFiltersIsMutable() {
      com.google.protobuf.Internal.ProtobufList<java.lang.String> tmp =
          frontmatterKeyIncludeFilters_;  if (!tmp.isModifiable()) {
        frontmatterKeyIncludeFilters_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }
    /**
     * <pre>
     * Optional: filter results to only pages that have ALL of these frontmatter keys
     * </pre>
     *
     * <code>repeated string frontmatter_key_include_filters = 2 [json_name = "frontmatterKeyIncludeFilters"];</code>
     * @param index The index to set the value at.
     * @param value The frontmatterKeyIncludeFilters to set.
     */
    private void setFrontmatterKeyIncludeFilters(
        int index, java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  ensureFrontmatterKeyIncludeFiltersIsMutable();
      frontmatterKeyIncludeFilters_.set(index, value);
    }
    /**
     * <pre>
     * Optional: filter results to only pages that have ALL of these frontmatter keys
     * </pre>
     *
     * <code>repeated string frontmatter_key_include_filters = 2 [json_name = "frontmatterKeyIncludeFilters"];</code>
     * @param value The frontmatterKeyIncludeFilters to add.
     */
    private void addFrontmatterKeyIncludeFilters(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  ensureFrontmatterKeyIncludeFiltersIsMutable();
      frontmatterKeyIncludeFilters_.add(value);
    }
    /**
     * <pre>
     * Optional: filter results to only pages that have ALL of these frontmatter keys
     * </pre>
     *
     * <code>repeated string frontmatter_key_include_filters = 2 [json_name = "frontmatterKeyIncludeFilters"];</code>
     * @param values The frontmatterKeyIncludeFilters to add.
     */
    private void addAllFrontmatterKeyIncludeFilters(
        java.lang.Iterable<java.lang.String> values) {
      ensureFrontmatterKeyIncludeFiltersIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, frontmatterKeyIncludeFilters_);
    }
    /**
     * <pre>
     * Optional: filter results to only pages that have ALL of these frontmatter keys
     * </pre>
     *
     * <code>repeated string frontmatter_key_include_filters = 2 [json_name = "frontmatterKeyIncludeFilters"];</code>
     */
    private void clearFrontmatterKeyIncludeFilters() {
      frontmatterKeyIncludeFilters_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }
    /**
     * <pre>
     * Optional: filter results to only pages that have ALL of these frontmatter keys
     * </pre>
     *
     * <code>repeated string frontmatter_key_include_filters = 2 [json_name = "frontmatterKeyIncludeFilters"];</code>
     * @param value The bytes of the frontmatterKeyIncludeFilters to add.
     */
    private void addFrontmatterKeyIncludeFiltersBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      ensureFrontmatterKeyIncludeFiltersIsMutable();
      frontmatterKeyIncludeFilters_.add(value.toStringUtf8());
    }

    public static final int FRONTMATTER_KEY_EXCLUDE_FILTERS_FIELD_NUMBER = 3;
    private com.google.protobuf.Internal.ProtobufList<java.lang.String> frontmatterKeyExcludeFilters_;
    /**
     * <pre>
     * Optional: filter OUT results that have ANY of these frontmatter keys
     * </pre>
     *
     * <code>repeated string frontmatter_key_exclude_filters = 3 [json_name = "frontmatterKeyExcludeFilters"];</code>
     * @return A list containing the frontmatterKeyExcludeFilters.
     */
    @java.lang.Override
    public java.util.List<java.lang.String> getFrontmatterKeyExcludeFiltersList() {
      return frontmatterKeyExcludeFilters_;
    }
    /**
     * <pre>
     * Optional: filter OUT results that have ANY of these frontmatter keys
     * </pre>
     *
     * <code>repeated string frontmatter_key_exclude_filters = 3 [json_name = "frontmatterKeyExcludeFilters"];</code>
     * @return The count of frontmatterKeyExcludeFilters.
     */
    @java.lang.Override
    public int getFrontmatterKeyExcludeFiltersCount() {
      return frontmatterKeyExcludeFilters_.size();
    }
    /**
     * <pre>
     * Optional: filter OUT results that have ANY of these frontmatter keys
     * </pre>
     *
     * <code>repeated string frontmatter_key_exclude_filters = 3 [json_name = "frontmatterKeyExcludeFilters"];</code>
     * @param index The index of the element to return.
     * @return The frontmatterKeyExcludeFilters at the given index.
     */
    @java.lang.Override
    public java.lang.String getFrontmatterKeyExcludeFilters(int index) {
      return frontmatterKeyExcludeFilters_.get(index);
    }
    /**
     * <pre>
     * Optional: filter OUT results that have ANY of these frontmatter keys
     * </pre>
     *
     * <code>repeated string frontmatter_key_exclude_filters = 3 [json_name = "frontmatterKeyExcludeFilters"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the frontmatterKeyExcludeFilters at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFrontmatterKeyExcludeFiltersBytes(int index) {
      return com.google.protobuf.ByteString.copyFromUtf8(
          frontmatterKeyExcludeFilters_.get(index));
    }
    private void ensureFrontmatterKeyExcludeFiltersIsMutable() {
      com.google.protobuf.Internal.ProtobufList<java.lang.String> tmp =
          frontmatterKeyExcludeFilters_;  if (!tmp.isModifiable()) {
        frontmatterKeyExcludeFilters_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }
    /**
     * <pre>
     * Optional: filter OUT results that have ANY of these frontmatter keys
     * </pre>
     *
     * <code>repeated string frontmatter_key_exclude_filters = 3 [json_name = "frontmatterKeyExcludeFilters"];</code>
     * @param index The index to set the value at.
     * @param value The frontmatterKeyExcludeFilters to set.
     */
    private void setFrontmatterKeyExcludeFilters(
        int index, java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  ensureFrontmatterKeyExcludeFiltersIsMutable();
      frontmatterKeyExcludeFilters_.set(index, value);
    }
    /**
     * <pre>
     * Optional: filter OUT results that have ANY of these frontmatter keys
     * </pre>
     *
     * <code>repeated string frontmatter_key_exclude_filters = 3 [json_name = "frontmatterKeyExcludeFilters"];</code>
     * @param value The frontmatterKeyExcludeFilters to add.
     */
    private void addFrontmatterKeyExcludeFilters(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  ensureFrontmatterKeyExcludeFiltersIsMutable();
      frontmatterKeyExcludeFilters_.add(value);
    }
    /**
     * <pre>
     * Optional: filter OUT results that have ANY of these frontmatter keys
     * </pre>
     *
     * <code>repeated string frontmatter_key_exclude_filters = 3 [json_name = "frontmatterKeyExcludeFilters"];</code>
     * @param values The frontmatterKeyExcludeFilters to add.
     */
    private void addAllFrontmatterKeyExcludeFilters(
        java.lang.Iterable<java.lang.String> values) {
      ensureFrontmatterKeyExcludeFiltersIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, frontmatterKeyExcludeFilters_);
    }
    /**
     * <pre>
     * Optional: filter OUT results that have ANY of these frontmatter keys
     * </pre>
     *
     * <code>repeated string frontmatter_key_exclude_filters = 3 [json_name = "frontmatterKeyExcludeFilters"];</code>
     */
    private void clearFrontmatterKeyExcludeFilters() {
      frontmatterKeyExcludeFilters_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }
    /**
     * <pre>
     * Optional: filter OUT results that have ANY of these frontmatter keys
     * </pre>
     *
     * <code>repeated string frontmatter_key_exclude_filters = 3 [json_name = "frontmatterKeyExcludeFilters"];</code>
     * @param value The bytes of the frontmatterKeyExcludeFilters to add.
     */
    private void addFrontmatterKeyExcludeFiltersBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      ensureFrontmatterKeyExcludeFiltersIsMutable();
      frontmatterKeyExcludeFilters_.add(value.toStringUtf8());
    }

    public static api.v1.Search.SearchContentRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.v1.Search.SearchContentRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.v1.Search.SearchContentRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.v1.Search.SearchContentRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.v1.Search.SearchContentRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.v1.Search.SearchContentRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.v1.Search.SearchContentRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.v1.Search.SearchContentRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static api.v1.Search.SearchContentRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static api.v1.Search.SearchContentRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static api.v1.Search.SearchContentRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.v1.Search.SearchContentRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(api.v1.Search.SearchContentRequest prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * The request message for searching content.
     * </pre>
     *
     * Protobuf type {@code api.v1.SearchContentRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          api.v1.Search.SearchContentRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:api.v1.SearchContentRequest)
        api.v1.Search.SearchContentRequestOrBuilder {
      // Construct using api.v1.Search.SearchContentRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string query = 1 [json_name = "query"];</code>
       * @return The query.
       */
      @java.lang.Override
      public java.lang.String getQuery() {
        return instance.getQuery();
      }
      /**
       * <code>string query = 1 [json_name = "query"];</code>
       * @return The bytes for query.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getQueryBytes() {
        return instance.getQueryBytes();
      }
      /**
       * <code>string query = 1 [json_name = "query"];</code>
       * @param value The query to set.
       * @return This builder for chaining.
       */
      public Builder setQuery(
          java.lang.String value) {
        copyOnWrite();
        instance.setQuery(value);
        return this;
      }
      /**
       * <code>string query = 1 [json_name = "query"];</code>
       * @return This builder for chaining.
       */
      public Builder clearQuery() {
        copyOnWrite();
        instance.clearQuery();
        return this;
      }
      /**
       * <code>string query = 1 [json_name = "query"];</code>
       * @param value The bytes for query to set.
       * @return This builder for chaining.
       */
      public Builder setQueryBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setQueryBytes(value);
        return this;
      }

      /**
       * <pre>
       * Optional: filter results to only pages that have ALL of these frontmatter keys
       * </pre>
       *
       * <code>repeated string frontmatter_key_include_filters = 2 [json_name = "frontmatterKeyIncludeFilters"];</code>
       * @return A list containing the frontmatterKeyIncludeFilters.
       */
      @java.lang.Override
      public java.util.List<java.lang.String>
          getFrontmatterKeyIncludeFiltersList() {
        return java.util.Collections.unmodifiableList(
            instance.getFrontmatterKeyIncludeFiltersList());
      }
      /**
       * <pre>
       * Optional: filter results to only pages that have ALL of these frontmatter keys
       * </pre>
       *
       * <code>repeated string frontmatter_key_include_filters = 2 [json_name = "frontmatterKeyIncludeFilters"];</code>
       * @return The count of frontmatterKeyIncludeFilters.
       */
      @java.lang.Override
      public int getFrontmatterKeyIncludeFiltersCount() {
        return instance.getFrontmatterKeyIncludeFiltersCount();
      }
      /**
       * <pre>
       * Optional: filter results to only pages that have ALL of these frontmatter keys
       * </pre>
       *
       * <code>repeated string frontmatter_key_include_filters = 2 [json_name = "frontmatterKeyIncludeFilters"];</code>
       * @param index The index of the element to return.
       * @return The frontmatterKeyIncludeFilters at the given index.
       */
      @java.lang.Override
      public java.lang.String getFrontmatterKeyIncludeFilters(int index) {
        return instance.getFrontmatterKeyIncludeFilters(index);
      }
      /**
       * <pre>
       * Optional: filter results to only pages that have ALL of these frontmatter keys
       * </pre>
       *
       * <code>repeated string frontmatter_key_include_filters = 2 [json_name = "frontmatterKeyIncludeFilters"];</code>
       * @param index The index of the value to return.
       * @return The bytes of the frontmatterKeyIncludeFilters at the given index.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getFrontmatterKeyIncludeFiltersBytes(int index) {
        return instance.getFrontmatterKeyIncludeFiltersBytes(index);
      }
      /**
       * <pre>
       * Optional: filter results to only pages that have ALL of these frontmatter keys
       * </pre>
       *
       * <code>repeated string frontmatter_key_include_filters = 2 [json_name = "frontmatterKeyIncludeFilters"];</code>
       * @param index The index to set the value at.
       * @param value The frontmatterKeyIncludeFilters to set.
       * @return This builder for chaining.
       */
      public Builder setFrontmatterKeyIncludeFilters(
          int index, java.lang.String value) {
        copyOnWrite();
        instance.setFrontmatterKeyIncludeFilters(index, value);
        return this;
      }
      /**
       * <pre>
       * Optional: filter results to only pages that have ALL of these frontmatter keys
       * </pre>
       *
       * <code>repeated string frontmatter_key_include_filters = 2 [json_name = "frontmatterKeyIncludeFilters"];</code>
       * @param value The frontmatterKeyIncludeFilters to add.
       * @return This builder for chaining.
       */
      public Builder addFrontmatterKeyIncludeFilters(
          java.lang.String value) {
        copyOnWrite();
        instance.addFrontmatterKeyIncludeFilters(value);
        return this;
      }
      /**
       * <pre>
       * Optional: filter results to only pages that have ALL of these frontmatter keys
       * </pre>
       *
       * <code>repeated string frontmatter_key_include_filters = 2 [json_name = "frontmatterKeyIncludeFilters"];</code>
       * @param values The frontmatterKeyIncludeFilters to add.
       * @return This builder for chaining.
       */
      public Builder addAllFrontmatterKeyIncludeFilters(
          java.lang.Iterable<java.lang.String> values) {
        copyOnWrite();
        instance.addAllFrontmatterKeyIncludeFilters(values);
        return this;
      }
      /**
       * <pre>
       * Optional: filter results to only pages that have ALL of these frontmatter keys
       * </pre>
       *
       * <code>repeated string frontmatter_key_include_filters = 2 [json_name = "frontmatterKeyIncludeFilters"];</code>
       * @return This builder for chaining.
       */
      public Builder clearFrontmatterKeyIncludeFilters() {
        copyOnWrite();
        instance.clearFrontmatterKeyIncludeFilters();
        return this;
      }
      /**
       * <pre>
       * Optional: filter results to only pages that have ALL of these frontmatter keys
       * </pre>
       *
       * <code>repeated string frontmatter_key_include_filters = 2 [json_name = "frontmatterKeyIncludeFilters"];</code>
       * @param value The bytes of the frontmatterKeyIncludeFilters to add.
       * @return This builder for chaining.
       */
      public Builder addFrontmatterKeyIncludeFiltersBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.addFrontmatterKeyIncludeFiltersBytes(value);
        return this;
      }

      /**
       * <pre>
       * Optional: filter OUT results that have ANY of these frontmatter keys
       * </pre>
       *
       * <code>repeated string frontmatter_key_exclude_filters = 3 [json_name = "frontmatterKeyExcludeFilters"];</code>
       * @return A list containing the frontmatterKeyExcludeFilters.
       */
      @java.lang.Override
      public java.util.List<java.lang.String>
          getFrontmatterKeyExcludeFiltersList() {
        return java.util.Collections.unmodifiableList(
            instance.getFrontmatterKeyExcludeFiltersList());
      }
      /**
       * <pre>
       * Optional: filter OUT results that have ANY of these frontmatter keys
       * </pre>
       *
       * <code>repeated string frontmatter_key_exclude_filters = 3 [json_name = "frontmatterKeyExcludeFilters"];</code>
       * @return The count of frontmatterKeyExcludeFilters.
       */
      @java.lang.Override
      public int getFrontmatterKeyExcludeFiltersCount() {
        return instance.getFrontmatterKeyExcludeFiltersCount();
      }
      /**
       * <pre>
       * Optional: filter OUT results that have ANY of these frontmatter keys
       * </pre>
       *
       * <code>repeated string frontmatter_key_exclude_filters = 3 [json_name = "frontmatterKeyExcludeFilters"];</code>
       * @param index The index of the element to return.
       * @return The frontmatterKeyExcludeFilters at the given index.
       */
      @java.lang.Override
      public java.lang.String getFrontmatterKeyExcludeFilters(int index) {
        return instance.getFrontmatterKeyExcludeFilters(index);
      }
      /**
       * <pre>
       * Optional: filter OUT results that have ANY of these frontmatter keys
       * </pre>
       *
       * <code>repeated string frontmatter_key_exclude_filters = 3 [json_name = "frontmatterKeyExcludeFilters"];</code>
       * @param index The index of the value to return.
       * @return The bytes of the frontmatterKeyExcludeFilters at the given index.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getFrontmatterKeyExcludeFiltersBytes(int index) {
        return instance.getFrontmatterKeyExcludeFiltersBytes(index);
      }
      /**
       * <pre>
       * Optional: filter OUT results that have ANY of these frontmatter keys
       * </pre>
       *
       * <code>repeated string frontmatter_key_exclude_filters = 3 [json_name = "frontmatterKeyExcludeFilters"];</code>
       * @param index The index to set the value at.
       * @param value The frontmatterKeyExcludeFilters to set.
       * @return This builder for chaining.
       */
      public Builder setFrontmatterKeyExcludeFilters(
          int index, java.lang.String value) {
        copyOnWrite();
        instance.setFrontmatterKeyExcludeFilters(index, value);
        return this;
      }
      /**
       * <pre>
       * Optional: filter OUT results that have ANY of these frontmatter keys
       * </pre>
       *
       * <code>repeated string frontmatter_key_exclude_filters = 3 [json_name = "frontmatterKeyExcludeFilters"];</code>
       * @param value The frontmatterKeyExcludeFilters to add.
       * @return This builder for chaining.
       */
      public Builder addFrontmatterKeyExcludeFilters(
          java.lang.String value) {
        copyOnWrite();
        instance.addFrontmatterKeyExcludeFilters(value);
        return this;
      }
      /**
       * <pre>
       * Optional: filter OUT results that have ANY of these frontmatter keys
       * </pre>
       *
       * <code>repeated string frontmatter_key_exclude_filters = 3 [json_name = "frontmatterKeyExcludeFilters"];</code>
       * @param values The frontmatterKeyExcludeFilters to add.
       * @return This builder for chaining.
       */
      public Builder addAllFrontmatterKeyExcludeFilters(
          java.lang.Iterable<java.lang.String> values) {
        copyOnWrite();
        instance.addAllFrontmatterKeyExcludeFilters(values);
        return this;
      }
      /**
       * <pre>
       * Optional: filter OUT results that have ANY of these frontmatter keys
       * </pre>
       *
       * <code>repeated string frontmatter_key_exclude_filters = 3 [json_name = "frontmatterKeyExcludeFilters"];</code>
       * @return This builder for chaining.
       */
      public Builder clearFrontmatterKeyExcludeFilters() {
        copyOnWrite();
        instance.clearFrontmatterKeyExcludeFilters();
        return this;
      }
      /**
       * <pre>
       * Optional: filter OUT results that have ANY of these frontmatter keys
       * </pre>
       *
       * <code>repeated string frontmatter_key_exclude_filters = 3 [json_name = "frontmatterKeyExcludeFilters"];</code>
       * @param value The bytes of the frontmatterKeyExcludeFilters to add.
       * @return This builder for chaining.
       */
      public Builder addFrontmatterKeyExcludeFiltersBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.addFrontmatterKeyExcludeFiltersBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:api.v1.SearchContentRequest)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new api.v1.Search.SearchContentRequest();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "query_",
              "frontmatterKeyIncludeFilters_",
              "frontmatterKeyExcludeFilters_",
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0002\u0000\u0001\u0208\u0002\u021a" +
                "\u0003\u021a";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<api.v1.Search.SearchContentRequest> parser = PARSER;
          if (parser == null) {
            synchronized (api.v1.Search.SearchContentRequest.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<api.v1.Search.SearchContentRequest>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:api.v1.SearchContentRequest)
    private static final api.v1.Search.SearchContentRequest DEFAULT_INSTANCE;
    static {
      SearchContentRequest defaultInstance = new SearchContentRequest();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        SearchContentRequest.class, defaultInstance);
    }

    public static api.v1.Search.SearchContentRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<SearchContentRequest> PARSER;

    public static com.google.protobuf.Parser<SearchContentRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface SearchContentResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.v1.SearchContentResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .api.v1.SearchResult results = 1 [json_name = "results"];</code>
     */
    java.util.List<api.v1.Search.SearchResult> 
        getResultsList();
    /**
     * <code>repeated .api.v1.SearchResult results = 1 [json_name = "results"];</code>
     */
    api.v1.Search.SearchResult getResults(int index);
    /**
     * <code>repeated .api.v1.SearchResult results = 1 [json_name = "results"];</code>
     */
    int getResultsCount();
  }
  /**
   * <pre>
   * The response message containing search results.
   * </pre>
   *
   * Protobuf type {@code api.v1.SearchContentResponse}
   */
  public  static final class SearchContentResponse extends
      com.google.protobuf.GeneratedMessageLite<
          SearchContentResponse, SearchContentResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:api.v1.SearchContentResponse)
      SearchContentResponseOrBuilder {
    private SearchContentResponse() {
      results_ = emptyProtobufList();
    }
    public static final int RESULTS_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<api.v1.Search.SearchResult> results_;
    /**
     * <code>repeated .api.v1.SearchResult results = 1 [json_name = "results"];</code>
     */
    @java.lang.Override
    public java.util.List<api.v1.Search.SearchResult> getResultsList() {
      return results_;
    }
    /**
     * <code>repeated .api.v1.SearchResult results = 1 [json_name = "results"];</code>
     */
    public java.util.List<? extends api.v1.Search.SearchResultOrBuilder> 
        getResultsOrBuilderList() {
      return results_;
    }
    /**
     * <code>repeated .api.v1.SearchResult results = 1 [json_name = "results"];</code>
     */
    @java.lang.Override
    public int getResultsCount() {
      return results_.size();
    }
    /**
     * <code>repeated .api.v1.SearchResult results = 1 [json_name = "results"];</code>
     */
    @java.lang.Override
    public api.v1.Search.SearchResult getResults(int index) {
      return results_.get(index);
    }
    /**
     * <code>repeated .api.v1.SearchResult results = 1 [json_name = "results"];</code>
     */
    public api.v1.Search.SearchResultOrBuilder getResultsOrBuilder(
        int index) {
      return results_.get(index);
    }
    private void ensureResultsIsMutable() {
      com.google.protobuf.Internal.ProtobufList<api.v1.Search.SearchResult> tmp = results_;
      if (!tmp.isModifiable()) {
        results_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .api.v1.SearchResult results = 1 [json_name = "results"];</code>
     */
    private void setResults(
        int index, api.v1.Search.SearchResult value) {
      value.getClass();
  ensureResultsIsMutable();
      results_.set(index, value);
    }
    /**
     * <code>repeated .api.v1.SearchResult results = 1 [json_name = "results"];</code>
     */
    private void addResults(api.v1.Search.SearchResult value) {
      value.getClass();
  ensureResultsIsMutable();
      results_.add(value);
    }
    /**
     * <code>repeated .api.v1.SearchResult results = 1 [json_name = "results"];</code>
     */
    private void addResults(
        int index, api.v1.Search.SearchResult value) {
      value.getClass();
  ensureResultsIsMutable();
      results_.add(index, value);
    }
    /**
     * <code>repeated .api.v1.SearchResult results = 1 [json_name = "results"];</code>
     */
    private void addAllResults(
        java.lang.Iterable<? extends api.v1.Search.SearchResult> values) {
      ensureResultsIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, results_);
    }
    /**
     * <code>repeated .api.v1.SearchResult results = 1 [json_name = "results"];</code>
     */
    private void clearResults() {
      results_ = emptyProtobufList();
    }
    /**
     * <code>repeated .api.v1.SearchResult results = 1 [json_name = "results"];</code>
     */
    private void removeResults(int index) {
      ensureResultsIsMutable();
      results_.remove(index);
    }

    public static api.v1.Search.SearchContentResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.v1.Search.SearchContentResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.v1.Search.SearchContentResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.v1.Search.SearchContentResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.v1.Search.SearchContentResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.v1.Search.SearchContentResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.v1.Search.SearchContentResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.v1.Search.SearchContentResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static api.v1.Search.SearchContentResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static api.v1.Search.SearchContentResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static api.v1.Search.SearchContentResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.v1.Search.SearchContentResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(api.v1.Search.SearchContentResponse prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * The response message containing search results.
     * </pre>
     *
     * Protobuf type {@code api.v1.SearchContentResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          api.v1.Search.SearchContentResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:api.v1.SearchContentResponse)
        api.v1.Search.SearchContentResponseOrBuilder {
      // Construct using api.v1.Search.SearchContentResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated .api.v1.SearchResult results = 1 [json_name = "results"];</code>
       */
      @java.lang.Override
      public java.util.List<api.v1.Search.SearchResult> getResultsList() {
        return java.util.Collections.unmodifiableList(
            instance.getResultsList());
      }
      /**
       * <code>repeated .api.v1.SearchResult results = 1 [json_name = "results"];</code>
       */
      @java.lang.Override
      public int getResultsCount() {
        return instance.getResultsCount();
      }/**
       * <code>repeated .api.v1.SearchResult results = 1 [json_name = "results"];</code>
       */
      @java.lang.Override
      public api.v1.Search.SearchResult getResults(int index) {
        return instance.getResults(index);
      }
      /**
       * <code>repeated .api.v1.SearchResult results = 1 [json_name = "results"];</code>
       */
      public Builder setResults(
          int index, api.v1.Search.SearchResult value) {
        copyOnWrite();
        instance.setResults(index, value);
        return this;
      }
      /**
       * <code>repeated .api.v1.SearchResult results = 1 [json_name = "results"];</code>
       */
      public Builder setResults(
          int index, api.v1.Search.SearchResult.Builder builderForValue) {
        copyOnWrite();
        instance.setResults(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .api.v1.SearchResult results = 1 [json_name = "results"];</code>
       */
      public Builder addResults(api.v1.Search.SearchResult value) {
        copyOnWrite();
        instance.addResults(value);
        return this;
      }
      /**
       * <code>repeated .api.v1.SearchResult results = 1 [json_name = "results"];</code>
       */
      public Builder addResults(
          int index, api.v1.Search.SearchResult value) {
        copyOnWrite();
        instance.addResults(index, value);
        return this;
      }
      /**
       * <code>repeated .api.v1.SearchResult results = 1 [json_name = "results"];</code>
       */
      public Builder addResults(
          api.v1.Search.SearchResult.Builder builderForValue) {
        copyOnWrite();
        instance.addResults(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .api.v1.SearchResult results = 1 [json_name = "results"];</code>
       */
      public Builder addResults(
          int index, api.v1.Search.SearchResult.Builder builderForValue) {
        copyOnWrite();
        instance.addResults(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .api.v1.SearchResult results = 1 [json_name = "results"];</code>
       */
      public Builder addAllResults(
          java.lang.Iterable<? extends api.v1.Search.SearchResult> values) {
        copyOnWrite();
        instance.addAllResults(values);
        return this;
      }
      /**
       * <code>repeated .api.v1.SearchResult results = 1 [json_name = "results"];</code>
       */
      public Builder clearResults() {
        copyOnWrite();
        instance.clearResults();
        return this;
      }
      /**
       * <code>repeated .api.v1.SearchResult results = 1 [json_name = "results"];</code>
       */
      public Builder removeResults(int index) {
        copyOnWrite();
        instance.removeResults(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:api.v1.SearchContentResponse)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new api.v1.Search.SearchContentResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "results_",
              api.v1.Search.SearchResult.class,
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u001b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<api.v1.Search.SearchContentResponse> parser = PARSER;
          if (parser == null) {
            synchronized (api.v1.Search.SearchContentResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<api.v1.Search.SearchContentResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:api.v1.SearchContentResponse)
    private static final api.v1.Search.SearchContentResponse DEFAULT_INSTANCE;
    static {
      SearchContentResponse defaultInstance = new SearchContentResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        SearchContentResponse.class, defaultInstance);
    }

    public static api.v1.Search.SearchContentResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<SearchContentResponse> PARSER;

    public static com.google.protobuf.Parser<SearchContentResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface SearchResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.v1.SearchResult)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * Page identifier
     * </pre>
     *
     * <code>string identifier = 1 [json_name = "identifier"];</code>
     * @return The identifier.
     */
    java.lang.String getIdentifier();
    /**
     * <pre>
     * Page identifier
     * </pre>
     *
     * <code>string identifier = 1 [json_name = "identifier"];</code>
     * @return The bytes for identifier.
     */
    com.google.protobuf.ByteString
        getIdentifierBytes();

    /**
     * <pre>
     * Page title
     * </pre>
     *
     * <code>string title = 2 [json_name = "title"];</code>
     * @return The title.
     */
    java.lang.String getTitle();
    /**
     * <pre>
     * Page title
     * </pre>
     *
     * <code>string title = 2 [json_name = "title"];</code>
     * @return The bytes for title.
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <pre>
     * Plain text fragment (no HTML)
     * </pre>
     *
     * <code>string fragment = 3 [json_name = "fragment"];</code>
     * @return The fragment.
     */
    java.lang.String getFragment();
    /**
     * <pre>
     * Plain text fragment (no HTML)
     * </pre>
     *
     * <code>string fragment = 3 [json_name = "fragment"];</code>
     * @return The bytes for fragment.
     */
    com.google.protobuf.ByteString
        getFragmentBytes();

    /**
     * <pre>
     * Highlight positions
     * </pre>
     *
     * <code>repeated .api.v1.HighlightSpan highlights = 4 [json_name = "highlights"];</code>
     */
    java.util.List<api.v1.Search.HighlightSpan> 
        getHighlightsList();
    /**
     * <pre>
     * Highlight positions
     * </pre>
     *
     * <code>repeated .api.v1.HighlightSpan highlights = 4 [json_name = "highlights"];</code>
     */
    api.v1.Search.HighlightSpan getHighlights(int index);
    /**
     * <pre>
     * Highlight positions
     * </pre>
     *
     * <code>repeated .api.v1.HighlightSpan highlights = 4 [json_name = "highlights"];</code>
     */
    int getHighlightsCount();
  }
  /**
   * <pre>
   * A search result item.
   * </pre>
   *
   * Protobuf type {@code api.v1.SearchResult}
   */
  public  static final class SearchResult extends
      com.google.protobuf.GeneratedMessageLite<
          SearchResult, SearchResult.Builder> implements
      // @@protoc_insertion_point(message_implements:api.v1.SearchResult)
      SearchResultOrBuilder {
    private SearchResult() {
      identifier_ = "";
      title_ = "";
      fragment_ = "";
      highlights_ = emptyProtobufList();
    }
    public static final int IDENTIFIER_FIELD_NUMBER = 1;
    private java.lang.String identifier_;
    /**
     * <pre>
     * Page identifier
     * </pre>
     *
     * <code>string identifier = 1 [json_name = "identifier"];</code>
     * @return The identifier.
     */
    @java.lang.Override
    public java.lang.String getIdentifier() {
      return identifier_;
    }
    /**
     * <pre>
     * Page identifier
     * </pre>
     *
     * <code>string identifier = 1 [json_name = "identifier"];</code>
     * @return The bytes for identifier.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdentifierBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(identifier_);
    }
    /**
     * <pre>
     * Page identifier
     * </pre>
     *
     * <code>string identifier = 1 [json_name = "identifier"];</code>
     * @param value The identifier to set.
     */
    private void setIdentifier(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      identifier_ = value;
    }
    /**
     * <pre>
     * Page identifier
     * </pre>
     *
     * <code>string identifier = 1 [json_name = "identifier"];</code>
     */
    private void clearIdentifier() {

      identifier_ = getDefaultInstance().getIdentifier();
    }
    /**
     * <pre>
     * Page identifier
     * </pre>
     *
     * <code>string identifier = 1 [json_name = "identifier"];</code>
     * @param value The bytes for identifier to set.
     */
    private void setIdentifierBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      identifier_ = value.toStringUtf8();

    }

    public static final int TITLE_FIELD_NUMBER = 2;
    private java.lang.String title_;
    /**
     * <pre>
     * Page title
     * </pre>
     *
     * <code>string title = 2 [json_name = "title"];</code>
     * @return The title.
     */
    @java.lang.Override
    public java.lang.String getTitle() {
      return title_;
    }
    /**
     * <pre>
     * Page title
     * </pre>
     *
     * <code>string title = 2 [json_name = "title"];</code>
     * @return The bytes for title.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(title_);
    }
    /**
     * <pre>
     * Page title
     * </pre>
     *
     * <code>string title = 2 [json_name = "title"];</code>
     * @param value The title to set.
     */
    private void setTitle(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      title_ = value;
    }
    /**
     * <pre>
     * Page title
     * </pre>
     *
     * <code>string title = 2 [json_name = "title"];</code>
     */
    private void clearTitle() {

      title_ = getDefaultInstance().getTitle();
    }
    /**
     * <pre>
     * Page title
     * </pre>
     *
     * <code>string title = 2 [json_name = "title"];</code>
     * @param value The bytes for title to set.
     */
    private void setTitleBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      title_ = value.toStringUtf8();

    }

    public static final int FRAGMENT_FIELD_NUMBER = 3;
    private java.lang.String fragment_;
    /**
     * <pre>
     * Plain text fragment (no HTML)
     * </pre>
     *
     * <code>string fragment = 3 [json_name = "fragment"];</code>
     * @return The fragment.
     */
    @java.lang.Override
    public java.lang.String getFragment() {
      return fragment_;
    }
    /**
     * <pre>
     * Plain text fragment (no HTML)
     * </pre>
     *
     * <code>string fragment = 3 [json_name = "fragment"];</code>
     * @return The bytes for fragment.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFragmentBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(fragment_);
    }
    /**
     * <pre>
     * Plain text fragment (no HTML)
     * </pre>
     *
     * <code>string fragment = 3 [json_name = "fragment"];</code>
     * @param value The fragment to set.
     */
    private void setFragment(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      fragment_ = value;
    }
    /**
     * <pre>
     * Plain text fragment (no HTML)
     * </pre>
     *
     * <code>string fragment = 3 [json_name = "fragment"];</code>
     */
    private void clearFragment() {

      fragment_ = getDefaultInstance().getFragment();
    }
    /**
     * <pre>
     * Plain text fragment (no HTML)
     * </pre>
     *
     * <code>string fragment = 3 [json_name = "fragment"];</code>
     * @param value The bytes for fragment to set.
     */
    private void setFragmentBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      fragment_ = value.toStringUtf8();

    }

    public static final int HIGHLIGHTS_FIELD_NUMBER = 4;
    private com.google.protobuf.Internal.ProtobufList<api.v1.Search.HighlightSpan> highlights_;
    /**
     * <pre>
     * Highlight positions
     * </pre>
     *
     * <code>repeated .api.v1.HighlightSpan highlights = 4 [json_name = "highlights"];</code>
     */
    @java.lang.Override
    public java.util.List<api.v1.Search.HighlightSpan> getHighlightsList() {
      return highlights_;
    }
    /**
     * <pre>
     * Highlight positions
     * </pre>
     *
     * <code>repeated .api.v1.HighlightSpan highlights = 4 [json_name = "highlights"];</code>
     */
    public java.util.List<? extends api.v1.Search.HighlightSpanOrBuilder> 
        getHighlightsOrBuilderList() {
      return highlights_;
    }
    /**
     * <pre>
     * Highlight positions
     * </pre>
     *
     * <code>repeated .api.v1.HighlightSpan highlights = 4 [json_name = "highlights"];</code>
     */
    @java.lang.Override
    public int getHighlightsCount() {
      return highlights_.size();
    }
    /**
     * <pre>
     * Highlight positions
     * </pre>
     *
     * <code>repeated .api.v1.HighlightSpan highlights = 4 [json_name = "highlights"];</code>
     */
    @java.lang.Override
    public api.v1.Search.HighlightSpan getHighlights(int index) {
      return highlights_.get(index);
    }
    /**
     * <pre>
     * Highlight positions
     * </pre>
     *
     * <code>repeated .api.v1.HighlightSpan highlights = 4 [json_name = "highlights"];</code>
     */
    public api.v1.Search.HighlightSpanOrBuilder getHighlightsOrBuilder(
        int index) {
      return highlights_.get(index);
    }
    private void ensureHighlightsIsMutable() {
      com.google.protobuf.Internal.ProtobufList<api.v1.Search.HighlightSpan> tmp = highlights_;
      if (!tmp.isModifiable()) {
        highlights_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <pre>
     * Highlight positions
     * </pre>
     *
     * <code>repeated .api.v1.HighlightSpan highlights = 4 [json_name = "highlights"];</code>
     */
    private void setHighlights(
        int index, api.v1.Search.HighlightSpan value) {
      value.getClass();
  ensureHighlightsIsMutable();
      highlights_.set(index, value);
    }
    /**
     * <pre>
     * Highlight positions
     * </pre>
     *
     * <code>repeated .api.v1.HighlightSpan highlights = 4 [json_name = "highlights"];</code>
     */
    private void addHighlights(api.v1.Search.HighlightSpan value) {
      value.getClass();
  ensureHighlightsIsMutable();
      highlights_.add(value);
    }
    /**
     * <pre>
     * Highlight positions
     * </pre>
     *
     * <code>repeated .api.v1.HighlightSpan highlights = 4 [json_name = "highlights"];</code>
     */
    private void addHighlights(
        int index, api.v1.Search.HighlightSpan value) {
      value.getClass();
  ensureHighlightsIsMutable();
      highlights_.add(index, value);
    }
    /**
     * <pre>
     * Highlight positions
     * </pre>
     *
     * <code>repeated .api.v1.HighlightSpan highlights = 4 [json_name = "highlights"];</code>
     */
    private void addAllHighlights(
        java.lang.Iterable<? extends api.v1.Search.HighlightSpan> values) {
      ensureHighlightsIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, highlights_);
    }
    /**
     * <pre>
     * Highlight positions
     * </pre>
     *
     * <code>repeated .api.v1.HighlightSpan highlights = 4 [json_name = "highlights"];</code>
     */
    private void clearHighlights() {
      highlights_ = emptyProtobufList();
    }
    /**
     * <pre>
     * Highlight positions
     * </pre>
     *
     * <code>repeated .api.v1.HighlightSpan highlights = 4 [json_name = "highlights"];</code>
     */
    private void removeHighlights(int index) {
      ensureHighlightsIsMutable();
      highlights_.remove(index);
    }

    public static api.v1.Search.SearchResult parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.v1.Search.SearchResult parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.v1.Search.SearchResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.v1.Search.SearchResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.v1.Search.SearchResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.v1.Search.SearchResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.v1.Search.SearchResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.v1.Search.SearchResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static api.v1.Search.SearchResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static api.v1.Search.SearchResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static api.v1.Search.SearchResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.v1.Search.SearchResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(api.v1.Search.SearchResult prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * A search result item.
     * </pre>
     *
     * Protobuf type {@code api.v1.SearchResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          api.v1.Search.SearchResult, Builder> implements
        // @@protoc_insertion_point(builder_implements:api.v1.SearchResult)
        api.v1.Search.SearchResultOrBuilder {
      // Construct using api.v1.Search.SearchResult.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * Page identifier
       * </pre>
       *
       * <code>string identifier = 1 [json_name = "identifier"];</code>
       * @return The identifier.
       */
      @java.lang.Override
      public java.lang.String getIdentifier() {
        return instance.getIdentifier();
      }
      /**
       * <pre>
       * Page identifier
       * </pre>
       *
       * <code>string identifier = 1 [json_name = "identifier"];</code>
       * @return The bytes for identifier.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getIdentifierBytes() {
        return instance.getIdentifierBytes();
      }
      /**
       * <pre>
       * Page identifier
       * </pre>
       *
       * <code>string identifier = 1 [json_name = "identifier"];</code>
       * @param value The identifier to set.
       * @return This builder for chaining.
       */
      public Builder setIdentifier(
          java.lang.String value) {
        copyOnWrite();
        instance.setIdentifier(value);
        return this;
      }
      /**
       * <pre>
       * Page identifier
       * </pre>
       *
       * <code>string identifier = 1 [json_name = "identifier"];</code>
       * @return This builder for chaining.
       */
      public Builder clearIdentifier() {
        copyOnWrite();
        instance.clearIdentifier();
        return this;
      }
      /**
       * <pre>
       * Page identifier
       * </pre>
       *
       * <code>string identifier = 1 [json_name = "identifier"];</code>
       * @param value The bytes for identifier to set.
       * @return This builder for chaining.
       */
      public Builder setIdentifierBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setIdentifierBytes(value);
        return this;
      }

      /**
       * <pre>
       * Page title
       * </pre>
       *
       * <code>string title = 2 [json_name = "title"];</code>
       * @return The title.
       */
      @java.lang.Override
      public java.lang.String getTitle() {
        return instance.getTitle();
      }
      /**
       * <pre>
       * Page title
       * </pre>
       *
       * <code>string title = 2 [json_name = "title"];</code>
       * @return The bytes for title.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getTitleBytes() {
        return instance.getTitleBytes();
      }
      /**
       * <pre>
       * Page title
       * </pre>
       *
       * <code>string title = 2 [json_name = "title"];</code>
       * @param value The title to set.
       * @return This builder for chaining.
       */
      public Builder setTitle(
          java.lang.String value) {
        copyOnWrite();
        instance.setTitle(value);
        return this;
      }
      /**
       * <pre>
       * Page title
       * </pre>
       *
       * <code>string title = 2 [json_name = "title"];</code>
       * @return This builder for chaining.
       */
      public Builder clearTitle() {
        copyOnWrite();
        instance.clearTitle();
        return this;
      }
      /**
       * <pre>
       * Page title
       * </pre>
       *
       * <code>string title = 2 [json_name = "title"];</code>
       * @param value The bytes for title to set.
       * @return This builder for chaining.
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setTitleBytes(value);
        return this;
      }

      /**
       * <pre>
       * Plain text fragment (no HTML)
       * </pre>
       *
       * <code>string fragment = 3 [json_name = "fragment"];</code>
       * @return The fragment.
       */
      @java.lang.Override
      public java.lang.String getFragment() {
        return instance.getFragment();
      }
      /**
       * <pre>
       * Plain text fragment (no HTML)
       * </pre>
       *
       * <code>string fragment = 3 [json_name = "fragment"];</code>
       * @return The bytes for fragment.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getFragmentBytes() {
        return instance.getFragmentBytes();
      }
      /**
       * <pre>
       * Plain text fragment (no HTML)
       * </pre>
       *
       * <code>string fragment = 3 [json_name = "fragment"];</code>
       * @param value The fragment to set.
       * @return This builder for chaining.
       */
      public Builder setFragment(
          java.lang.String value) {
        copyOnWrite();
        instance.setFragment(value);
        return this;
      }
      /**
       * <pre>
       * Plain text fragment (no HTML)
       * </pre>
       *
       * <code>string fragment = 3 [json_name = "fragment"];</code>
       * @return This builder for chaining.
       */
      public Builder clearFragment() {
        copyOnWrite();
        instance.clearFragment();
        return this;
      }
      /**
       * <pre>
       * Plain text fragment (no HTML)
       * </pre>
       *
       * <code>string fragment = 3 [json_name = "fragment"];</code>
       * @param value The bytes for fragment to set.
       * @return This builder for chaining.
       */
      public Builder setFragmentBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setFragmentBytes(value);
        return this;
      }

      /**
       * <pre>
       * Highlight positions
       * </pre>
       *
       * <code>repeated .api.v1.HighlightSpan highlights = 4 [json_name = "highlights"];</code>
       */
      @java.lang.Override
      public java.util.List<api.v1.Search.HighlightSpan> getHighlightsList() {
        return java.util.Collections.unmodifiableList(
            instance.getHighlightsList());
      }
      /**
       * <pre>
       * Highlight positions
       * </pre>
       *
       * <code>repeated .api.v1.HighlightSpan highlights = 4 [json_name = "highlights"];</code>
       */
      @java.lang.Override
      public int getHighlightsCount() {
        return instance.getHighlightsCount();
      }/**
       * <pre>
       * Highlight positions
       * </pre>
       *
       * <code>repeated .api.v1.HighlightSpan highlights = 4 [json_name = "highlights"];</code>
       */
      @java.lang.Override
      public api.v1.Search.HighlightSpan getHighlights(int index) {
        return instance.getHighlights(index);
      }
      /**
       * <pre>
       * Highlight positions
       * </pre>
       *
       * <code>repeated .api.v1.HighlightSpan highlights = 4 [json_name = "highlights"];</code>
       */
      public Builder setHighlights(
          int index, api.v1.Search.HighlightSpan value) {
        copyOnWrite();
        instance.setHighlights(index, value);
        return this;
      }
      /**
       * <pre>
       * Highlight positions
       * </pre>
       *
       * <code>repeated .api.v1.HighlightSpan highlights = 4 [json_name = "highlights"];</code>
       */
      public Builder setHighlights(
          int index, api.v1.Search.HighlightSpan.Builder builderForValue) {
        copyOnWrite();
        instance.setHighlights(index,
            builderForValue.build());
        return this;
      }
      /**
       * <pre>
       * Highlight positions
       * </pre>
       *
       * <code>repeated .api.v1.HighlightSpan highlights = 4 [json_name = "highlights"];</code>
       */
      public Builder addHighlights(api.v1.Search.HighlightSpan value) {
        copyOnWrite();
        instance.addHighlights(value);
        return this;
      }
      /**
       * <pre>
       * Highlight positions
       * </pre>
       *
       * <code>repeated .api.v1.HighlightSpan highlights = 4 [json_name = "highlights"];</code>
       */
      public Builder addHighlights(
          int index, api.v1.Search.HighlightSpan value) {
        copyOnWrite();
        instance.addHighlights(index, value);
        return this;
      }
      /**
       * <pre>
       * Highlight positions
       * </pre>
       *
       * <code>repeated .api.v1.HighlightSpan highlights = 4 [json_name = "highlights"];</code>
       */
      public Builder addHighlights(
          api.v1.Search.HighlightSpan.Builder builderForValue) {
        copyOnWrite();
        instance.addHighlights(builderForValue.build());
        return this;
      }
      /**
       * <pre>
       * Highlight positions
       * </pre>
       *
       * <code>repeated .api.v1.HighlightSpan highlights = 4 [json_name = "highlights"];</code>
       */
      public Builder addHighlights(
          int index, api.v1.Search.HighlightSpan.Builder builderForValue) {
        copyOnWrite();
        instance.addHighlights(index,
            builderForValue.build());
        return this;
      }
      /**
       * <pre>
       * Highlight positions
       * </pre>
       *
       * <code>repeated .api.v1.HighlightSpan highlights = 4 [json_name = "highlights"];</code>
       */
      public Builder addAllHighlights(
          java.lang.Iterable<? extends api.v1.Search.HighlightSpan> values) {
        copyOnWrite();
        instance.addAllHighlights(values);
        return this;
      }
      /**
       * <pre>
       * Highlight positions
       * </pre>
       *
       * <code>repeated .api.v1.HighlightSpan highlights = 4 [json_name = "highlights"];</code>
       */
      public Builder clearHighlights() {
        copyOnWrite();
        instance.clearHighlights();
        return this;
      }
      /**
       * <pre>
       * Highlight positions
       * </pre>
       *
       * <code>repeated .api.v1.HighlightSpan highlights = 4 [json_name = "highlights"];</code>
       */
      public Builder removeHighlights(int index) {
        copyOnWrite();
        instance.removeHighlights(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:api.v1.SearchResult)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new api.v1.Search.SearchResult();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "identifier_",
              "title_",
              "fragment_",
              "highlights_",
              api.v1.Search.HighlightSpan.class,
            };
            java.lang.String info =
                "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0001\u0000\u0001\u0208\u0002\u0208" +
                "\u0003\u0208\u0004\u001b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<api.v1.Search.SearchResult> parser = PARSER;
          if (parser == null) {
            synchronized (api.v1.Search.SearchResult.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<api.v1.Search.SearchResult>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:api.v1.SearchResult)
    private static final api.v1.Search.SearchResult DEFAULT_INSTANCE;
    static {
      SearchResult defaultInstance = new SearchResult();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        SearchResult.class, defaultInstance);
    }

    public static api.v1.Search.SearchResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<SearchResult> PARSER;

    public static com.google.protobuf.Parser<SearchResult> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface HighlightSpanOrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.v1.HighlightSpan)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * Start position in fragment
     * </pre>
     *
     * <code>int32 start = 1 [json_name = "start"];</code>
     * @return The start.
     */
    int getStart();

    /**
     * <pre>
     * End position in fragment
     * </pre>
     *
     * <code>int32 end = 2 [json_name = "end"];</code>
     * @return The end.
     */
    int getEnd();
  }
  /**
   * <pre>
   * A span of text to be highlighted.
   * </pre>
   *
   * Protobuf type {@code api.v1.HighlightSpan}
   */
  public  static final class HighlightSpan extends
      com.google.protobuf.GeneratedMessageLite<
          HighlightSpan, HighlightSpan.Builder> implements
      // @@protoc_insertion_point(message_implements:api.v1.HighlightSpan)
      HighlightSpanOrBuilder {
    private HighlightSpan() {
    }
    public static final int START_FIELD_NUMBER = 1;
    private int start_;
    /**
     * <pre>
     * Start position in fragment
     * </pre>
     *
     * <code>int32 start = 1 [json_name = "start"];</code>
     * @return The start.
     */
    @java.lang.Override
    public int getStart() {
      return start_;
    }
    /**
     * <pre>
     * Start position in fragment
     * </pre>
     *
     * <code>int32 start = 1 [json_name = "start"];</code>
     * @param value The start to set.
     */
    private void setStart(int value) {
      
      start_ = value;
    }
    /**
     * <pre>
     * Start position in fragment
     * </pre>
     *
     * <code>int32 start = 1 [json_name = "start"];</code>
     */
    private void clearStart() {

      start_ = 0;
    }

    public static final int END_FIELD_NUMBER = 2;
    private int end_;
    /**
     * <pre>
     * End position in fragment
     * </pre>
     *
     * <code>int32 end = 2 [json_name = "end"];</code>
     * @return The end.
     */
    @java.lang.Override
    public int getEnd() {
      return end_;
    }
    /**
     * <pre>
     * End position in fragment
     * </pre>
     *
     * <code>int32 end = 2 [json_name = "end"];</code>
     * @param value The end to set.
     */
    private void setEnd(int value) {
      
      end_ = value;
    }
    /**
     * <pre>
     * End position in fragment
     * </pre>
     *
     * <code>int32 end = 2 [json_name = "end"];</code>
     */
    private void clearEnd() {

      end_ = 0;
    }

    public static api.v1.Search.HighlightSpan parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.v1.Search.HighlightSpan parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.v1.Search.HighlightSpan parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.v1.Search.HighlightSpan parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.v1.Search.HighlightSpan parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.v1.Search.HighlightSpan parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.v1.Search.HighlightSpan parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.v1.Search.HighlightSpan parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static api.v1.Search.HighlightSpan parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static api.v1.Search.HighlightSpan parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static api.v1.Search.HighlightSpan parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.v1.Search.HighlightSpan parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(api.v1.Search.HighlightSpan prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * A span of text to be highlighted.
     * </pre>
     *
     * Protobuf type {@code api.v1.HighlightSpan}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          api.v1.Search.HighlightSpan, Builder> implements
        // @@protoc_insertion_point(builder_implements:api.v1.HighlightSpan)
        api.v1.Search.HighlightSpanOrBuilder {
      // Construct using api.v1.Search.HighlightSpan.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * Start position in fragment
       * </pre>
       *
       * <code>int32 start = 1 [json_name = "start"];</code>
       * @return The start.
       */
      @java.lang.Override
      public int getStart() {
        return instance.getStart();
      }
      /**
       * <pre>
       * Start position in fragment
       * </pre>
       *
       * <code>int32 start = 1 [json_name = "start"];</code>
       * @param value The start to set.
       * @return This builder for chaining.
       */
      public Builder setStart(int value) {
        copyOnWrite();
        instance.setStart(value);
        return this;
      }
      /**
       * <pre>
       * Start position in fragment
       * </pre>
       *
       * <code>int32 start = 1 [json_name = "start"];</code>
       * @return This builder for chaining.
       */
      public Builder clearStart() {
        copyOnWrite();
        instance.clearStart();
        return this;
      }

      /**
       * <pre>
       * End position in fragment
       * </pre>
       *
       * <code>int32 end = 2 [json_name = "end"];</code>
       * @return The end.
       */
      @java.lang.Override
      public int getEnd() {
        return instance.getEnd();
      }
      /**
       * <pre>
       * End position in fragment
       * </pre>
       *
       * <code>int32 end = 2 [json_name = "end"];</code>
       * @param value The end to set.
       * @return This builder for chaining.
       */
      public Builder setEnd(int value) {
        copyOnWrite();
        instance.setEnd(value);
        return this;
      }
      /**
       * <pre>
       * End position in fragment
       * </pre>
       *
       * <code>int32 end = 2 [json_name = "end"];</code>
       * @return This builder for chaining.
       */
      public Builder clearEnd() {
        copyOnWrite();
        instance.clearEnd();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:api.v1.HighlightSpan)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new api.v1.Search.HighlightSpan();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "start_",
              "end_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0004\u0002\u0004" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<api.v1.Search.HighlightSpan> parser = PARSER;
          if (parser == null) {
            synchronized (api.v1.Search.HighlightSpan.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<api.v1.Search.HighlightSpan>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:api.v1.HighlightSpan)
    private static final api.v1.Search.HighlightSpan DEFAULT_INSTANCE;
    static {
      HighlightSpan defaultInstance = new HighlightSpan();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        HighlightSpan.class, defaultInstance);
    }

    public static api.v1.Search.HighlightSpan getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<HighlightSpan> PARSER;

    public static com.google.protobuf.Parser<HighlightSpan> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
