// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/search.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package api.v1;

@kotlin.jvm.JvmName("-initializesearchContentResponse")
public inline fun searchContentResponse(block: api.v1.SearchContentResponseKt.Dsl.() -> kotlin.Unit): api.v1.Search.SearchContentResponse =
  api.v1.SearchContentResponseKt.Dsl._create(api.v1.Search.SearchContentResponse.newBuilder()).apply { block() }._build()
/**
 * ```
 * The response message containing search results.
 * ```
 *
 * Protobuf type `api.v1.SearchContentResponse`
 */
public object SearchContentResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: api.v1.Search.SearchContentResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: api.v1.Search.SearchContentResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): api.v1.Search.SearchContentResponse = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ResultsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .api.v1.SearchResult results = 1 [json_name = "results"];`
     */
     public val results: com.google.protobuf.kotlin.DslList<api.v1.Search.SearchResult, ResultsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.resultsList
      )
    /**
     * `repeated .api.v1.SearchResult results = 1 [json_name = "results"];`
     * @param value The results to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addResults")
    public fun com.google.protobuf.kotlin.DslList<api.v1.Search.SearchResult, ResultsProxy>.add(value: api.v1.Search.SearchResult) {
      _builder.addResults(value)
    }
    /**
     * `repeated .api.v1.SearchResult results = 1 [json_name = "results"];`
     * @param value The results to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignResults")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<api.v1.Search.SearchResult, ResultsProxy>.plusAssign(value: api.v1.Search.SearchResult) {
      add(value)
    }
    /**
     * `repeated .api.v1.SearchResult results = 1 [json_name = "results"];`
     * @param values The results to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllResults")
    public fun com.google.protobuf.kotlin.DslList<api.v1.Search.SearchResult, ResultsProxy>.addAll(values: kotlin.collections.Iterable<api.v1.Search.SearchResult>) {
      _builder.addAllResults(values)
    }
    /**
     * `repeated .api.v1.SearchResult results = 1 [json_name = "results"];`
     * @param values The results to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllResults")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<api.v1.Search.SearchResult, ResultsProxy>.plusAssign(values: kotlin.collections.Iterable<api.v1.Search.SearchResult>) {
      addAll(values)
    }
    /**
     * `repeated .api.v1.SearchResult results = 1 [json_name = "results"];`
     * @param index The index to set the value at.
     * @param value The results to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setResults")
    public operator fun com.google.protobuf.kotlin.DslList<api.v1.Search.SearchResult, ResultsProxy>.set(index: kotlin.Int, value: api.v1.Search.SearchResult) {
      _builder.setResults(index, value)
    }
    /**
     * `repeated .api.v1.SearchResult results = 1 [json_name = "results"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearResults")
    public fun com.google.protobuf.kotlin.DslList<api.v1.Search.SearchResult, ResultsProxy>.clear() {
      _builder.clearResults()
    }

  }
}
@kotlin.jvm.JvmSynthetic
public inline fun api.v1.Search.SearchContentResponse.copy(block: `api.v1`.SearchContentResponseKt.Dsl.() -> kotlin.Unit): api.v1.Search.SearchContentResponse =
  `api.v1`.SearchContentResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

