// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/system_info.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package api.v1;

@kotlin.jvm.JvmName("-initializestreamJobStatusRequest")
public inline fun streamJobStatusRequest(block: api.v1.StreamJobStatusRequestKt.Dsl.() -> kotlin.Unit): api.v1.SystemInfo.StreamJobStatusRequest =
  api.v1.StreamJobStatusRequestKt.Dsl._create(api.v1.SystemInfo.StreamJobStatusRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * The request message for the StreamJobStatus RPC.
 * ```
 *
 * Protobuf type `api.v1.StreamJobStatusRequest`
 */
public object StreamJobStatusRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: api.v1.SystemInfo.StreamJobStatusRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: api.v1.SystemInfo.StreamJobStatusRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): api.v1.SystemInfo.StreamJobStatusRequest = _builder.build()

    /**
     * ```
     * Optional: interval in milliseconds for updates (default: 1000ms)
     * ```
     *
     * `optional int32 update_interval_ms = 1 [json_name = "updateIntervalMs"];`
     */
    public var updateIntervalMs: kotlin.Int
      @JvmName("getUpdateIntervalMs")
      get() = _builder.updateIntervalMs
      @JvmName("setUpdateIntervalMs")
      set(value) {
        _builder.updateIntervalMs = value
      }
    /**
     * ```
     * Optional: interval in milliseconds for updates (default: 1000ms)
     * ```
     *
     * `optional int32 update_interval_ms = 1 [json_name = "updateIntervalMs"];`
     */
    public fun clearUpdateIntervalMs() {
      _builder.clearUpdateIntervalMs()
    }
    /**
     * ```
     * Optional: interval in milliseconds for updates (default: 1000ms)
     * ```
     *
     * `optional int32 update_interval_ms = 1 [json_name = "updateIntervalMs"];`
     * @return Whether the updateIntervalMs field is set.
     */
    public fun hasUpdateIntervalMs(): kotlin.Boolean {
      return _builder.hasUpdateIntervalMs()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun api.v1.SystemInfo.StreamJobStatusRequest.copy(block: `api.v1`.StreamJobStatusRequestKt.Dsl.() -> kotlin.Unit): api.v1.SystemInfo.StreamJobStatusRequest =
  `api.v1`.StreamJobStatusRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

