// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/system_info.proto
// Protobuf Java Version: 4.28.3

package api.v1;

public final class SystemInfo {
  private SystemInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface GetVersionRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.v1.GetVersionRequest)
      com.google.protobuf.MessageLiteOrBuilder {
  }
  /**
   * <pre>
   * The request message for the GetVersion RPC.
   * </pre>
   *
   * Protobuf type {@code api.v1.GetVersionRequest}
   */
  public  static final class GetVersionRequest extends
      com.google.protobuf.GeneratedMessageLite<
          GetVersionRequest, GetVersionRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:api.v1.GetVersionRequest)
      GetVersionRequestOrBuilder {
    private GetVersionRequest() {
    }
    public static api.v1.SystemInfo.GetVersionRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.v1.SystemInfo.GetVersionRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.v1.SystemInfo.GetVersionRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.v1.SystemInfo.GetVersionRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.v1.SystemInfo.GetVersionRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.v1.SystemInfo.GetVersionRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.v1.SystemInfo.GetVersionRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.v1.SystemInfo.GetVersionRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static api.v1.SystemInfo.GetVersionRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static api.v1.SystemInfo.GetVersionRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static api.v1.SystemInfo.GetVersionRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.v1.SystemInfo.GetVersionRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(api.v1.SystemInfo.GetVersionRequest prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * The request message for the GetVersion RPC.
     * </pre>
     *
     * Protobuf type {@code api.v1.GetVersionRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          api.v1.SystemInfo.GetVersionRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:api.v1.GetVersionRequest)
        api.v1.SystemInfo.GetVersionRequestOrBuilder {
      // Construct using api.v1.SystemInfo.GetVersionRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      // @@protoc_insertion_point(builder_scope:api.v1.GetVersionRequest)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new api.v1.SystemInfo.GetVersionRequest();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = null;java.lang.String info =
                "\u0000\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<api.v1.SystemInfo.GetVersionRequest> parser = PARSER;
          if (parser == null) {
            synchronized (api.v1.SystemInfo.GetVersionRequest.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<api.v1.SystemInfo.GetVersionRequest>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:api.v1.GetVersionRequest)
    private static final api.v1.SystemInfo.GetVersionRequest DEFAULT_INSTANCE;
    static {
      GetVersionRequest defaultInstance = new GetVersionRequest();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        GetVersionRequest.class, defaultInstance);
    }

    public static api.v1.SystemInfo.GetVersionRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<GetVersionRequest> PARSER;

    public static com.google.protobuf.Parser<GetVersionRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface GetVersionResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.v1.GetVersionResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string commit = 1 [json_name = "commit"];</code>
     * @return The commit.
     */
    java.lang.String getCommit();
    /**
     * <code>string commit = 1 [json_name = "commit"];</code>
     * @return The bytes for commit.
     */
    com.google.protobuf.ByteString
        getCommitBytes();

    /**
     * <code>.google.protobuf.Timestamp build_time = 2 [json_name = "buildTime"];</code>
     * @return Whether the buildTime field is set.
     */
    boolean hasBuildTime();
    /**
     * <code>.google.protobuf.Timestamp build_time = 2 [json_name = "buildTime"];</code>
     * @return The buildTime.
     */
    com.google.protobuf.Timestamp getBuildTime();
  }
  /**
   * <pre>
   * The response message for the GetVersion RPC.
   * </pre>
   *
   * Protobuf type {@code api.v1.GetVersionResponse}
   */
  public  static final class GetVersionResponse extends
      com.google.protobuf.GeneratedMessageLite<
          GetVersionResponse, GetVersionResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:api.v1.GetVersionResponse)
      GetVersionResponseOrBuilder {
    private GetVersionResponse() {
      commit_ = "";
    }
    private int bitField0_;
    public static final int COMMIT_FIELD_NUMBER = 1;
    private java.lang.String commit_;
    /**
     * <code>string commit = 1 [json_name = "commit"];</code>
     * @return The commit.
     */
    @java.lang.Override
    public java.lang.String getCommit() {
      return commit_;
    }
    /**
     * <code>string commit = 1 [json_name = "commit"];</code>
     * @return The bytes for commit.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCommitBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(commit_);
    }
    /**
     * <code>string commit = 1 [json_name = "commit"];</code>
     * @param value The commit to set.
     */
    private void setCommit(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      commit_ = value;
    }
    /**
     * <code>string commit = 1 [json_name = "commit"];</code>
     */
    private void clearCommit() {

      commit_ = getDefaultInstance().getCommit();
    }
    /**
     * <code>string commit = 1 [json_name = "commit"];</code>
     * @param value The bytes for commit to set.
     */
    private void setCommitBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      commit_ = value.toStringUtf8();

    }

    public static final int BUILD_TIME_FIELD_NUMBER = 2;
    private com.google.protobuf.Timestamp buildTime_;
    /**
     * <code>.google.protobuf.Timestamp build_time = 2 [json_name = "buildTime"];</code>
     */
    @java.lang.Override
    public boolean hasBuildTime() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp build_time = 2 [json_name = "buildTime"];</code>
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getBuildTime() {
      return buildTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : buildTime_;
    }
    /**
     * <code>.google.protobuf.Timestamp build_time = 2 [json_name = "buildTime"];</code>
     */
    private void setBuildTime(com.google.protobuf.Timestamp value) {
      value.getClass();
  buildTime_ = value;
      bitField0_ |= 0x00000001;
      }
    /**
     * <code>.google.protobuf.Timestamp build_time = 2 [json_name = "buildTime"];</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeBuildTime(com.google.protobuf.Timestamp value) {
      value.getClass();
  if (buildTime_ != null &&
          buildTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
        buildTime_ =
          com.google.protobuf.Timestamp.newBuilder(buildTime_).mergeFrom(value).buildPartial();
      } else {
        buildTime_ = value;
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>.google.protobuf.Timestamp build_time = 2 [json_name = "buildTime"];</code>
     */
    private void clearBuildTime() {  buildTime_ = null;
      bitField0_ = (bitField0_ & ~0x00000001);
    }

    public static api.v1.SystemInfo.GetVersionResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.v1.SystemInfo.GetVersionResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.v1.SystemInfo.GetVersionResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.v1.SystemInfo.GetVersionResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.v1.SystemInfo.GetVersionResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.v1.SystemInfo.GetVersionResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.v1.SystemInfo.GetVersionResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.v1.SystemInfo.GetVersionResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static api.v1.SystemInfo.GetVersionResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static api.v1.SystemInfo.GetVersionResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static api.v1.SystemInfo.GetVersionResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.v1.SystemInfo.GetVersionResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(api.v1.SystemInfo.GetVersionResponse prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * The response message for the GetVersion RPC.
     * </pre>
     *
     * Protobuf type {@code api.v1.GetVersionResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          api.v1.SystemInfo.GetVersionResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:api.v1.GetVersionResponse)
        api.v1.SystemInfo.GetVersionResponseOrBuilder {
      // Construct using api.v1.SystemInfo.GetVersionResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string commit = 1 [json_name = "commit"];</code>
       * @return The commit.
       */
      @java.lang.Override
      public java.lang.String getCommit() {
        return instance.getCommit();
      }
      /**
       * <code>string commit = 1 [json_name = "commit"];</code>
       * @return The bytes for commit.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getCommitBytes() {
        return instance.getCommitBytes();
      }
      /**
       * <code>string commit = 1 [json_name = "commit"];</code>
       * @param value The commit to set.
       * @return This builder for chaining.
       */
      public Builder setCommit(
          java.lang.String value) {
        copyOnWrite();
        instance.setCommit(value);
        return this;
      }
      /**
       * <code>string commit = 1 [json_name = "commit"];</code>
       * @return This builder for chaining.
       */
      public Builder clearCommit() {
        copyOnWrite();
        instance.clearCommit();
        return this;
      }
      /**
       * <code>string commit = 1 [json_name = "commit"];</code>
       * @param value The bytes for commit to set.
       * @return This builder for chaining.
       */
      public Builder setCommitBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setCommitBytes(value);
        return this;
      }

      /**
       * <code>.google.protobuf.Timestamp build_time = 2 [json_name = "buildTime"];</code>
       */
      @java.lang.Override
      public boolean hasBuildTime() {
        return instance.hasBuildTime();
      }
      /**
       * <code>.google.protobuf.Timestamp build_time = 2 [json_name = "buildTime"];</code>
       */
      @java.lang.Override
      public com.google.protobuf.Timestamp getBuildTime() {
        return instance.getBuildTime();
      }
      /**
       * <code>.google.protobuf.Timestamp build_time = 2 [json_name = "buildTime"];</code>
       */
      public Builder setBuildTime(com.google.protobuf.Timestamp value) {
        copyOnWrite();
        instance.setBuildTime(value);
        return this;
        }
      /**
       * <code>.google.protobuf.Timestamp build_time = 2 [json_name = "buildTime"];</code>
       */
      public Builder setBuildTime(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        copyOnWrite();
        instance.setBuildTime(builderForValue.build());
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp build_time = 2 [json_name = "buildTime"];</code>
       */
      public Builder mergeBuildTime(com.google.protobuf.Timestamp value) {
        copyOnWrite();
        instance.mergeBuildTime(value);
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp build_time = 2 [json_name = "buildTime"];</code>
       */
      public Builder clearBuildTime() {  copyOnWrite();
        instance.clearBuildTime();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:api.v1.GetVersionResponse)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new api.v1.SystemInfo.GetVersionResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "commit_",
              "buildTime_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\u1009" +
                "\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<api.v1.SystemInfo.GetVersionResponse> parser = PARSER;
          if (parser == null) {
            synchronized (api.v1.SystemInfo.GetVersionResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<api.v1.SystemInfo.GetVersionResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:api.v1.GetVersionResponse)
    private static final api.v1.SystemInfo.GetVersionResponse DEFAULT_INSTANCE;
    static {
      GetVersionResponse defaultInstance = new GetVersionResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        GetVersionResponse.class, defaultInstance);
    }

    public static api.v1.SystemInfo.GetVersionResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<GetVersionResponse> PARSER;

    public static com.google.protobuf.Parser<GetVersionResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface GetJobStatusRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.v1.GetJobStatusRequest)
      com.google.protobuf.MessageLiteOrBuilder {
  }
  /**
   * <pre>
   * The request message for the GetJobStatus RPC.
   * </pre>
   *
   * Protobuf type {@code api.v1.GetJobStatusRequest}
   */
  public  static final class GetJobStatusRequest extends
      com.google.protobuf.GeneratedMessageLite<
          GetJobStatusRequest, GetJobStatusRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:api.v1.GetJobStatusRequest)
      GetJobStatusRequestOrBuilder {
    private GetJobStatusRequest() {
    }
    public static api.v1.SystemInfo.GetJobStatusRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.v1.SystemInfo.GetJobStatusRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.v1.SystemInfo.GetJobStatusRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.v1.SystemInfo.GetJobStatusRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.v1.SystemInfo.GetJobStatusRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.v1.SystemInfo.GetJobStatusRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.v1.SystemInfo.GetJobStatusRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.v1.SystemInfo.GetJobStatusRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static api.v1.SystemInfo.GetJobStatusRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static api.v1.SystemInfo.GetJobStatusRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static api.v1.SystemInfo.GetJobStatusRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.v1.SystemInfo.GetJobStatusRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(api.v1.SystemInfo.GetJobStatusRequest prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * The request message for the GetJobStatus RPC.
     * </pre>
     *
     * Protobuf type {@code api.v1.GetJobStatusRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          api.v1.SystemInfo.GetJobStatusRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:api.v1.GetJobStatusRequest)
        api.v1.SystemInfo.GetJobStatusRequestOrBuilder {
      // Construct using api.v1.SystemInfo.GetJobStatusRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      // @@protoc_insertion_point(builder_scope:api.v1.GetJobStatusRequest)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new api.v1.SystemInfo.GetJobStatusRequest();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = null;java.lang.String info =
                "\u0000\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<api.v1.SystemInfo.GetJobStatusRequest> parser = PARSER;
          if (parser == null) {
            synchronized (api.v1.SystemInfo.GetJobStatusRequest.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<api.v1.SystemInfo.GetJobStatusRequest>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:api.v1.GetJobStatusRequest)
    private static final api.v1.SystemInfo.GetJobStatusRequest DEFAULT_INSTANCE;
    static {
      GetJobStatusRequest defaultInstance = new GetJobStatusRequest();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        GetJobStatusRequest.class, defaultInstance);
    }

    public static api.v1.SystemInfo.GetJobStatusRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<GetJobStatusRequest> PARSER;

    public static com.google.protobuf.Parser<GetJobStatusRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface StreamJobStatusRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.v1.StreamJobStatusRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * Optional: interval in milliseconds for updates (default: 1000ms)
     * </pre>
     *
     * <code>optional int32 update_interval_ms = 1 [json_name = "updateIntervalMs"];</code>
     * @return Whether the updateIntervalMs field is set.
     */
    boolean hasUpdateIntervalMs();
    /**
     * <pre>
     * Optional: interval in milliseconds for updates (default: 1000ms)
     * </pre>
     *
     * <code>optional int32 update_interval_ms = 1 [json_name = "updateIntervalMs"];</code>
     * @return The updateIntervalMs.
     */
    int getUpdateIntervalMs();
  }
  /**
   * <pre>
   * The request message for the StreamJobStatus RPC.
   * </pre>
   *
   * Protobuf type {@code api.v1.StreamJobStatusRequest}
   */
  public  static final class StreamJobStatusRequest extends
      com.google.protobuf.GeneratedMessageLite<
          StreamJobStatusRequest, StreamJobStatusRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:api.v1.StreamJobStatusRequest)
      StreamJobStatusRequestOrBuilder {
    private StreamJobStatusRequest() {
    }
    private int bitField0_;
    public static final int UPDATE_INTERVAL_MS_FIELD_NUMBER = 1;
    private int updateIntervalMs_;
    /**
     * <pre>
     * Optional: interval in milliseconds for updates (default: 1000ms)
     * </pre>
     *
     * <code>optional int32 update_interval_ms = 1 [json_name = "updateIntervalMs"];</code>
     * @return Whether the updateIntervalMs field is set.
     */
    @java.lang.Override
    public boolean hasUpdateIntervalMs() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Optional: interval in milliseconds for updates (default: 1000ms)
     * </pre>
     *
     * <code>optional int32 update_interval_ms = 1 [json_name = "updateIntervalMs"];</code>
     * @return The updateIntervalMs.
     */
    @java.lang.Override
    public int getUpdateIntervalMs() {
      return updateIntervalMs_;
    }
    /**
     * <pre>
     * Optional: interval in milliseconds for updates (default: 1000ms)
     * </pre>
     *
     * <code>optional int32 update_interval_ms = 1 [json_name = "updateIntervalMs"];</code>
     * @param value The updateIntervalMs to set.
     */
    private void setUpdateIntervalMs(int value) {
      bitField0_ |= 0x00000001;
      updateIntervalMs_ = value;
    }
    /**
     * <pre>
     * Optional: interval in milliseconds for updates (default: 1000ms)
     * </pre>
     *
     * <code>optional int32 update_interval_ms = 1 [json_name = "updateIntervalMs"];</code>
     */
    private void clearUpdateIntervalMs() {
      bitField0_ = (bitField0_ & ~0x00000001);
      updateIntervalMs_ = 0;
    }

    public static api.v1.SystemInfo.StreamJobStatusRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.v1.SystemInfo.StreamJobStatusRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.v1.SystemInfo.StreamJobStatusRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.v1.SystemInfo.StreamJobStatusRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.v1.SystemInfo.StreamJobStatusRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.v1.SystemInfo.StreamJobStatusRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.v1.SystemInfo.StreamJobStatusRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.v1.SystemInfo.StreamJobStatusRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static api.v1.SystemInfo.StreamJobStatusRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static api.v1.SystemInfo.StreamJobStatusRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static api.v1.SystemInfo.StreamJobStatusRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.v1.SystemInfo.StreamJobStatusRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(api.v1.SystemInfo.StreamJobStatusRequest prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * The request message for the StreamJobStatus RPC.
     * </pre>
     *
     * Protobuf type {@code api.v1.StreamJobStatusRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          api.v1.SystemInfo.StreamJobStatusRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:api.v1.StreamJobStatusRequest)
        api.v1.SystemInfo.StreamJobStatusRequestOrBuilder {
      // Construct using api.v1.SystemInfo.StreamJobStatusRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * Optional: interval in milliseconds for updates (default: 1000ms)
       * </pre>
       *
       * <code>optional int32 update_interval_ms = 1 [json_name = "updateIntervalMs"];</code>
       * @return Whether the updateIntervalMs field is set.
       */
      @java.lang.Override
      public boolean hasUpdateIntervalMs() {
        return instance.hasUpdateIntervalMs();
      }
      /**
       * <pre>
       * Optional: interval in milliseconds for updates (default: 1000ms)
       * </pre>
       *
       * <code>optional int32 update_interval_ms = 1 [json_name = "updateIntervalMs"];</code>
       * @return The updateIntervalMs.
       */
      @java.lang.Override
      public int getUpdateIntervalMs() {
        return instance.getUpdateIntervalMs();
      }
      /**
       * <pre>
       * Optional: interval in milliseconds for updates (default: 1000ms)
       * </pre>
       *
       * <code>optional int32 update_interval_ms = 1 [json_name = "updateIntervalMs"];</code>
       * @param value The updateIntervalMs to set.
       * @return This builder for chaining.
       */
      public Builder setUpdateIntervalMs(int value) {
        copyOnWrite();
        instance.setUpdateIntervalMs(value);
        return this;
      }
      /**
       * <pre>
       * Optional: interval in milliseconds for updates (default: 1000ms)
       * </pre>
       *
       * <code>optional int32 update_interval_ms = 1 [json_name = "updateIntervalMs"];</code>
       * @return This builder for chaining.
       */
      public Builder clearUpdateIntervalMs() {
        copyOnWrite();
        instance.clearUpdateIntervalMs();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:api.v1.StreamJobStatusRequest)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new api.v1.SystemInfo.StreamJobStatusRequest();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "updateIntervalMs_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0001\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u1004\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<api.v1.SystemInfo.StreamJobStatusRequest> parser = PARSER;
          if (parser == null) {
            synchronized (api.v1.SystemInfo.StreamJobStatusRequest.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<api.v1.SystemInfo.StreamJobStatusRequest>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:api.v1.StreamJobStatusRequest)
    private static final api.v1.SystemInfo.StreamJobStatusRequest DEFAULT_INSTANCE;
    static {
      StreamJobStatusRequest defaultInstance = new StreamJobStatusRequest();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        StreamJobStatusRequest.class, defaultInstance);
    }

    public static api.v1.SystemInfo.StreamJobStatusRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<StreamJobStatusRequest> PARSER;

    public static com.google.protobuf.Parser<StreamJobStatusRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface GetJobStatusResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.v1.GetJobStatusResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .api.v1.JobQueueStatus job_queues = 1 [json_name = "jobQueues"];</code>
     */
    java.util.List<api.v1.SystemInfo.JobQueueStatus> 
        getJobQueuesList();
    /**
     * <code>repeated .api.v1.JobQueueStatus job_queues = 1 [json_name = "jobQueues"];</code>
     */
    api.v1.SystemInfo.JobQueueStatus getJobQueues(int index);
    /**
     * <code>repeated .api.v1.JobQueueStatus job_queues = 1 [json_name = "jobQueues"];</code>
     */
    int getJobQueuesCount();
  }
  /**
   * <pre>
   * The response message for the GetJobStatus RPC.
   * </pre>
   *
   * Protobuf type {@code api.v1.GetJobStatusResponse}
   */
  public  static final class GetJobStatusResponse extends
      com.google.protobuf.GeneratedMessageLite<
          GetJobStatusResponse, GetJobStatusResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:api.v1.GetJobStatusResponse)
      GetJobStatusResponseOrBuilder {
    private GetJobStatusResponse() {
      jobQueues_ = emptyProtobufList();
    }
    public static final int JOB_QUEUES_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<api.v1.SystemInfo.JobQueueStatus> jobQueues_;
    /**
     * <code>repeated .api.v1.JobQueueStatus job_queues = 1 [json_name = "jobQueues"];</code>
     */
    @java.lang.Override
    public java.util.List<api.v1.SystemInfo.JobQueueStatus> getJobQueuesList() {
      return jobQueues_;
    }
    /**
     * <code>repeated .api.v1.JobQueueStatus job_queues = 1 [json_name = "jobQueues"];</code>
     */
    public java.util.List<? extends api.v1.SystemInfo.JobQueueStatusOrBuilder> 
        getJobQueuesOrBuilderList() {
      return jobQueues_;
    }
    /**
     * <code>repeated .api.v1.JobQueueStatus job_queues = 1 [json_name = "jobQueues"];</code>
     */
    @java.lang.Override
    public int getJobQueuesCount() {
      return jobQueues_.size();
    }
    /**
     * <code>repeated .api.v1.JobQueueStatus job_queues = 1 [json_name = "jobQueues"];</code>
     */
    @java.lang.Override
    public api.v1.SystemInfo.JobQueueStatus getJobQueues(int index) {
      return jobQueues_.get(index);
    }
    /**
     * <code>repeated .api.v1.JobQueueStatus job_queues = 1 [json_name = "jobQueues"];</code>
     */
    public api.v1.SystemInfo.JobQueueStatusOrBuilder getJobQueuesOrBuilder(
        int index) {
      return jobQueues_.get(index);
    }
    private void ensureJobQueuesIsMutable() {
      com.google.protobuf.Internal.ProtobufList<api.v1.SystemInfo.JobQueueStatus> tmp = jobQueues_;
      if (!tmp.isModifiable()) {
        jobQueues_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .api.v1.JobQueueStatus job_queues = 1 [json_name = "jobQueues"];</code>
     */
    private void setJobQueues(
        int index, api.v1.SystemInfo.JobQueueStatus value) {
      value.getClass();
  ensureJobQueuesIsMutable();
      jobQueues_.set(index, value);
    }
    /**
     * <code>repeated .api.v1.JobQueueStatus job_queues = 1 [json_name = "jobQueues"];</code>
     */
    private void addJobQueues(api.v1.SystemInfo.JobQueueStatus value) {
      value.getClass();
  ensureJobQueuesIsMutable();
      jobQueues_.add(value);
    }
    /**
     * <code>repeated .api.v1.JobQueueStatus job_queues = 1 [json_name = "jobQueues"];</code>
     */
    private void addJobQueues(
        int index, api.v1.SystemInfo.JobQueueStatus value) {
      value.getClass();
  ensureJobQueuesIsMutable();
      jobQueues_.add(index, value);
    }
    /**
     * <code>repeated .api.v1.JobQueueStatus job_queues = 1 [json_name = "jobQueues"];</code>
     */
    private void addAllJobQueues(
        java.lang.Iterable<? extends api.v1.SystemInfo.JobQueueStatus> values) {
      ensureJobQueuesIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, jobQueues_);
    }
    /**
     * <code>repeated .api.v1.JobQueueStatus job_queues = 1 [json_name = "jobQueues"];</code>
     */
    private void clearJobQueues() {
      jobQueues_ = emptyProtobufList();
    }
    /**
     * <code>repeated .api.v1.JobQueueStatus job_queues = 1 [json_name = "jobQueues"];</code>
     */
    private void removeJobQueues(int index) {
      ensureJobQueuesIsMutable();
      jobQueues_.remove(index);
    }

    public static api.v1.SystemInfo.GetJobStatusResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.v1.SystemInfo.GetJobStatusResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.v1.SystemInfo.GetJobStatusResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.v1.SystemInfo.GetJobStatusResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.v1.SystemInfo.GetJobStatusResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.v1.SystemInfo.GetJobStatusResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.v1.SystemInfo.GetJobStatusResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.v1.SystemInfo.GetJobStatusResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static api.v1.SystemInfo.GetJobStatusResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static api.v1.SystemInfo.GetJobStatusResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static api.v1.SystemInfo.GetJobStatusResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.v1.SystemInfo.GetJobStatusResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(api.v1.SystemInfo.GetJobStatusResponse prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * The response message for the GetJobStatus RPC.
     * </pre>
     *
     * Protobuf type {@code api.v1.GetJobStatusResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          api.v1.SystemInfo.GetJobStatusResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:api.v1.GetJobStatusResponse)
        api.v1.SystemInfo.GetJobStatusResponseOrBuilder {
      // Construct using api.v1.SystemInfo.GetJobStatusResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated .api.v1.JobQueueStatus job_queues = 1 [json_name = "jobQueues"];</code>
       */
      @java.lang.Override
      public java.util.List<api.v1.SystemInfo.JobQueueStatus> getJobQueuesList() {
        return java.util.Collections.unmodifiableList(
            instance.getJobQueuesList());
      }
      /**
       * <code>repeated .api.v1.JobQueueStatus job_queues = 1 [json_name = "jobQueues"];</code>
       */
      @java.lang.Override
      public int getJobQueuesCount() {
        return instance.getJobQueuesCount();
      }/**
       * <code>repeated .api.v1.JobQueueStatus job_queues = 1 [json_name = "jobQueues"];</code>
       */
      @java.lang.Override
      public api.v1.SystemInfo.JobQueueStatus getJobQueues(int index) {
        return instance.getJobQueues(index);
      }
      /**
       * <code>repeated .api.v1.JobQueueStatus job_queues = 1 [json_name = "jobQueues"];</code>
       */
      public Builder setJobQueues(
          int index, api.v1.SystemInfo.JobQueueStatus value) {
        copyOnWrite();
        instance.setJobQueues(index, value);
        return this;
      }
      /**
       * <code>repeated .api.v1.JobQueueStatus job_queues = 1 [json_name = "jobQueues"];</code>
       */
      public Builder setJobQueues(
          int index, api.v1.SystemInfo.JobQueueStatus.Builder builderForValue) {
        copyOnWrite();
        instance.setJobQueues(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .api.v1.JobQueueStatus job_queues = 1 [json_name = "jobQueues"];</code>
       */
      public Builder addJobQueues(api.v1.SystemInfo.JobQueueStatus value) {
        copyOnWrite();
        instance.addJobQueues(value);
        return this;
      }
      /**
       * <code>repeated .api.v1.JobQueueStatus job_queues = 1 [json_name = "jobQueues"];</code>
       */
      public Builder addJobQueues(
          int index, api.v1.SystemInfo.JobQueueStatus value) {
        copyOnWrite();
        instance.addJobQueues(index, value);
        return this;
      }
      /**
       * <code>repeated .api.v1.JobQueueStatus job_queues = 1 [json_name = "jobQueues"];</code>
       */
      public Builder addJobQueues(
          api.v1.SystemInfo.JobQueueStatus.Builder builderForValue) {
        copyOnWrite();
        instance.addJobQueues(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .api.v1.JobQueueStatus job_queues = 1 [json_name = "jobQueues"];</code>
       */
      public Builder addJobQueues(
          int index, api.v1.SystemInfo.JobQueueStatus.Builder builderForValue) {
        copyOnWrite();
        instance.addJobQueues(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .api.v1.JobQueueStatus job_queues = 1 [json_name = "jobQueues"];</code>
       */
      public Builder addAllJobQueues(
          java.lang.Iterable<? extends api.v1.SystemInfo.JobQueueStatus> values) {
        copyOnWrite();
        instance.addAllJobQueues(values);
        return this;
      }
      /**
       * <code>repeated .api.v1.JobQueueStatus job_queues = 1 [json_name = "jobQueues"];</code>
       */
      public Builder clearJobQueues() {
        copyOnWrite();
        instance.clearJobQueues();
        return this;
      }
      /**
       * <code>repeated .api.v1.JobQueueStatus job_queues = 1 [json_name = "jobQueues"];</code>
       */
      public Builder removeJobQueues(int index) {
        copyOnWrite();
        instance.removeJobQueues(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:api.v1.GetJobStatusResponse)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new api.v1.SystemInfo.GetJobStatusResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "jobQueues_",
              api.v1.SystemInfo.JobQueueStatus.class,
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u001b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<api.v1.SystemInfo.GetJobStatusResponse> parser = PARSER;
          if (parser == null) {
            synchronized (api.v1.SystemInfo.GetJobStatusResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<api.v1.SystemInfo.GetJobStatusResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:api.v1.GetJobStatusResponse)
    private static final api.v1.SystemInfo.GetJobStatusResponse DEFAULT_INSTANCE;
    static {
      GetJobStatusResponse defaultInstance = new GetJobStatusResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        GetJobStatusResponse.class, defaultInstance);
    }

    public static api.v1.SystemInfo.GetJobStatusResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<GetJobStatusResponse> PARSER;

    public static com.google.protobuf.Parser<GetJobStatusResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface JobQueueStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.v1.JobQueueStatus)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * "Frontmatter", "Bleve", "File Scan"
     * </pre>
     *
     * <code>string name = 1 [json_name = "name"];</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <pre>
     * "Frontmatter", "Bleve", "File Scan"
     * </pre>
     *
     * <code>string name = 1 [json_name = "name"];</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     * Current queue depth
     * </pre>
     *
     * <code>int32 jobs_remaining = 2 [json_name = "jobsRemaining"];</code>
     * @return The jobsRemaining.
     */
    int getJobsRemaining();

    /**
     * <pre>
     * Peak, resets to 0 when empty
     * </pre>
     *
     * <code>int32 high_water_mark = 3 [json_name = "highWaterMark"];</code>
     * @return The highWaterMark.
     */
    int getHighWaterMark();

    /**
     * <pre>
     * jobs_remaining &gt; 0
     * </pre>
     *
     * <code>bool is_active = 4 [json_name = "isActive"];</code>
     * @return The isActive.
     */
    boolean getIsActive();
  }
  /**
   * <pre>
   * Status information for a single job queue.
   * </pre>
   *
   * Protobuf type {@code api.v1.JobQueueStatus}
   */
  public  static final class JobQueueStatus extends
      com.google.protobuf.GeneratedMessageLite<
          JobQueueStatus, JobQueueStatus.Builder> implements
      // @@protoc_insertion_point(message_implements:api.v1.JobQueueStatus)
      JobQueueStatusOrBuilder {
    private JobQueueStatus() {
      name_ = "";
    }
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.String name_;
    /**
     * <pre>
     * "Frontmatter", "Bleve", "File Scan"
     * </pre>
     *
     * <code>string name = 1 [json_name = "name"];</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      return name_;
    }
    /**
     * <pre>
     * "Frontmatter", "Bleve", "File Scan"
     * </pre>
     *
     * <code>string name = 1 [json_name = "name"];</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(name_);
    }
    /**
     * <pre>
     * "Frontmatter", "Bleve", "File Scan"
     * </pre>
     *
     * <code>string name = 1 [json_name = "name"];</code>
     * @param value The name to set.
     */
    private void setName(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      name_ = value;
    }
    /**
     * <pre>
     * "Frontmatter", "Bleve", "File Scan"
     * </pre>
     *
     * <code>string name = 1 [json_name = "name"];</code>
     */
    private void clearName() {

      name_ = getDefaultInstance().getName();
    }
    /**
     * <pre>
     * "Frontmatter", "Bleve", "File Scan"
     * </pre>
     *
     * <code>string name = 1 [json_name = "name"];</code>
     * @param value The bytes for name to set.
     */
    private void setNameBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      name_ = value.toStringUtf8();

    }

    public static final int JOBS_REMAINING_FIELD_NUMBER = 2;
    private int jobsRemaining_;
    /**
     * <pre>
     * Current queue depth
     * </pre>
     *
     * <code>int32 jobs_remaining = 2 [json_name = "jobsRemaining"];</code>
     * @return The jobsRemaining.
     */
    @java.lang.Override
    public int getJobsRemaining() {
      return jobsRemaining_;
    }
    /**
     * <pre>
     * Current queue depth
     * </pre>
     *
     * <code>int32 jobs_remaining = 2 [json_name = "jobsRemaining"];</code>
     * @param value The jobsRemaining to set.
     */
    private void setJobsRemaining(int value) {
      
      jobsRemaining_ = value;
    }
    /**
     * <pre>
     * Current queue depth
     * </pre>
     *
     * <code>int32 jobs_remaining = 2 [json_name = "jobsRemaining"];</code>
     */
    private void clearJobsRemaining() {

      jobsRemaining_ = 0;
    }

    public static final int HIGH_WATER_MARK_FIELD_NUMBER = 3;
    private int highWaterMark_;
    /**
     * <pre>
     * Peak, resets to 0 when empty
     * </pre>
     *
     * <code>int32 high_water_mark = 3 [json_name = "highWaterMark"];</code>
     * @return The highWaterMark.
     */
    @java.lang.Override
    public int getHighWaterMark() {
      return highWaterMark_;
    }
    /**
     * <pre>
     * Peak, resets to 0 when empty
     * </pre>
     *
     * <code>int32 high_water_mark = 3 [json_name = "highWaterMark"];</code>
     * @param value The highWaterMark to set.
     */
    private void setHighWaterMark(int value) {
      
      highWaterMark_ = value;
    }
    /**
     * <pre>
     * Peak, resets to 0 when empty
     * </pre>
     *
     * <code>int32 high_water_mark = 3 [json_name = "highWaterMark"];</code>
     */
    private void clearHighWaterMark() {

      highWaterMark_ = 0;
    }

    public static final int IS_ACTIVE_FIELD_NUMBER = 4;
    private boolean isActive_;
    /**
     * <pre>
     * jobs_remaining &gt; 0
     * </pre>
     *
     * <code>bool is_active = 4 [json_name = "isActive"];</code>
     * @return The isActive.
     */
    @java.lang.Override
    public boolean getIsActive() {
      return isActive_;
    }
    /**
     * <pre>
     * jobs_remaining &gt; 0
     * </pre>
     *
     * <code>bool is_active = 4 [json_name = "isActive"];</code>
     * @param value The isActive to set.
     */
    private void setIsActive(boolean value) {
      
      isActive_ = value;
    }
    /**
     * <pre>
     * jobs_remaining &gt; 0
     * </pre>
     *
     * <code>bool is_active = 4 [json_name = "isActive"];</code>
     */
    private void clearIsActive() {

      isActive_ = false;
    }

    public static api.v1.SystemInfo.JobQueueStatus parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.v1.SystemInfo.JobQueueStatus parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.v1.SystemInfo.JobQueueStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.v1.SystemInfo.JobQueueStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.v1.SystemInfo.JobQueueStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.v1.SystemInfo.JobQueueStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.v1.SystemInfo.JobQueueStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.v1.SystemInfo.JobQueueStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static api.v1.SystemInfo.JobQueueStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static api.v1.SystemInfo.JobQueueStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static api.v1.SystemInfo.JobQueueStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.v1.SystemInfo.JobQueueStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(api.v1.SystemInfo.JobQueueStatus prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Status information for a single job queue.
     * </pre>
     *
     * Protobuf type {@code api.v1.JobQueueStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          api.v1.SystemInfo.JobQueueStatus, Builder> implements
        // @@protoc_insertion_point(builder_implements:api.v1.JobQueueStatus)
        api.v1.SystemInfo.JobQueueStatusOrBuilder {
      // Construct using api.v1.SystemInfo.JobQueueStatus.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * "Frontmatter", "Bleve", "File Scan"
       * </pre>
       *
       * <code>string name = 1 [json_name = "name"];</code>
       * @return The name.
       */
      @java.lang.Override
      public java.lang.String getName() {
        return instance.getName();
      }
      /**
       * <pre>
       * "Frontmatter", "Bleve", "File Scan"
       * </pre>
       *
       * <code>string name = 1 [json_name = "name"];</code>
       * @return The bytes for name.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getNameBytes() {
        return instance.getNameBytes();
      }
      /**
       * <pre>
       * "Frontmatter", "Bleve", "File Scan"
       * </pre>
       *
       * <code>string name = 1 [json_name = "name"];</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        copyOnWrite();
        instance.setName(value);
        return this;
      }
      /**
       * <pre>
       * "Frontmatter", "Bleve", "File Scan"
       * </pre>
       *
       * <code>string name = 1 [json_name = "name"];</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        copyOnWrite();
        instance.clearName();
        return this;
      }
      /**
       * <pre>
       * "Frontmatter", "Bleve", "File Scan"
       * </pre>
       *
       * <code>string name = 1 [json_name = "name"];</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNameBytes(value);
        return this;
      }

      /**
       * <pre>
       * Current queue depth
       * </pre>
       *
       * <code>int32 jobs_remaining = 2 [json_name = "jobsRemaining"];</code>
       * @return The jobsRemaining.
       */
      @java.lang.Override
      public int getJobsRemaining() {
        return instance.getJobsRemaining();
      }
      /**
       * <pre>
       * Current queue depth
       * </pre>
       *
       * <code>int32 jobs_remaining = 2 [json_name = "jobsRemaining"];</code>
       * @param value The jobsRemaining to set.
       * @return This builder for chaining.
       */
      public Builder setJobsRemaining(int value) {
        copyOnWrite();
        instance.setJobsRemaining(value);
        return this;
      }
      /**
       * <pre>
       * Current queue depth
       * </pre>
       *
       * <code>int32 jobs_remaining = 2 [json_name = "jobsRemaining"];</code>
       * @return This builder for chaining.
       */
      public Builder clearJobsRemaining() {
        copyOnWrite();
        instance.clearJobsRemaining();
        return this;
      }

      /**
       * <pre>
       * Peak, resets to 0 when empty
       * </pre>
       *
       * <code>int32 high_water_mark = 3 [json_name = "highWaterMark"];</code>
       * @return The highWaterMark.
       */
      @java.lang.Override
      public int getHighWaterMark() {
        return instance.getHighWaterMark();
      }
      /**
       * <pre>
       * Peak, resets to 0 when empty
       * </pre>
       *
       * <code>int32 high_water_mark = 3 [json_name = "highWaterMark"];</code>
       * @param value The highWaterMark to set.
       * @return This builder for chaining.
       */
      public Builder setHighWaterMark(int value) {
        copyOnWrite();
        instance.setHighWaterMark(value);
        return this;
      }
      /**
       * <pre>
       * Peak, resets to 0 when empty
       * </pre>
       *
       * <code>int32 high_water_mark = 3 [json_name = "highWaterMark"];</code>
       * @return This builder for chaining.
       */
      public Builder clearHighWaterMark() {
        copyOnWrite();
        instance.clearHighWaterMark();
        return this;
      }

      /**
       * <pre>
       * jobs_remaining &gt; 0
       * </pre>
       *
       * <code>bool is_active = 4 [json_name = "isActive"];</code>
       * @return The isActive.
       */
      @java.lang.Override
      public boolean getIsActive() {
        return instance.getIsActive();
      }
      /**
       * <pre>
       * jobs_remaining &gt; 0
       * </pre>
       *
       * <code>bool is_active = 4 [json_name = "isActive"];</code>
       * @param value The isActive to set.
       * @return This builder for chaining.
       */
      public Builder setIsActive(boolean value) {
        copyOnWrite();
        instance.setIsActive(value);
        return this;
      }
      /**
       * <pre>
       * jobs_remaining &gt; 0
       * </pre>
       *
       * <code>bool is_active = 4 [json_name = "isActive"];</code>
       * @return This builder for chaining.
       */
      public Builder clearIsActive() {
        copyOnWrite();
        instance.clearIsActive();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:api.v1.JobQueueStatus)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new api.v1.SystemInfo.JobQueueStatus();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "name_",
              "jobsRemaining_",
              "highWaterMark_",
              "isActive_",
            };
            java.lang.String info =
                "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u0208\u0002\u0004" +
                "\u0003\u0004\u0004\u0007";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<api.v1.SystemInfo.JobQueueStatus> parser = PARSER;
          if (parser == null) {
            synchronized (api.v1.SystemInfo.JobQueueStatus.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<api.v1.SystemInfo.JobQueueStatus>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:api.v1.JobQueueStatus)
    private static final api.v1.SystemInfo.JobQueueStatus DEFAULT_INSTANCE;
    static {
      JobQueueStatus defaultInstance = new JobQueueStatus();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        JobQueueStatus.class, defaultInstance);
    }

    public static api.v1.SystemInfo.JobQueueStatus getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<JobQueueStatus> PARSER;

    public static com.google.protobuf.Parser<JobQueueStatus> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
