// Code generated by connect-kotlin. DO NOT EDIT.
//
// Source: api/v1/system_info.proto
//
package api.v1

import com.connectrpc.Headers
import com.connectrpc.ResponseMessage
import com.connectrpc.ServerOnlyStreamInterface

public interface SystemInfoServiceClientInterface {
  /**
   *  GetVersion returns the server version and build time.
   */
  public suspend fun getVersion(request: SystemInfo.GetVersionRequest, headers: Headers = emptyMap()): ResponseMessage<SystemInfo.GetVersionResponse>

  /**
   *  GetJobStatus returns the current status of background job queues.
   */
  public suspend fun getJobStatus(request: SystemInfo.GetJobStatusRequest, headers: Headers = emptyMap()): ResponseMessage<SystemInfo.GetJobStatusResponse>

  /**
   *  StreamJobStatus provides real-time streaming updates of job queue status.
   *  The stream will automatically terminate when all queues are idle.
   */
  public suspend fun streamJobStatus(headers: Headers = emptyMap()): ServerOnlyStreamInterface<SystemInfo.StreamJobStatusRequest, SystemInfo.GetJobStatusResponse>
}
