// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/page_management.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package api.v1;

@kotlin.jvm.JvmName("-initializeupdatePageRequest")
public inline fun updatePageRequest(block: api.v1.UpdatePageRequestKt.Dsl.() -> kotlin.Unit): api.v1.PageManagement.UpdatePageRequest =
  api.v1.UpdatePageRequestKt.Dsl._create(api.v1.PageManagement.UpdatePageRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * Update Page
 * ```
 *
 * Protobuf type `api.v1.UpdatePageRequest`
 */
public object UpdatePageRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: api.v1.PageManagement.UpdatePageRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: api.v1.PageManagement.UpdatePageRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): api.v1.PageManagement.UpdatePageRequest = _builder.build()

    /**
     * `string page_name = 1 [json_name = "pageName"];`
     */
    public var pageName: kotlin.String
      @JvmName("getPageName")
      get() = _builder.pageName
      @JvmName("setPageName")
      set(value) {
        _builder.pageName = value
      }
    /**
     * `string page_name = 1 [json_name = "pageName"];`
     */
    public fun clearPageName() {
      _builder.clearPageName()
    }

    /**
     * `string new_content_markdown = 2 [json_name = "newContentMarkdown"];`
     */
    public var newContentMarkdown: kotlin.String
      @JvmName("getNewContentMarkdown")
      get() = _builder.newContentMarkdown
      @JvmName("setNewContentMarkdown")
      set(value) {
        _builder.newContentMarkdown = value
      }
    /**
     * `string new_content_markdown = 2 [json_name = "newContentMarkdown"];`
     */
    public fun clearNewContentMarkdown() {
      _builder.clearNewContentMarkdown()
    }

    /**
     * `string new_front_matter_toml = 3 [json_name = "newFrontMatterToml"];`
     */
    public var newFrontMatterToml: kotlin.String
      @JvmName("getNewFrontMatterToml")
      get() = _builder.newFrontMatterToml
      @JvmName("setNewFrontMatterToml")
      set(value) {
        _builder.newFrontMatterToml = value
      }
    /**
     * `string new_front_matter_toml = 3 [json_name = "newFrontMatterToml"];`
     */
    public fun clearNewFrontMatterToml() {
      _builder.clearNewFrontMatterToml()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun api.v1.PageManagement.UpdatePageRequest.copy(block: `api.v1`.UpdatePageRequestKt.Dsl.() -> kotlin.Unit): api.v1.PageManagement.UpdatePageRequest =
  `api.v1`.UpdatePageRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

