// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/page_management.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package api.v1;

@kotlin.jvm.JvmName("-initializeupdateWholePageRequest")
public inline fun updateWholePageRequest(block: api.v1.UpdateWholePageRequestKt.Dsl.() -> kotlin.Unit): api.v1.PageManagement.UpdateWholePageRequest =
  api.v1.UpdateWholePageRequestKt.Dsl._create(api.v1.PageManagement.UpdateWholePageRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * Update Whole Page
 * ```
 *
 * Protobuf type `api.v1.UpdateWholePageRequest`
 */
public object UpdateWholePageRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: api.v1.PageManagement.UpdateWholePageRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: api.v1.PageManagement.UpdateWholePageRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): api.v1.PageManagement.UpdateWholePageRequest = _builder.build()

    /**
     * `string page_name = 1 [json_name = "pageName"];`
     */
    public var pageName: kotlin.String
      @JvmName("getPageName")
      get() = _builder.pageName
      @JvmName("setPageName")
      set(value) {
        _builder.pageName = value
      }
    /**
     * `string page_name = 1 [json_name = "pageName"];`
     */
    public fun clearPageName() {
      _builder.clearPageName()
    }

    /**
     * ```
     * Markdown including front matter
     * ```
     *
     * `string new_whole_markdown = 2 [json_name = "newWholeMarkdown"];`
     */
    public var newWholeMarkdown: kotlin.String
      @JvmName("getNewWholeMarkdown")
      get() = _builder.newWholeMarkdown
      @JvmName("setNewWholeMarkdown")
      set(value) {
        _builder.newWholeMarkdown = value
      }
    /**
     * ```
     * Markdown including front matter
     * ```
     *
     * `string new_whole_markdown = 2 [json_name = "newWholeMarkdown"];`
     */
    public fun clearNewWholeMarkdown() {
      _builder.clearNewWholeMarkdown()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun api.v1.PageManagement.UpdateWholePageRequest.copy(block: `api.v1`.UpdateWholePageRequestKt.Dsl.() -> kotlin.Unit): api.v1.PageManagement.UpdateWholePageRequest =
  `api.v1`.UpdateWholePageRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

