// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/page_management.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package api.v1;

@kotlin.jvm.JvmName("-initializeupdateWholePageResponse")
public inline fun updateWholePageResponse(block: api.v1.UpdateWholePageResponseKt.Dsl.() -> kotlin.Unit): api.v1.PageManagement.UpdateWholePageResponse =
  api.v1.UpdateWholePageResponseKt.Dsl._create(api.v1.PageManagement.UpdateWholePageResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `api.v1.UpdateWholePageResponse`
 */
public object UpdateWholePageResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: api.v1.PageManagement.UpdateWholePageResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: api.v1.PageManagement.UpdateWholePageResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): api.v1.PageManagement.UpdateWholePageResponse = _builder.build()

    /**
     * `bool success = 1 [json_name = "success"];`
     */
    public var success: kotlin.Boolean
      @JvmName("getSuccess")
      get() = _builder.success
      @JvmName("setSuccess")
      set(value) {
        _builder.success = value
      }
    /**
     * `bool success = 1 [json_name = "success"];`
     */
    public fun clearSuccess() {
      _builder.clearSuccess()
    }

    /**
     * `string error = 2 [json_name = "error"];`
     */
    public var error: kotlin.String
      @JvmName("getError")
      get() = _builder.error
      @JvmName("setError")
      set(value) {
        _builder.error = value
      }
    /**
     * `string error = 2 [json_name = "error"];`
     */
    public fun clearError() {
      _builder.clearError()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun api.v1.PageManagement.UpdateWholePageResponse.copy(block: `api.v1`.UpdateWholePageResponseKt.Dsl.() -> kotlin.Unit): api.v1.PageManagement.UpdateWholePageResponse =
  `api.v1`.UpdateWholePageResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

