name: Copilot Setup Steps

on:
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Devbox
        uses: jetify-com/devbox-install-action@v0.12.0
        with:
          enable-cache: 'true'

      - name: Install Devbox dependencies
        run: devbox install

      - name: Configure pre-commit hook for linting
        run: |
          mkdir -p .git/hooks
          echo '#!/bin/sh' > .git/hooks/pre-commit
          echo 'devbox run lint:everything' >> .git/hooks/pre-commit
          chmod +x .git/hooks/pre-commit
