name: Copilot Setup Steps

on:
  workflow_call:
    secrets:
      CHROMATIC_PROJECT_TOKEN:
        required: true
      GITHUB_TOKEN:
        required: true

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Devbox
        uses: jetify-com/devbox-install-action@v0.12.0
        with:
          enable-cache: "true"

      - name: Install Devbox dependencies
        run: devbox install
