name: Frontend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Devbox
        uses: jetify-com/devbox-install-action@v0.12.0
        with:
          enable_cache: 'true'
      
      - name: Install dependencies
        run: devbox run bun install
        working-directory: ./static/js
      
      - name: Run frontend tests
        run: devbox run fe:test