name: Frontend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: bun install
        working-directory: ./static/js
      
      - name: Run frontend tests
        run: bun test
        working-directory: ./static/js
      
      - name: Run frontend tests with coverage
        run: bun run test:coverage
        working-directory: ./static/js
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./static/js/coverage/lcov.info
          flags: frontend
          name: frontend-coverage