name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        group:
          - name: group-1
            packages:
              - github.com/brendanjerwin/simple_wiki/server
              - github.com/brendanjerwin/simple_wiki/index/frontmatter
          - name: group-2
            packages:
              - github.com/brendanjerwin/simple_wiki
              - github.com/brendanjerwin/simple_wiki/static
          - name: group-3
            packages:
              - github.com/brendanjerwin/simple_wiki/internal/grpc/api/v1
              - github.com/brendanjerwin/simple_wiki/templating
          - name: group-4
            packages:
              - github.com/brendanjerwin/simple_wiki/utils
              - github.com/brendanjerwin/simple_wiki/common
          - name: group-5
            packages:
              - github.com/brendanjerwin/simple_wiki/index/bleve
              - github.com/brendanjerwin/simple_wiki/labels
          - name: group-6
            packages:
              - github.com/brendanjerwin/simple_wiki/sec
              - github.com/brendanjerwin/simple_wiki/index
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.24

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        run: go build -v ./...

      - name: Test ${{ matrix.group.name }}
        id: run_tests
        run: |
          mkdir -p coverage_temp
          for pkg in ${{ join(matrix.group.packages, ' ') }};
          do
            COVER_FILE=$(echo $pkg | tr '/' '-')
            TEST_ENV=true go test -race -coverprofile=coverage_temp/$COVER_FILE.cover $pkg &
          done
          wait

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ matrix.group.name }}
          path: coverage_temp

  combine_and_upload_coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.24

      - name: Download coverage artifacts
        uses: actions/download-artifact@v4
        with:
          path: coverage-artifacts

      - name: Combine coverage
        run: |
          echo "mode: set" > coverage.txt
          find coverage-artifacts -name "*.cover" -exec cat {} + | grep -v "mode: set" >> coverage.txt

      - name: Upload combined coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.txt