name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - github.com/brendanjerwin/simple_wiki
          - github.com/brendanjerwin/simple_wiki/common
          - github.com/brendanjerwin/simple_wiki/index
          - github.com/brendanjerwin/simple_wiki/index/bleve
          - github.com/brendanjerwin/simple_wiki/index/frontmatter
          - github.com/brendanjerwin/simple_wiki/internal/grpc/api/v1
          - github.com/brendanjerwin/simple_wiki/labels
          - github.com/brendanjerwin/simple_wiki/sec
          - github.com/brendanjerwin/simple_wiki/server
          - github.com/brendanjerwin/simple_wiki/static
          - github.com/brendanjerwin/simple_wiki/templating
          - github.com/brendanjerwin/simple_wiki/utils
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.24

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        run: go build -v ./...

      - name: Test ${{ matrix.package }}
        run: |
          TEST_ENV=true go test -race -coverprofile=${{ matrix.package | replace('/', '-') }}.cover ${{ matrix.package }}

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report-${{ matrix.package | replace('/', '-') }}
          path: ${{ matrix.package | replace('/', '-') }}.cover

  combine_and_upload_coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.24

      - name: Download coverage artifacts
        uses: actions/download-artifact@v3
        with:
          path: coverage-artifacts

      - name: Combine coverage
        run: |
          echo "mode: set" > coverage.txt
          find coverage-artifacts -name "*.cover" -exec cat {} + | grep -v "mode: set" >> coverage.txt

      - name: Upload combined coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.txt
